### ISSUE TITLE
Streaming of Liveapp playlist to DLive is failing

### ISSUE THREAD

**Issue by walt93** [ant-media/Ant-Media-Server#4546] opened 2022-11-08 22:37 UTC
### Short description
Streaming to DLive is failing. Relevant log message seems to be this:

`2022-11-08 22:22:34,481 [NioProcessor-16] WARN  o.r.s.net.rtmp.InboundHandshake - Client not compatible
`

### Environment

* Ubuntu 20.04.5 LTS:
* Java version: openjdk version "11.0.16" 2022-07-19
* Ant Media Server version: That's a really good question. Literally just installed from Linode Marketplace & it installs via script, so assume the very latest.
* Browser name and version: N/A .... we haven't gotten to the browser yet

### Steps to reproduce
1. Create LiveApp->playlist of MP4 files (from URL, not uploaded to server)
2. Set Dlive RTMP stream key as endpoint
3. Start stream playing

### Expected behavior
Stream to play on DLive

### Actual behavior
Stream fails to play on DLive

 ### Logs
https://pastebin.com/66KmevRu

**Comment by yashtandon113** [comment] 2022-11-09 10:55
Hi @walt93
Thanks for creating the issue.
I attempted to reproduce the problem on my end by re-publishing the playlist stream to [dlive.tv](https://dlive.tv/s/dashboard#0), and it appears to be working properly. Could you please share the mp4 URL you used to make the playlist?
You can also send it to my email address directly : yash.tandon@antmedia.io

**Comment by walt93** [comment] 2022-11-10 20:22
Publish URL for the playlist is here rtmp://kappy.conspyre.tv/LiveApp/continuous_loop

Let me know if there's anything else I can add to help.

**Comment by yashtandon113** [comment] 2022-11-18 18:32
@walt93
I apologize for my delayed response.
Thank you for including your playlist details in my email. In my tests, the stream is successfully publishing on the Dlive RTMP ingest point.

![image](https://user-images.githubusercontent.com/82374739/202776588-c1e692ee-df03-4482-ac5b-7d5f4161ec57.png)

If it's still not working for you, we can look into it together.

**Comment by walt93** [comment] 2022-11-18 20:35
I'm thinking it's an issue with my dlive account?

I tried another test. I created a restream.io account, and pointed it to DLive, and sent Ant output to restream. It worked. For ≈48 hours. Now restream.io is stuck in a loop connecting/streaming/erroring out.

DLive seems to have no ability to get any log information. DLive support says to use OBS 🤣

What do you recommend as a debugging strategy?

**Comment by yashtandon113** [comment] 2022-12-12 06:19
@walt93
Is it now working for you?
If not, we can check it together. Please let me know if you are available for the meeting this week.

**Comment by walt93** [comment] 2022-12-12 08:44
I just now went through the install instructions and it seems that my ant media server is dead.

Loading the server from https://kappy.conspyre.tv:5443/ we get a login screen, but the "Let's go" button is dead.

Reloading the page redirects to https://kappy.conspyre.tv:5443/#/pages/login and we get a "can't connect to server"

What time zone are you in for a meeting? I am US/PST and fairly flexible for schedule.

**Comment by walt93** [comment] 2022-12-12 09:06
I am currently having some problems with the Ant media install, I was sent a snapshot of 2.6.0 and the server is no longer functioning after the install. I will come back to this shortly.

**Comment by yashtandon113** [comment] 2022-12-18 09:34
Hi @walt93 
Have you tested streaming to DLive using the snapshot version?

**Comment by asharamseervi** [comment] 2022-12-18 19:12
> I am currently having some problems with the Ant media install, I was sent a snapshot of 2.6.0 and the server is no longer functioning after the update. I will come back to this shortly.

Would recommend you to stay to latest stable release till upcoming version released. Snapshots are Beta version; if anything breaking it, you're welcome to open a new issue with logs, we'll look into this. Thanks.

**Comment by walt93** [comment] 2022-12-18 19:32
Go ahead and close this. I am unable to stream anything to DLive. I believe it is something on their end. I may try creating a new account because it initially worked. Then the account received a “strike” and has never been the same. e.g. started failing right after that.

**Comment by asharamseervi** [comment] 2022-12-18 20:13
cc: @yashtandon113 
As reported by walt93, we couldn't reproduce this anymore, hence we may close this issue.

For other users, who're facing similar issue, kindly create new issue by referencing this issue, to connect dots for further investigating. Thanks.

**Comment by yashtandon113** [comment] 2022-12-19 06:57
@asharamseervi, Thanks for your comments.

@walt93 
Thanks for the update. I am closing this issue.

**Closed by yashtandon113** 2022-12-19 06:57 UTC
Labels: Priority: Normal

**Comment by walt93** [comment] 2022-12-19 08:08
Go ahead and close. DLive is not working, but it stopped working in a global way (i.e. it looks like it should be working, but even OBS is failing now - where everything initially worked - ant / obs - all started out good…)
