### ISSUE TITLE
Problems with WebRTC

### ISSUE THREAD

**Issue by tomylee001001** [ant-media/Ant-Media-Server#17] opened 2018-01-17 13:39 UTC
i am trying to use webrtc to rtmp with this link "[https://github.com/ant-media/Ant-Media-Server/blob/master/doc/WebRTC_Publish_and_Play_JavaScript_SDK_Details.md](https://github.com/ant-media/Ant-Media-Server/blob/master/doc/WebRTC_Publish_and_Play_JavaScript_SDK_Details.md)" although some of the information for this link outdated i was able to send audio and video through "ws" socket to the antmedia server i instal our lan.
in the broadcast page everything looks ok. but when try to watch the broadcast with rtmp or http there is no problem with audio but my video look like this;
![stream](https://user-images.githubusercontent.com/20665133/35045316-1c6fdd74-fb9c-11e7-9904-14f94fc8a896.PNG)

Also if i try to watch this through WebRTC like it shown in that link my antmedia server crashes.

Last of all is there any documantation for how to config sssl to antmedia server so that i can work with https and wss.

Thanks for advance.

**Comment by tomylee001001** [comment] 2018-01-24 15:38
i also found another bug with WebRTC.
İf you try to send stream without audio server crashes.

**Comment by mekya** [comment] 2018-01-27 15:28
Thank you for this feedback. I am sorry for being late. 
Lately, we have been very busy for webrtc-to-webrtc 1:N low latency  solution. 

I am going to interested in these issues.

**Comment by tomylee001001** [comment] 2018-01-29 08:40
in your "WebRTC WebSocket Messaging Details" documentation it mention all commands returns from the webservice contains "streamName" key with the stream name we send when we publish or play stream. like this 
{
command : "takeConfiguration",
streamName : "stream1",
type : "offer",  
sdp : "${SDP_PARAMETER}"
}

but this "streamName" do not return right now.

also there are a lot more issues we are having try to work with antmedia server. 
We have couple of live meeting applications that are written with flex/flash and we wanna re-write them since flash having its last breath. and antmedia server is one of our candidates for this purpose.

**Comment by mekya** [comment] 2018-01-29 11:56
Hi @tomylee001001 ,

The documentation is generally based on Enterprise Edition.  In additino, Community Edition cannot play webrtc streams due to decoding-encoding requirements which are in enterprise edition

Btw, I can fix the missing parts in documentation for community version as well. 

For your previous errors, could you please try this [WebRTCApp 1.2.1 SNAPSHOT](https://oss.sonatype.org/service/local/repositories/snapshots/content/io/antmedia/webrtc/WebRTCApp/1.2.1-SNAPSHOT/WebRTCApp-1.2.1-20180129.094755-1.war) with Ant Media Server 1.2.0 version which is available to download on [releases](https://github.com/ant-media/Ant-Media-Server/releases)

**Comment by tomylee001001** [comment] 2018-01-29 13:11
@mekya 
i will try them as soon as i can and return you with the results.
so Webrtc to Webrtc is for enterprise addion only but Webrtc to rtmp/hls is both right?
if so when i broadcast via Webrtc and try to play the hls in my website, i am getting No 'Access-Control-Allow-Origin' error from media side and it refuse to play the video from my website but i can play with vlc player or inside the antmedia application page. is this also Community Edition problem or samething else. 
Also we are having some audio problems with Webrtc to rtmp/hls.  even though recorded video has no problem when we try to watch it live via vlc player audio stops every 1-2 second for an instant and continuous but video seems good. We try this with rtmp to rtmp/hls there is no problem at all.
And is there any documantion for enabling ssl in antmedia.
thanks in advance

**Comment by mekya** [comment] 2018-01-29 15:11
Hi @tomylee001001 ,

Yeah WebRTC to RTMP/HLS is available both on community and enterprise edition. 
'Access-Control-Allow-Origin' is just a CORS filter issue. I have added this configuration and send a new snapshot release to repo. [Check it out](https://oss.sonatype.org/service/local/repositories/snapshots/content/io/antmedia/webrtc/WebRTCApp/1.2.1-SNAPSHOT/WebRTCApp-1.2.1-20180129.145818-2.war)

We have been dealt with so much with audio and video synch issue on Enterprise Edition and we have fixed these issues on 1.2.0 EE version. Fortunately, I have added related modification to community edition WebRTCApp 1.2.1 snapshot as well.  Please try and let me know if it is working for you. If not, I have some more things to try as well ;)

Yeah I am going to publish a documentation today to blog page about enabling ssl in ant media server with a script that makes it very easy. Keep an eye on blog ;)
[antmedia.io/blog](https://antmedia.io/blog)

**Comment by tomylee001001** [comment] 2018-01-31 08:33
hi @mekya ,
Thanks for the update.
 i try the new version of WebRTCApp and these are my results;
1)The graphic issue i sent first; i did some try and error and found that this problem is about resolution of the webcam video. There is no problem with 640x480 and below but when you go over this that issue starts happing.with the update video seems mostly ok with 1280x720 i only see 1-2 times for an second that graphic issue but again with hd resolution that problem occurs more often.
2) Issue about antmedia crashes when you send stream without audio. Server still crashes if you send stream without audio.
3)No 'Access-Control-Allow-Origin' error when trying to play the webrtc broadcast with hls on a website. this issue resolved with the update.
4)Audio shutters and frozes every few seconds when watching webrtc broadcast with hls or rtmp. this issue still continues.i did a few test in the LiveApp when you send and receive rtmp everthings ok. but in the WebRTCApp the video you get from either hls or rtmp have this issue also after the end of the broadcast if you try to wacth the mp4 video this happens too.if you copy/paste the video to LiveApp folder it still continues but if you donwload the mp4 and watch it in local there is no problem with the video.you can also watch mp4 files without problem which recorded via LiveApp.

Also there are few things i wanna ask about.
1)how many broadcasters can publish in WebRTC simultaneously in EE/CE. in my tests after 4-5 of broadcasters servers Webrtc stops working.logs stop at "initialized". Also as you know in webrtc we cant always control users browser to properly send "stop" command. system should automatically send stop command if your websocket connection broken. right now server does some things with broken connection but not act like you send "stop" command. (for example when you send stop command server prepares the mp4 and deletes the m3u8 files but when you disconnect server only prepare the mp4 files leaving the m3u8 files intact). i dont know if its because of this but if start brodcasting for example with "stream1" key then close and open that browser few times the issue i mentioned happens and you cannot start broad cast with Webrtc again until service restart.
2)in the past we try the red5 as a live media server for out online conferences but we had a lot of problems with it  as soon as our viewer numbers reach 100+ even though server can easily capable of handling 400+ users. because of this right now we are using nginx for our live media server. can you give me any statistic how much user can antmedia handle and what kind of server it needs.

i will continue to try and test the antmedia for our needs and send you anything i found.we probably gonna needt he low latency webrtc wich comes with EE. but i need to make sure first this will solve all our problems. as you know how its with the bosses ;).

**Comment by mekya** [comment] 2018-02-01 07:12
Hi @tomylee001001 
Let me answer your questions :)

1) You have tried the latest WebRTCApp Snapshot right? If yes, let me check. 
2) Yeah probably we gonna try and fix the audio issue. Then we will make a new sub release with 1.2.1
3) OK.
4) I guess this issue is about threading in Community Edition, let me check. 

Questions
1) We have not worked much about Community Edition. Normally, in EE edition, it stops broadcasting if browser is closed or connection drop. Anyway, I am going to check it for community edition as well. 

2) First of all, I can say that Getting WebRTC and converting it to RTMP is a heavy process. Because stream should decoded and encoded again so it may use high cpu power. Video operations are all very cpu sensitive. Nevertheless, we are going to create a benchmark test for some customers as well and I am going to share it with you. 

Sure thank you for using Ant Media Server, I am going to do best I can to solve your problems. 

I am going to give more information about the issues above you have reported. Keep in touch.

**Comment by mekya** [comment] 2018-02-03 10:15
Hi @tomylee001001 ,

1) WebRTC to RTMP Adaptor which also encodes stream make the resolution 640x480 it is hard coded right now.  Any other resolution like 1280x720 does not in 4:3 ratio and in addition encoder needs to rescale the image. It is best to use 640x480 resolution to have both less cpu power and aspect ratio compatibility. I think we may force resolution 640x480 or 4:3 aspect ratio in javascript in Community Edition

2)  The audio issue should be fixed. Please try 1.2.1 SNAPSHOT. Link is available on README.txt https://github.com/ant-media/Ant-Media-Server

3) It was already fixed. 

4) I have tested this issue on a low performance ubuntu box. I did not reproduce this issue, Nevertheless we have some improvements for this issue as well. Could you please try again last version? If yes please let me know the exact scenario, I need to reproduce this issue on our local environment. 

Answers to Questions
1) Community edition stops WebRTC to RTMP Adaptor if websocket connection is closed or connection is disclosed. We also protect these calls with signalling thread in 1.2.1 SNAPSHOT.  Even so, server creates different mp4 files for the streams with the same name.  In production, there will be no stream with the same name anyhow.  Rest services create unique id for stream urls.

2) Load tests are not ready yet. 

Consequently, Please try the latest snapshot release and let me know your results.

**Comment by tomylee001001** [comment] 2018-02-06 11:03
hi @mekya ,

Sorry about late respond i was caught up with some other projects. i downloaded the 1.2.1 SNAPSHOT and i will this and return to you with results. Also i didn't quite understand what you mean in your first answer to my questions.

**Comment by FedorovP777** [comment] 2018-03-08 09:36
same problem

**Comment by mekya** [comment] 2018-08-30 13:41
Hi,

This issue is fixed with v1.4.0+ version, please check it out. 

If you are still having the same issue, please reopen this issue. 

Regards,
A. Oguz

**Closed by mekya** 2018-08-30 13:41 UTC

**Comment by deveshspraxa** [comment] 2021-01-20 19:44
Hi @mekya 

We are facing same issue under snapshot version of Ant Media server -Enterprise Edition 2.3.0

Details -
1. We start publishing stream through our server on Ant media - it shows Broadcasting but didn't play at all
2. We check other streams too they work fine but after some load like more then 50 to 60 streams this issue generally comes up

**Comment by mekya** [comment] 2021-02-16 08:49
Hi @deveshspraxa ,

There is a known in one of snapshot version in some snapshots of 2.3 related to this stuff. 

Btw, I'm not sure if you're using RTMP playback. We don't recommend to play the stream with RTMP anymore. It's deprecated. We'll completely remove RTMP playback support for one of the upcoming releases. We've implemented Low Latency Dash(CMAF) for having similar latency in RTMP. 

Regards,
A. Oguz
