### ISSUE TITLE
Ant Media Server running out of Memory

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#5029] opened 2023-04-24 09:30 UTC
I have encountered a couple of reports in which the server runs out of Memory and needs to be restarted.
The server keeps printing messages like `java.lang.OutOfMemoryError: Physical memory usage is too high: physicalBytes (5095M) > maxPhysicalBytes (3832M)`

This happens mostly for two use cases:
1. When there are many streams running for a long duration like 5-6 hours.
2. For use cases that require 24/7 streaming.

Memory usage keeps increasing unless the server is restarted then it keeps increasing again.
A couple of customers have reported this issue for AMS v2.4.3 and AMS v2.5.3

**Comment by Mohit-3196** [comment] 2023-04-30 14:39
There are two different environments:

1.  Standalone server:
Instance type: 10 CPU cores 8GB RAM with 132GB storage
No. of concurrent streams: 17 to 20 running 24/7 and there is no adaptive setting.
AMS v2.5.3

2. Cluster Environment:
Instance type: All nodes in the cluster are c5.xlarge - 4 CPU cores with 8GB RAM
No. of streams: 200 to 800
stream duration: 1 minute to 6hrs
AMS v2.4.3

Thank you

**Comment by mekya** [comment] 2023-05-02 10:02
Are there any users watching the streams?

**Comment by Mohit-3196** [comment] 2023-05-02 10:57
Yes, there are users watching the streams as well.

**Comment by riftdea-isj** [comment] 2023-05-03 04:13
Hi,

I'm the one who have:

1. Standalone server:
    Instance type: 10 CPU cores 8GB RAM with 132GB storage
    No. of concurrent streams: 17 to 20 running 24/7 and there is no adaptive setting.
    AMS v2.5.3
    OS: ubuntu 20.04

To elaborate to reproduce the problem. 
After installation of AMS v2.5.3 and putting in 20 stream source.
Some on the physical devices of my camera is down so the stream link aren't suppose to be working hence the forever preparing status.
![image](https://user-images.githubusercontent.com/132421851/235829496-42f7d520-dca1-4447-b875-108ad48fdca4.png)

Most of the time there is no viewers since it's a test environment. If there is viewer, would be at most be 20viewer per day only on weekdays around 2-3day per week. The server is running 24/7.
Regardless there is viewers or not, the RAM will increase 2-3% daily. If the server is up for 2 week, it reaches 65% memory in idle states with 0 viewers, and will continuously increase the next day.

![image](https://user-images.githubusercontent.com/132421851/235829940-7e69d350-4b28-4258-b483-011d2feb2096.png)
As you can see from the picture, error log always created up to date.

The content mostly are,
![image](https://user-images.githubusercontent.com/132421851/235830079-628a3c61-b542-4aa0-a3bb-a0cc1bd8e7ed.png)

99% of the time is this full of duplication of this error message
[hls @ 0x7f93e8030a80] Opening '/usr/local/antmedia/webapps/WebRTCAppEE/streams/485014293894173603848289.m3u8.tmp' for writing
[hls @ 0x7f93cc029380] pkt->duration = 0, maybe the hls segment duration will not precise

This is my HLS Streaming Setting:
![image](https://user-images.githubusercontent.com/132421851/235831634-44334a45-e545-474d-bbe3-1d1c249f09cc.png)
And as mentioned by Mohit, no adaptive streaming.

Hopefully this helps.

**Comment by Mohit-3196** [comment] 2023-05-08 09:39
Hi All,
I would like to update this issue with more details.

I came across another issue:
AMS v 2.5.3
Cluster with 2x c5.4xtralarge EC2 instances
Ubuntu 18.04
When the ingestion server went OOM, there was 1 webrtc stream, no adaptive streaming, and around 200 viewers. 
**The server uptime was 120 days.
FD ticket: 92690**

I'm trying to reproduce the OOM issue with a t2.micro instance type on AWS but the issue has not been reproduced yet.


Also, I have updated the logs from all three cases here https://drive.google.com/drive/folders/1ObkJ_wozw0cJUMSy15sN03xSjZpQlQOT

**Comment by mekya** [comment] 2023-05-22 11:39
Let us have the heap dump

**Comment by Mohit-3196** [comment] 2023-05-25 15:43
Here are the heap dumps from another user.
https://streambid.sharepoint.com/:f:/s/StreambidLtd/EoCcEXJAZkpDkWlMXVU0oXsBDahWH6Te2V4sCb75XDC2Tg?e=5%3aKCmF4Z&at=9

Also MAT analysis for one of the nodes
![jK0PtboKgOvqGO5CzNjaefLnmbIVAfcEDA](https://github.com/ant-media/Ant-Media-Server/assets/86982446/c526333d-b356-48dc-80e6-eb20726cbb23)

**Comment by oleul05** [comment] 2023-05-29 10:43
I am using Vultr Kubernetes Engine for AMS. For my case push RTSP camera streams from source by FFmpeg to Ant Media's RTMP server.
Server configuration: CPU optimized, RAM 16GB and CPU : 8.
Database: MongoDB cluster also installed in Vultr.
Example push command: 
ffmpeg -i input.mp4 -codec copy -f flv rtmp://domain/LiveApp/stream_01
After running 68 streams around 20 hours I received the following error
"Exception in thread "ContainerBackgroundProcessor[StandardEngine[red5Engine]]" java.lang.OutOfMemoryError: Java heap space"
I have attached all the log and java_pid1.hprof file in the following google drive.
https://drive.google.com/drive/folders/1TbL80vblMyNZXy02MCD1cgdT6Lzpzk5R?usp=sharing
FYI I didn't receive this error for standalone AMS.

**Comment by timantmedia** [comment] 2023-05-30 10:10
**FD: 94146 for @oleul05**

**Comment by mekya** [comment] 2023-06-12 10:12
Hi @Mohit-3196 
There is a fix for the below case. It happens in both cluster and standalone mode. It's merged into the master.
Share the version when you see the "fix-memory-leakage" PR in the enterprise/changelog (https://antmedia.io/changelog/changelog.html)

> Here are the heap dumps from another user. https://streambid.sharepoint.com/:f:/s/StreambidLtd/EoCcEXJAZkpDkWlMXVU0oXsBDahWH6Te2V4sCb75XDC2Tg?e=5%3aKCmF4Z&at=9
> 
> Also MAT analysis for one of the nodes ![jK0PtboKgOvqGO5CzNjaefLnmbIVAfcEDA](https://user-images.githubusercontent.com/86982446/240965365-c526333d-b356-48dc-80e6-eb20726cbb23.png)

**Comment by mekya** [comment] 2023-06-14 16:36
Hi @oleul05 ,

I've analyzed the log files. I think the main problem is that there is a problem in MongoDB server and it blocks threads so that threads cannot run. The incoming packet are not processed and it fill the memory and then it will give out-of-memory eventually. 

What I've done to not encounter this problem. 
- Make the worker thread count the same as rtmp executor thread count so that there will be more threads to consume the incoming packets 
-  Increase the timer period - that is blocker in the logs and I encounter the same problem in different places - writes the stream quality updates to the MongoDB from 1 second to 5 seconds. I think 1 second is too frequent and user just get updates for 10 seconds or more. 

To sum up, 
- I've sent a [PR for this scenario](https://github.com/ant-media/Ant-Media-Server/pull/5247). Please test it after it's merged at your convenient time. 
- Check your MongoDB instance./cluster You may powerup them.
 
If the problem persists on your end, we can take a look together.

Thank you for being with us on this journey :)

Oguz

> I am using Vultr Kubernetes Engine for AMS. For my case push RTSP camera streams from source by FFmpeg to Ant Media's RTMP server. Server configuration: CPU optimized, RAM 16GB and CPU : 8. Database: MongoDB cluster also installed in Vultr. Example push command: ffmpeg -i input.mp4 -codec copy -f flv rtmp://domain/LiveApp/stream_01 After running 68 streams around 20 hours I received the following error "Exception in thread "ContainerBackgroundProcessor[StandardEngine[red5Engine]]" java.lang.OutOfMemoryError: Java heap space" I have attached all the log and java_pid1.hprof file in the following google drive. https://drive.google.com/drive/folders/1TbL80vblMyNZXy02MCD1cgdT6Lzpzk5R?usp=sharing FYI I didn't receive this error for standalone AMS.

**Closed** 2023-06-26 11:23 UTC
Labels: investigating, Priority: Important

**Comment by timantmedia** [comment] 2023-07-20 10:52
@oleul05 To clarify, you have tested with the recommended PR and still experiencing a high memory usage of your AMS instance? @mekya This PR https://github.com/ant-media/Ant-Media-Server/pull/5247 is merged, I assume with the latest version that should resolve the issue? Ole is still seeing high memory usage FD98911
