### ISSUE TITLE
issue in video streaming

### ISSUE THREAD

**Issue by sanjeetakc** [ant-media/Ant-Media-Server#3221] opened 2021-04-30 05:55 UTC
When the internet is turned off during streaming it will take some time to call
	 onDisconnected function so in the video, it will contain the black screen for 5 to 6 sec

### Environment

* Operating system and version: Android
* Java version: 
* Ant Media Server version:
* Browser name and version:

### Steps to reproduce
1. 
2. 
3.

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by mekya** [comment] 2021-05-03 17:44
Hi @sanjeetakc ,

Could you please write your expectation for this scenario?

**Comment by sxudan** [comment] 2021-05-04 03:07
Hello @mekya,

After internet is turned off, onDisconnected is not called immediately and black screen will be appended to the video (black screen probably after internet disconnection). Is the delay due to reconnection? Can we set reconnect option to false so that when internet is turned off, onDisconnect is called immediately and how to not append black screen on the video?

**Comment by mekya** [comment] 2021-05-06 09:18
Hello @sxudan ,

You can set the reconnect option to false. 

There are following code snippets in the sample project. 

```
 Handler reconnectionHandler = new Handler();
    Runnable reconnectionRunnable = new Runnable() {
        @Override
        public void run() {
            if (!stoppedStream && !webRTCClient.isStreaming()) {
                webRTCClient.startStream();
                if (webRTCMode == IWebRTCClient.MODE_JOIN)
                {
                    pipViewRenderer.setZOrderOnTop(true);
                }
            }
            if (!stoppedStream) {
                reconnectionHandler.postDelayed(this, RECONNECTION_PERIOD_MLS);
            }
        }
    };
```

You can completely comment out these lines and related references. Then reconnect option will be disabled

As far as I remember `onDisconnected` event is called immediately if the WebRTC stack detects there is no connection. In some scenarios, it may take a few seconds. If it takes longer for you, we can take a look at the code. 

When `onDisconnected` is called, you can change the visibility of the view in order to not get black screen. 

I hope it would help you

Regards,
A. Oguz

**Comment by sxudan** [comment] 2021-05-06 10:51
Hello @mekya, 

Thanks you for your suggestion. The problem is  after the internet is turned off, onDisconnected() is called after 5 to 6 seconds so I am having hard time preventing the black screen too. And for the info the black screen is appended from the point of internet disconnect to the point where onDisconnected() is called.  So, Can you please look into the code.

**Comment by mekya** [comment] 2021-05-06 11:45
Let me go through this way. If you want us to check why onDisconnected is called after 5-6 seconds, we can schedule this issue and we can make some analysis for that.  

On the other side, I can recommend a workaround solution. If you want to make the black screen invisible immediately when the internet is turned off, maybe you should listen network changes in the Android side.

**Comment by sxudan** [comment] 2021-05-06 16:37
Okay sure thanks for your time

**Comment by sxudan** [comment] 2021-05-09 11:54
Hello @mekya ,

The problem I am facing is even if I call stop() when user get disconnected from internet, the video will contain freezed frames at the end of the video probably of duration 6- 8 seconds. Can you please tell me what I did wrong here.

Here is the for broadcast receiver which is called when the network connectivity is changed.

BroadcastReceiver connectivityReceiver = new BroadcastReceiver() {
        @Override
        public void onReceive(final Context context, final Intent intent) {
            if (!checkInternet(context)) {
               if(client.isStreaming()) {
                   client.stop();
               }
            }
        }

        public boolean checkInternet(Context context) {
            ServiceManager serviceManager = new ServiceManager(context);
            return serviceManager.isNetworkAvailable();
        }
    };

**Comment by mekya** [comment] 2021-05-10 06:49
Hi @sxudan ,

When you call stop(), it's ok to freeze the frames. It's an expected behavior. 

If you are running 6-8 seconds video after you call the stop. You are having a very bad network connection or alternatively there is a fundamental problem in your development. 


TBH, in order to understand the problem please write what you're doing step by step, expected behavior and actual behavior as we request in the bug report. Otherwise, as you see, both you and I are spending more time to understand the problem. Please make life easy and simple for both of us.

**Comment by sxudan** [comment] 2021-05-10 09:02
Okay sure.

**What am I doing?**
- Trying to publish the live stream media to the server.

**Expected behavior**
- When stop() is called after internet is turned off, I need onDisconected()  to be called immediately or maybe 1 to 2 seconds delay is fine.
- When stop() is called after internet is turned off, the video must not contain the data after the stop().

**Actual behavior**
- When stop() is called after internet is turned off, onDisconnected() takes too much time (5 to 6 seconds ) to be called.
- When stop() is called after internet is turned off, the video will contain the freezed frames of duration 5 to 6 seconds after the point of stop(). So, if I record 10 seconds video and after 10 seconds I turned off the internet, the recorded video will contain the video of duration 16 seconds where those 6 seconds are the bunch of freezed frames. There is no problem in iOS in this scenario BTW.

Hope you understand this. Cheers!!

**Comment by mekya** [comment] 2021-05-18 06:03
Thank you for the report. We are moving this to the backlog and we'll schedule this issue.
I wish we schedule it immediately but there are some priority issues.

**Comment by golgetahir** [comment] 2021-05-24 09:53
Hi @sxudan

I made some tests for your inquiry, @mekya it is reproducible but I am not sure 

What am I doing?

Trying to publish the live stream media to the server.
**-) I am using the Sample Android Application of Ant Media Server on Samsung Galaxy M31 (SM-M315F)**

Expected behavior

When stop() is called after internet is turned off, I need onDisconected() to be called immediately or maybe 1 to 2 seconds delay is fine.

**-)If you manually click on stop() method the onDisconnected() is called immediately**
**-) However if you disconnect from the internet, onDisconnected() is not called immediately, and the user media is being continued to gathered for a while on the user's phone, of course there is no data being sent to the server, so server side is unrelated**

When stop() is called after internet is turned off, the video must not contain the data after the stop().
Actual behavior

When stop() is called after internet is turned off, onDisconnected() takes too much time (5 to 6 seconds ) to be called.
When stop() is called after internet is turned off, the video will contain the freezed frames of duration 5 to 6 seconds after the point of stop(). So, if I record 10 seconds video and after 10 seconds I turned off the internet, the recorded video will contain the video of duration 16 seconds where those 6 seconds are the bunch of freezed frames. There is no problem in iOS in this scenario BTW.

**-) Here I think the client is recording the video on the client side, not in the server side. Because server acts immediately when the packets are not coming. So therefore what the client requests is that our SDK is still reaching the user media after the internet connection drops, how about recording the videos on server side maybe? **

**What I've observed is that I think the Android webrtc stack ICE connection update mechanism is a bit slower because we are using the callbacks only,  `public void onIceDisconnected()`  method is called before `onDisconnected()` , however it doesn't save much time ( at most 1 sec ). I hope the issue is cleared out here, can you confirm @sxudan ? We can proceed if you confirm that we cleared out the issue.**

Cheers

**Comment by sxudan** [comment] 2021-05-24 11:14
Hello @golgetahir ,

I think these statements are not for me, Are they?
`Here I think the client is recording the video on the client side, not in the server side. Because server acts immediately when the packets are not coming. So therefore what the client requests is that our SDK is still reaching the user media after the internet connection drops, how about recording the videos on server side maybe?`

### Regarding this issue: When stop() is called after internet is turned off, the video must not contain the data after the stop().
**Correct me if I am wrong, Since, WebRTC is peer-peer communication, our mobile device is one peer and the server is another peer right? If, PeerA (android) gets disconnected due to internet, the ice status of peerB(server) changes to disconnected right? So, why is it working in iOS but not in Android? In iOS, there will be no extra freezed clips after internet is disconnected.**

### Regarding this issue: onDisconnected() not called immediately
-> Yes, I am totally clearead regarding this issue.

Thank you for the response :) 

With Regards,
@sxudan

**Comment by golgetahir** [comment] 2021-05-24 11:48
`Correct me if I am wrong, Since, WebRTC is peer-peer communication, our mobile device is one peer and the server is another peer right? If, PeerA (android) gets disconnected due to internet, the ice status of peerB(server) changes to disconnected right? So, why is it working in iOS but not in Android? In iOS, there will be no extra freezed clips after internet is disconnected.`

In my tests servers peer connection is disconnected immediately, android client does not get disconnected immediately but server does. Is it possible that you are checking it from the client side but not from the server side? Please control it from the Ant Media management panel.

It does not seem possible for server to continue recording after your internet connection on mobile device drops because the server can't physically get packets and when the packets does not arrive the server reacts in about 1 second. Do I understand it wrong ? Is it possinle that your internet fluctuates rather than dropped? Can you take a video if I understand wrong because it is getting a bit hard to understand

**Comment by sxudan** [comment] 2021-05-24 13:00
Hello @golgetahir ,

I think we misunderstood each other. Okay let's forget about disconnect method.

**What I want?**
-> I dont want unwanted video frames after internet disconnect. Please check the video in the zip file. The video in the zip file is 14sec long. I disconnect the internet in 9seconds but the video contains 5seconds extra frames.

[rec1.zip](https://github.com/ant-media/Ant-Media-Server/files/6532447/rec1.zip)

Sorry for the trouble mate. Hope you understand the problem after you watch the video.

Cheers!

**Comment by golgetahir** [comment] 2021-05-31 15:53
Hello,

Let's have a meeting on this issue with a call, is that something OK for you? Can you reach me from tahir.golge@antmedia.io for the call?

Cheers.

**Comment by golgetahir** [comment] 2021-06-07 18:20
Hi @sxudan

Couldn't hear from you, isn't meeting is feasible for you?

**Comment by sxudan** [comment] 2021-06-08 03:01
Hi @golgetahir,
Sorry for the late reply. Yes, I will reach you out at the email above. Thanks!

**Comment by golgetahir** [comment] 2021-06-20 17:32
Hi @sxudan

Firstly we decided to improve and work on our disconnect mechanism, here is an issue for that: https://github.com/ant-media/Ant-Media-Server/issues/3358

Making the disconnection immediately recognize by the server creates an issue that, for now, if the internet connections stabilizes before timeout, the connection will continue afterwards only with a small lag. However, if we make the disconnection timeout immediate, even with the smallest internet fluctuations your stream will end recording. So I am not sure what kind of a solution we will do but we will work on the issue, you can follow it on the above link.

Cheers

**Closed** 2021-08-30 17:01 UTC
