### ISSUE TITLE
Start publishing without video(audio only) in the beginning of WebRTC stream and enable video after sometime

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#3478] opened 2021-07-26 21:28 UTC
Some of our clients want to publish WebRTC stream without video.

**Comment by mekya** [comment] 2021-08-02 15:49
Audio only support is already available. I don't understand the question

**Comment by sagark1510** [comment] 2021-08-06 07:28
@mekya  yes that is available the problem is once you start with audio only I mean by making `{audio: true, video: false}`. later in the call you can not stream the video no matter what.

**Comment by mekya** [comment] 2021-08-07 14:32
Thank you @sagark1510, I got the point. 

Quick workaround is opening video and audio at first and then closing the video track. With this solution, you enable video at any time. 

Make sense?

**Comment by sagark1510** [comment] 2021-08-08 08:57
@mekya True that and I'm doing that too. But that is bad user experience to ask for Video permission even though user just want to do a audio only session. I'm developing mobile app.

**Comment by mekya** [comment] 2021-08-09 07:50
Yes, you're right. Thank you for the feedback. Sent to the backlog to schedule.

**Comment by golgetahir** [comment] 2021-08-16 14:02
Hi all,

New development about the issue is here: https://github.com/ant-media/StreamApp/pull/202/files

I hope it solves your problems.

Cheers

**Comment by sagark1510** [comment] 2021-08-17 08:26
@golgetahir Thank you for the update. Can you tell me what changes I need to do on this lib https://github.com/TecladistaProd/rn-antmedia/

**Closed** 2021-11-15 17:56 UTC
