### ISSUE TITLE
Custom App create issue when using latest StreamApp war file

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#6177] opened 2024-03-12 08:16 UTC
### Short description
When the user tries to create the application using the latest StreamApp war file, the application does not create on the server (for example, v2.8.2). But in the webapps folder, the application directory is created in the backend and after that, even if you try to create the application using the default war file or with the 2.8.2 StreamApp war file, it does not have the same name.

To make it work, you need to delete the app directory first from the webapps folder and then the user would be able to create the application again with the same name.

### Environment
* Ant Media Server version: v2.8.2

### Steps to reproduce
1. Install v2.8.2 of AMS
2. Create war file using the StreamApp repo with master branch
3. Try to create the application using that war file
4. The application will not create
5. Try to create the app again by using the 2.8.2 StreamApp war file or without using the custom war file with the same name

### Expected behavior
Application should be created

### Actual behavior
Application has not created with the same name again

To make it work, you need to delete the app directory first from the webapps folder and then the user would be able to create the application again with the same name.

**Comment by burak-58** [comment] 2024-03-18 06:53
When we try to create an app which is created a newer branch than AMS and also if there is some class definition differences in red5.xml then application is created under webapps folder but throws some exceptions. So we can not see the app in the dashboard. Since it has folder in webapps folder, server cannot create an app with the same name.

**Comment by mekya** [comment] 2024-05-06 17:08
Hi @yashtandon113 and @burak-58 

It may be an expected behaviour. We can keep the backward compatibility in the other direction. 

Older application versions can be created on new Ant Media Server versions. I also know that there is a problem with this way also and I've fixed it. 

Then I'm closing this issue, please feel free to re-open if you think this is a mistake. 

Cheers
Oguz

**Closed by mekya** 2024-05-06 17:08 UTC
