### ISSUE TITLE
SRT Ingest does not reconnect after connection loss

### ISSUE THREAD

**Issue by timantmedia** [ant-media/Ant-Media-Server#5736] opened 2023-10-26 09:35 UTC
### Short description

If there is a sudden and short-lived connection loss during RTMP ingestion, the connection is re-established, however, if the same happens when ingesting SRT, the connection is broken and does not recover. 

Either there is a very small reconnection window with SRT or none at all. 

FFMPEG 

```
ffmpeg -re -stream_loop -1 -i bigbuckbunny.mp4 -c:v libx264 -c:a aac -f flv rtmp://ant-media-server/LiveApp/stream1
```
SRT

```
ffmpeg -re -stream_loop -1 -i ./bigbuckbunny.mp4 -vcodec libx264 -profile:v baseline -g 60 -an -f mpegts "srt://ant-media-server:4200?streamid=LiveApp/stream1"
```

Simulate connection loss for 10 seconds by running the shell script during ingestion

```
#!/bin/bash
sudo tc qdisc add dev eth0 root netem loss 100%
sleep $1
sudo tc qdisc del dev eth0 root
```

### Environment

* Operating system and version: ubuntu 22
* Java version: 
* Ant Media Server version: 2.6.4
* Browser name and version: none

### Steps to reproduce
1. Use either of the FFMPEG commands above to start streaming
2. during live streaming execute the shell script on the ingest server
3. observe how SRT disconnects completely whereas RTMP resumes live streaming once the script has completed

### Expected behavior
Either ingestion method should recover the live stream after a short-lived connection loss.

### Actual behavior
Only RTMP reconnects. 

 FD111570

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by timantmedia** [comment] 2023-10-26 09:36
@mekya @mustafaboleken @burak-58 @lastpeony  Is this behavior expected.

**Comment by timantmedia** [comment] 2023-10-26 10:05
Looks like SRT timeout is 5 seconds https://github.com/ant-media/Ant-Media-Server/issues/4434

**Comment by mekya** [comment] 2023-10-30 11:52
Hi @timantmedia,

No, it's not expected. The same problem is happening on the latest snapshot? Because we've some improvements in the latest verion

Regards

**Comment by timantmedia** [comment] 2023-10-30 13:01
@mekya I've not tried on the latest snapshot. Let me test and comment back.

**Comment by timantmedia** [comment] 2023-10-30 15:34
@mekya same thing happens on ovh36 thats running 2.7.0 snapshot version.

**Comment by mekya** [comment] 2023-11-06 11:57
Thank you for the update @timantmedia

**Comment by timantmedia** [comment] 2023-11-16 13:47
@mekya was this resolved when this https://github.com/ant-media/Ant-Media-Server/issues/5504 was fixed in latest release?

**Comment by mekya** [comment] 2023-11-20 10:56
As far as I remember I've fixed on my end but  I need to check again

**Comment by timantmedia** [comment] 2023-11-27 09:48
@mekya can we check if this is expected to be fixed in 2.7.0

**Comment by mekya** [comment] 2023-11-27 10:11
Hi @timantmedia,

Yes, it's expected to be fixed in 2.7.0 but it seems that I miss something to update it accordingly. 

Let me know if the problem exists in 2.7.0.

**Comment by USAMAWIZARD** [comment] 2023-12-12 12:34
I am able to reproduce this in 2.8.0

**Comment by USAMAWIZARD** [comment] 2024-01-15 03:07
We have investigated the issue with our scenario developer , the issue is from client side the RTMP uses TCP where as SRT uses UDP for the connection , we also tried configuring various configuration for ffmpeg connect_timeout timeout etc..
but nothing seems to work there , I have also tested this scenario with OBS which re-connects after approx 45 sec , you can either use OBS or create a custom solution script which can republish the stream in cases of disconnection.

**Comment by USAMAWIZARD** [comment] 2024-01-24 05:20
I am closing this issue now , please feel free to re-open the issue if the above suggested things does not works for you.

**Closed by USAMAWIZARD** 2024-01-24 05:20 UTC
Labels: investigating, Confirmed
