### ISSUE TITLE
Stuttering or Flickering issue with openh264 encoder on 16 or 32 core server

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#5086] opened 2023-05-10 16:30 UTC
### Short description
When ABR is enabled, AMS now utilizes the open264 encoder starting with v2.5.1. However, when using ABR on a 16 or 32 core server, the stream stutters or flickers, although there is no such problem on a 4 or 8 core server.

### Environment

* Operating system and version: Ubuntu 20.04
* Java version: Java 11
* Ant Media Server version: v2.5.3 and above

### Steps to reproduce
1. Install AMS on 16 or 32 core CPU server
2. Enable the multiple ABRs (1080p, 720p and 480p)
3. Publish the stream with 1080p
4. Play the stream on play.html or player.html

### Expected behavior
Stream should play fine without any issue.

### Actual behavior
When playing in 1080p or 720p resolution, the stream stutters and flickers.
 
### Work around solution used
To resolve the problem, we must utilise libx264 and adjust the encoder thread count setting.
The steps outlined in the following post are used to change the encoder.
https://github.com/orgs/ant-media/discussions/5087

**Comment by mekya** [comment] 2023-05-11 10:46
Hi @yashtandon113 ,
This is a known issue and it's fixed in this issue
https://github.com/ant-media/Ant-Media-Server/issues/4471

It is available as snapshot and it will be available in 2.6.0 probably next week

**Comment by mekya** [comment] 2023-05-11 10:47
So I'm closing this issue as duplicate and fixed
https://github.com/ant-media/Ant-Media-Server/issues/4471

Please feel free to re-open if the problem is still there.

**Closed by mekya** 2023-05-11 10:47 UTC

**Comment by yashtandon113** [comment] 2023-05-11 11:13
@mekya 
Thanks for the information. I will test it today and update the status.
