### ISSUE TITLE
av_interleaved_write_frame() error -32 while writing interleaved audio packet.

### ISSUE THREAD

**Issue by muratugureminoglu** [ant-media/Ant-Media-Server#2579] opened 2020-10-07 21:15 UTC
### Environment

* Operating system and version: Ubuntu 18.04
* Ant Media Server version: Ant Media Server Community 2.1.0

### Logs

```
2020-09-26 21:31:33,536 [pool-14-thread-1] ERROR i.a.webrtc.adaptor.RTMPAdaptor - io.antmedia.recorder.FrameRecorder$Exception: av_interleaved_write_frame() error -32 while writing interleaved audio packet.
	at io.antmedia.recorder.FFmpegFrameRecorder.writePacket(FFmpegFrameRecorder.java:1290)
	at io.antmedia.recorder.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:1276)
	at io.antmedia.recorder.FFmpegFrameRecorder.writeSamples(FFmpegFrameRecorder.java:1247)
	at io.antmedia.recorder.FFmpegFrameRecorder.recordSamples(FFmpegFrameRecorder.java:1222)
	at io.antmedia.webrtc.adaptor.RTMPAdaptor.lambda$null$2(RTMPAdaptor.java:238)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
### All Log File
[ant-media-server.log.gz](https://github.com/ant-media/Ant-Media-Server/files/5343866/ant-media-server.log.gz)

**Comment by iAmcR** [comment] 2020-10-10 00:36
Also occurs on **macOS Catalina (10.15.6) with Java 8**. 

**log snippet:**

2020-10-09 19:29:25,785 [pool-11-thread-1] io.antmedia.webrtc.adaptor.RTMPAdaptor - io.antmedia.recorder.FrameRecorder$Exception: av_interleaved_write_frame() error -32 while writing interleaved audio packet.
	at io.antmedia.recorder.FFmpegFrameRecorder.writePacket(FFmpegFrameRecorder.java:1290)
	at io.antmedia.recorder.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:1276)
	at io.antmedia.recorder.FFmpegFrameRecorder.writeSamples(FFmpegFrameRecorder.java:1247)
	at io.antmedia.recorder.FFmpegFrameRecorder.recordSamples(FFmpegFrameRecorder.java:1222)
	at io.antmedia.webrtc.adaptor.RTMPAdaptor.lambda$null$2(RTMPAdaptor.java:238)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by mekya** [comment] 2020-10-12 16:53
I've analyzed the logs and I understand why it happens. Let us schedule this fix on our end. When it's assigned to someone, it's likely scheduled at that week.

**Comment by JonathanBristow** [comment] 2020-10-14 16:04
@mekya Hi, is this an issue in the enterprise version as well? I need to get Audio only recording working ASAP and this issue appears to be blocking me.

**Comment by golgetahir** [comment] 2020-10-27 11:09
@JonathanBristow Hi Jonathan, the issue is not related with Enterprise edition. It happens when the maxWaitTime exceeded for getting the packets of streams. maxWaitTime is given 5 seconds for streams. The bug in this case is error was keep looping while we expect the connection to stop since there no packets arrive to the server about the streams. I linked the related pull request.

**Closed** 2020-11-16 06:09 UTC
