### ISSUE TITLE
Error: Playback cannot continue. No available working or supported playlists.

### ISSUE THREAD

**Issue by studentAlanMorgan** [ant-media/Ant-Media-Server#5346] opened 2023-07-08 09:55 UTC
>ant media shows that the stream is online.
when you try to play it, it gives an error or an eternal download appears.
Error: Playback cannot continue. No available working or supported playlists.

Community Edition 2.6.2

**Comment by mekya** [comment] 2023-07-10 09:36
Hi @studentAlanMorgan,
We would be very happy if we assist you while you're using Ant Media Server. 

On the other hand to understand the issue in a better way, I'm gently asking you to explain your problem in a more clear way. Just assume that you're telling the problem to dummy guys. (Assume that we're dummy :D )

For instance, how do you publish and how do you play the stream. We then try on our end and check if it's reproducible.

**Comment by studentAlanMorgan** [comment] 2023-07-11 04:24
> 

Detail:
I create a broadcast via rtsp, Ant shows that the camera is online and shows it in green. But when I connect to it, it shows an error that I wrote in the topic, or an eternal download appears.
![Ant_No_Conekt](https://github.com/ant-media/Ant-Media-Server/assets/81875252/d1eded7d-ce6b-4cbf-81a6-6044c90e0e2b)

**Comment by yashtandon113** [comment] 2023-07-12 11:16
@studentAlanMorgan 
Thanks for sharing the video.

It appears that there is a problem with the stream because the broadcasting speed is also 0.00x. Have you attempted to restart the stream?
If the problem persists, could you kindly send your AMS credentials to my email address: yash.tandon@antmedia.io so that I can look into it further?

**Comment by yashtandon113** [comment] 2023-07-21 12:20
@studentAlanMorgan 
I am closing this issue. If you are still experiencing the same probelm, please email me.

**Closed by yashtandon113** 2023-07-21 12:20 UTC
Labels: support
