### ISSUE TITLE
Broadcasting is Active but Streams only Show  "Stream will start playing automatically when it is live"

### ISSUE THREAD

**Issue by takai-sama** [ant-media/Ant-Media-Server#3646] opened 2021-09-27 10:43 UTC
# Issue
when i'm adding stream source, it says Broadcasting 1.00x .But when i start playing the stream, only Show  "Stream will start playing automatically when it is live". i try to start recording mp4 ,(in VoD) the stream start properly. 

* Operating system and version: docker with linux 20.04
* Ant Media Server version: Community Edition 2.4.0.2 20210905_1320

ps: I used version Community Edition 2.0.0 and everything worked fine

Stream in liveapp
<img width="600" alt="1" src="https://user-images.githubusercontent.com/77669943/134892779-a3d6e260-bb96-4b4d-9de6-533c04f2fd0d.PNG">
in VOD
<img width="732" alt="2" src="https://user-images.githubusercontent.com/77669943/134892880-ef11a820-0aa7-49e0-a299-5ced2f163777.PNG">

try to run ffmpeg -i rtsp:xxxx
<img width="517" alt="3" src="https://user-images.githubusercontent.com/77669943/134893140-0fa769d0-b12d-4e36-b08a-6c67251d388b.PNG">

### Logs
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/usr/local/antmedia/lib/spring-core-4.3.28.RELEASE.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Sep 27, 2021 7:39:04 AM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFO: The Apache Tomcat Native library which allows using OpenSSL was not found on the java.library.path: [/usr/local/antmedia/lib/native-linux-x86_64:/usr/local/antmedia/lib/native]
Sep 27, 2021 7:39:04 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio2-0.0.0.0-5080"]
Sep 27, 2021 7:39:04 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Tomcat]
Sep 27, 2021 7:39:04 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet engine: [Apache Tomcat/8.5.69]
Sep 27, 2021 7:39:04 AM org.apache.catalina.loader.WebappLoader buildClassPath
INFO: Unknown loader jdk.internal.loader.ClassLoaders$AppClassLoader@5cb0d902 class jdk.internal.loader.ClassLoaders$AppClassLoader
Sep 27, 2021 7:39:04 AM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFO: No global web.xml found
Sep 27, 2021 7:39:05 AM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Sep 27, 2021 7:39:07 AM org.glassfish.jersey.server.spring.SpringComponentProvider initialize
SEVERE: Spring context lookup failed, skipping spring component provider initialization.
Sep 27, 2021 7:39:08 AM org.apache.catalina.loader.WebappLoader buildClassPath
INFO: Unknown loader jdk.internal.loader.ClassLoaders$AppClassLoader@5cb0d902 class jdk.internal.loader.ClassLoaders$AppClassLoader
Sep 27, 2021 7:39:08 AM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Sep 27, 2021 7:39:09 AM org.glassfish.jersey.server.spring.SpringComponentProvider initialize
SEVERE: Spring context lookup failed, skipping spring component provider initialization.
Sep 27, 2021 7:39:09 AM org.apache.catalina.loader.WebappLoader buildClassPath
INFO: Unknown loader jdk.internal.loader.ClassLoaders$AppClassLoader@5cb0d902 class jdk.internal.loader.ClassLoaders$AppClassLoader
Sep 27, 2021 7:39:09 AM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Sep 27, 2021 7:39:10 AM org.glassfish.jersey.server.spring.SpringComponentProvider initialize
SEVERE: Spring context lookup failed, skipping spring component provider initialization.
Sep 27, 2021 7:39:10 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio2-0.0.0.0-5080"]

**Comment by takai-sama** [comment] 2021-09-28 05:37
**try to downgrade to 2.3. the case still same (broadcasting but can't play stream, only vod work properly). but it makes different logs. like these**

> 2021-09-28 05:20:40,972 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:40,972 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,038 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,039 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,109 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,110 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,179 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,180 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,248 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,250 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,318 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,320 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,388 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,389 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,459 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,460 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,528 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,529 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,599 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,600 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,601 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,668 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,668 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,736 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,809 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,810 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,811 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,877 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,878 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,966 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First video packet is not key frame. It will drop for direct muxing. Stream 581127393143403424250397
2021-09-28 05:20:41,980 [Thread-8] WARN  io.antmedia.muxer.RecordMuxer - First key frame received for stream: 581127393143403424250397
2021-09-28 05:20:51,349 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts7652978 is bigger than incoming dts 7653067
2021-09-28 05:20:51,350 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (7653068) is bigger than pts(7652978)
2021-09-28 05:20:54,929 [http-apr-0.0.0.0-5080-exec-8] INFO  io.antmedia.rest.RestServiceBase - Version Name 2.3.0 Version Type Community Edition
2021-09-28 05:21:01,427 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts8552978 is bigger than incoming dts 8552978
2021-09-28 05:21:01,428 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (8552979) is bigger than pts(8552978)
2021-09-28 05:21:05,879 [http-apr-0.0.0.0-5080-exec-3] INFO  i.a.e.s.WebSocketLocalHandler - Web Socket opened
2021-09-28 05:21:13,288 [http-apr-0.0.0.0-5080-exec-8] INFO  io.antmedia.rest.RestServiceBase - Recording method is called for 581127393143403424250397 to make it false and recordy Type: mp4
2021-09-28 05:21:13,290 [http-apr-0.0.0.0-5080-exec-8] INFO  io.antmedia.muxer.RecordMuxer - Record Muxer writing trailer for stream: 581127393143403424250397
2021-09-28 05:21:13,304 [http-apr-0.0.0.0-5080-exec-8] INFO  io.antmedia.muxer.RecordMuxer - Clearing resources for stream: 581127393143403424250397
2021-09-28 05:21:13,305 [http-apr-0.0.0.0-5080-exec-8] INFO  io.antmedia.muxer.RecordMuxer - Resources are cleaned for stream: 581127393143403424250397
2021-09-28 05:21:13,307 [http-apr-0.0.0.0-5080-exec-8] WARN  io.antmedia.rest.RestServiceBase - WebM recording is started for stream: 581127393143403424250397
2021-09-28 05:21:13,309 [vert.x-worker-thread-1] INFO  io.antmedia.muxer.RecordMuxer - File: /usr/local/antmedia/webapps/LiveApp/streams/581127393143403424250397.mp4.tmp_extension exist: true
2021-09-28 05:21:13,325 [vert.x-worker-thread-1] INFO  io.antmedia.muxer.RecordMuxer - 581127393143403424250397.mp4 is ready
2021-09-28 05:21:13,418 [vert.x-worker-thread-1] WARN  io.antmedia.datastore.db.MapDBStore - VoD is saved to DB 581127393143403424250397.mp4 with voID 586628053723043373394620
2021-09-28 05:21:17,401 [http-apr-0.0.0.0-5080-exec-5] INFO  io.antmedia.rest.RestServiceBase - Version Name 2.3.0 Version Type Community Edition
2021-09-28 05:21:26,498 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts10802980 is bigger than incoming dts 10803069
2021-09-28 05:21:26,501 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (10803070) is bigger than pts(10802980)
2021-09-28 05:21:36,516 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts11702980 is bigger than incoming dts 11702980
2021-09-28 05:21:36,517 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (11702981) is bigger than pts(11702980)
2021-09-28 05:22:01,570 [vert.x-eventloop-thread-0] INFO  i.a.AntMediaApplicationAdapter - update source quality for stream: 581127393143403424250397 quality:null speed:1.0976907630522088
2021-09-28 05:22:11,539 [vert.x-eventloop-thread-1] INFO  i.a.AntMediaApplicationAdapter - update source quality for stream: 581127393143403424250397 quality:null speed:0.9997993780720232
2021-09-28 05:22:13,483 [vert.x-eventloop-thread-0] INFO  i.antmedia.statistic.StatsCollector - System cpu load:23 process cpu load:4 available memory: 319836 KB used memory(RSS): 437044 KB
2021-09-28 05:22:13,484 [vert.x-eventloop-thread-0] INFO  i.antmedia.statistic.StatsCollector - Vertx worker queue size:0 WebRTCVertx worker queue size:0
2021-09-28 05:22:26,694 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts16292963 is bigger than incoming dts 16293052
2021-09-28 05:22:26,695 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (16293053) is bigger than pts(16292963)
2021-09-28 05:23:06,767 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts19892965 is bigger than incoming dts 19893054
2021-09-28 05:23:06,768 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (19893055) is bigger than pts(19892965)
2021-09-28 05:23:41,843 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts23042967 is bigger than incoming dts 23043057
2021-09-28 05:23:41,843 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (23043058) is bigger than pts(23042967)
2021-09-28 05:24:21,977 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts26642969 is bigger than incoming dts 26643059
2021-09-28 05:24:21,977 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (26643060) is bigger than pts(26642969)
2021-09-28 05:24:52,055 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts29342971 is bigger than incoming dts 29343061
2021-09-28 05:24:52,056 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (29343062) is bigger than pts(29342971)
2021-09-28 05:25:12,190 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts31142973 is bigger than incoming dts 31143063
2021-09-28 05:25:12,191 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (31143064) is bigger than pts(31142973)
2021-09-28 05:25:27,260 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts32492976 is bigger than incoming dts 32493065
2021-09-28 05:25:27,261 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (32493066) is bigger than pts(32492976)
2021-09-28 05:25:32,300 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts32942976 is bigger than incoming dts 32942976
2021-09-28 05:25:32,300 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (32942977) is bigger than pts(32942976)
2021-09-28 05:25:52,368 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts34742978 is bigger than incoming dts 34743067
2021-09-28 05:25:52,369 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (34743068) is bigger than pts(34742978)
2021-09-28 05:26:02,408 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts35642978 is bigger than incoming dts 35642978
2021-09-28 05:26:02,409 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (35642979) is bigger than pts(35642978)
2021-09-28 05:26:17,490 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts36992980 is bigger than incoming dts 36993069
2021-09-28 05:26:17,491 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (36993070) is bigger than pts(36992980)
2021-09-28 05:26:27,458 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts37892980 is bigger than incoming dts 37892980
2021-09-28 05:26:27,459 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (37892981) is bigger than pts(37892980)
2021-09-28 05:26:37,563 [vert.x-eventloop-thread-2] INFO  i.a.AntMediaApplicationAdapter - update source quality for stream: 581127393143403424250397 quality:null speed:1.094487398333166
2021-09-28 05:26:47,531 [vert.x-eventloop-thread-3] INFO  i.a.AntMediaApplicationAdapter - update source quality for stream: 581127393143403424250397 quality:null speed:0.9998996789727127
2021-09-28 05:27:02,686 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts41132963 is bigger than incoming dts 41133052
2021-09-28 05:27:02,687 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (41133053) is bigger than pts(41132963)
2021-09-28 05:27:13,482 [vert.x-eventloop-thread-0] INFO  i.antmedia.statistic.StatsCollector - System cpu load:9 process cpu load:2 available memory: 309452 KB used memory(RSS): 432448 KB
2021-09-28 05:27:13,483 [vert.x-eventloop-thread-0] INFO  i.antmedia.statistic.StatsCollector - Vertx worker queue size:0 WebRTCVertx worker queue size:0
2021-09-28 05:27:22,758 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts42932965 is bigger than incoming dts 42933054
2021-09-28 05:27:22,759 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (42933055) is bigger than pts(42932965)
2021-09-28 05:27:42,826 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts44732967 is bigger than incoming dts 44733057
2021-09-28 05:27:42,826 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (44733058) is bigger than pts(44732967)
2021-09-28 05:28:13,914 [pool-4-thread-1] INFO  org.red5.server.tomcat.WarDeployer - Deploy wars with app start
2021-09-28 05:28:32,925 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts49232969 is bigger than incoming dts 49233059
2021-09-28 05:28:32,925 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (49233060) is bigger than pts(49232969)
2021-09-28 05:29:28,017 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts54182971 is bigger than incoming dts 54183061
2021-09-28 05:29:28,018 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (54183062) is bigger than pts(54182971)
2021-09-28 05:30:03,173 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts57332973 is bigger than incoming dts 57333063
2021-09-28 05:30:03,174 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (57333064) is bigger than pts(57332973)
2021-09-28 05:30:33,272 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts60032976 is bigger than incoming dts 60033065
2021-09-28 05:30:33,273 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (60033066) is bigger than pts(60032976)
2021-09-28 05:30:48,291 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts61382976 is bigger than incoming dts 61382976
2021-09-28 05:30:48,292 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (61382977) is bigger than pts(61382976)
2021-09-28 05:31:08,360 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts63182978 is bigger than incoming dts 63183067
2021-09-28 05:31:08,361 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (63183068) is bigger than pts(63182978)
2021-09-28 05:31:23,383 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts64532978 is bigger than incoming dts 64532978
2021-09-28 05:31:23,383 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (64532979) is bigger than pts(64532978)
2021-09-28 05:31:38,470 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts65882980 is bigger than incoming dts 65883069
2021-09-28 05:31:38,471 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (65883070) is bigger than pts(65882980)
2021-09-28 05:31:48,500 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts66782980 is bigger than incoming dts 66782980
2021-09-28 05:31:48,501 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (66782981) is bigger than pts(66782980)
2021-09-28 05:32:03,595 [vert.x-eventloop-thread-0] INFO  i.a.AntMediaApplicationAdapter - update source quality for stream: 581127393143403424250397 quality:null speed:1.0902473075388912
2021-09-28 05:32:13,482 [vert.x-eventloop-thread-0] INFO  i.antmedia.statistic.StatsCollector - System cpu load:9 process cpu load:2 available memory: 298272 KB used memory(RSS): 433224 KB
2021-09-28 05:32:13,483 [vert.x-eventloop-thread-0] INFO  i.antmedia.statistic.StatsCollector - Vertx worker queue size:0 WebRTCVertx worker queue size:0
2021-09-28 05:32:13,496 [vert.x-eventloop-thread-1] INFO  i.a.AntMediaApplicationAdapter - update source quality for stream: 581127393143403424250397 quality:null speed:1.0066659933340067
2021-09-28 05:32:23,658 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts70022963 is bigger than incoming dts 70023052
2021-09-28 05:32:23,658 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (70023053) is bigger than pts(70022963)
2021-09-28 05:33:03,868 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts73622967 is bigger than incoming dts 73623057
2021-09-28 05:33:03,869 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (73623058) is bigger than pts(73622967)
2021-09-28 05:33:23,938 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts75422969 is bigger than incoming dts 75423059
2021-09-28 05:33:23,939 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (75423060) is bigger than pts(75422969)
2021-09-28 05:33:33,980 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts76322970 is bigger than incoming dts 76323059
2021-09-28 05:33:33,980 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (76323060) is bigger than pts(76322970)
2021-09-28 05:33:44,016 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts77222971 is bigger than incoming dts 77222971
2021-09-28 05:33:44,017 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (77222972) is bigger than pts(77222971)
2021-09-28 05:34:14,136 [Thread-8] INFO  i.a.streamsource.StreamFetcher - last dts79922973 is bigger than incoming dts 79922973
2021-09-28 05:34:14,136 [Thread-8] INFO  i.a.streamsource.StreamFetcher - dts (79922974) is bigger than pts(79922973)

**Comment by yashtandon113** [comment] 2021-09-28 18:25
Hi @takai-sama 
As I have checked at my end using RTSP Url at my end in community edition 2.4.0.2 and it is running fine as expected.
During upgrade from 2.0.0 to 2.4.0.2, did you use latest installation script from [here](https://github.com/ant-media/Ant-Media-Server/wiki/Installation#3-download-installation-script)
Also can you please do the fresh installation once at your end if possible using this script?

**Comment by takai-sama** [comment] 2021-09-29 08:27
thanks for reply @yashtandon113 ,i just try with the latest installation script from there, build the image and run the docker. the result is like that, play stream not running well. 
i try other way, i found ant media docker version here https://hub.docker.com/r/nibrev/ant-media-server , i run this command `docker run --name ams -d --net=host nibrev/ant-media-server:ams-v2.4.0.2 `
so i just replace the old one with the new one. the result still same. can record mp4 streams but can't play the stream. it stuck in **"Stream will start playing automatically when it is live"**
[errorlog.txt](https://github.com/ant-media/Ant-Media-Server/files/7250161/errorlog.txt)
[consolelog.txt](https://github.com/ant-media/Ant-Media-Server/files/7250164/consolelog.txt)

**Comment by yashtandon113** [comment] 2021-09-29 17:33
Can you please follow this guide to run ant media in docker https://github.com/ant-media/Ant-Media-Server/wiki/Installation#docker-installation
Also is there any firewall at your end which is blocking the traffic?

**Comment by takai-sama** [comment] 2021-09-30 08:10
Hi @yashtandon113 ,I told you, i have followed the guide, it's still the same.

> thanks for reply @yashtandon113 ,i just try with the latest installation script from there, build the image and run the docker. the result is like that, play stream not running well. i try other way, i found ant media docker version here https://hub.docker.com/r/nibrev/ant-media-server , i run this command `docker run --name ams -d --net=host nibrev/ant-media-server:ams-v2.4.0.2 ` so i just replace the old one with the new one. the result still same. can record mp4 streams but can't play the stream. it stuck in **"Stream will start playing automatically when it is live"** [errorlog.txt](https://github.com/ant-media/Ant-Media-Server/files/7250161/errorlog.txt) [consolelog.txt](https://github.com/ant-media/Ant-Media-Server/files/7250164/consolelog.txt)

i have tried on others linux vm (which one just converted), it doesn't change the result. there is no problem with the firewall because with the previous version (2.0) everything worked fine.

I just tried the enterprise version trial, and it solved my problem. it means the problem only solved by enterprise version?? I don't really understand the backend of community vers and enterprise vers.

**Comment by yashtandon113** [comment] 2021-09-30 08:20
Hi @takai-sama 
There is no difference between community edition and enterprise edition if it comes to pulling the stream source. You can see the comparison regarding features [here](https://github.com/ant-media/Ant-Media-Server/wiki/Introduction#community-edition--enterprise-edition)
Also I have tested with the same docker installation guide on ( linux vm v18.04 ) and v2.4.0.2 at my end and there is no issue in playing the stream.

**Comment by mekya** [comment] 2021-09-30 09:32
Thank you Guys so much for the discussion. I think we're close to resolve.  

I've an idea. 
@takai-sama I think the problem may happen with community edition and your stream source.  Could you please share your stream source and we can try to re-produce the problem?  If we cannot reproduce it, we can schedule a meeting to see the problem.

**Comment by takai-sama** [comment] 2021-09-30 09:51
thanks for response @mekya @yashtandon113 
this is my rtsp source => rtsp://36.90.64.148:11083 . i will stop my broadcast so you can try the rtsp source. hope can solve as soon as possible before the ip public reset.

**Comment by yashtandon113** [comment] 2021-09-30 12:10
@takai-sama 
As we tried to reproduce the issue using your RTSP Url and observed that it's not fully about community or enterprise edition as it's not playing in HLS both in community and enterprise edition. In Enterprise edition the stream plays with WebRTC by default on the dashboard but in community edition, as WebRTC is not supported so it plays HLS their.

Also we checked that the stream source has an audio codec that HLS does not support.
Stream #0:0: Video: h264 (High), yuvj420p(pc, bt470bg/bt470bg/bt709, progressive), 1920x1080, 30 tbr, 90k tbn, 180k tbc
Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s

In this scenario, community/enterprise edition should play the HLS stream without audio but it's not playing. So we're assigning it to one of the developer to understand the cause.

**Comment by takai-sama** [comment] 2021-10-01 04:46
@yashtandon113 
Thanks for the explanation. I'm not very familiar with codecs, so is there a temporary solution for now? can i play stream in community vers (2.4) without HLS ?

**Comment by yashtandon113** [comment] 2021-10-01 08:04
@takai-sama 
If possible, can you please check once by changing the audio codec of your RTSP stream source to AAC?
Please let me know if it works for you.

**Comment by yashtandon113** [comment] 2021-11-15 18:29
Hi @takai-sama 
As this issue has been scheduled at our end, but we do not have any RTSP source with pcm audio codec for troubleshooting.
It will be great if you can increase the limit of your RTSP source rtsp://36.90.64.148:11083 so we can use it for the troubleshooting.
Please let us know.

**Comment by takai-sama** [comment] 2021-11-19 04:05
Hi @yashtandon113 , sorry for late, didn't receive any notif zz. here  rtsp://36.90.8.223:11083 .  
cc : @mekya @Mohit-3196

**Comment by yashtandon113** [comment] 2021-11-19 14:15
@takai-sama, Thanks a lot for sharing the URL. We will update you on this.

**Closed** 2022-01-06 15:25 UTC
