### ISSUE TITLE
Streaming a playlist to twitch does not work correctly

### ISSUE THREAD

**Issue by lastpeony** [ant-media/Ant-Media-Server#5005] opened 2023-04-12 09:45 UTC
Create a playlist through web panel and add multiple videos. Add your twitch rtmp url with your streaming key example:
rtmp://live.twitch.tv/app/live_897029327_cktUtBBMcnONuiQIJ7kXyjTbBhbXGO

Make sure that videos are short for easy reproducing.
Start streaming and check your channel from twitch. 

the stream ends after each video in the playlist, and then restarts when the next video begins.

Furthermore, I have noticed that the stream occasionally goes offline on Twitch, despite the fact that the web panel indicates that the stream is still broadcasting.

expected behaviour:
The playlist should stream continuously without any interruptions or restarts when switching to the next video.

**Comment by lastpeony** [comment] 2023-04-12 20:59
related
https://github.com/ant-media/Ant-Media-Server/issues/4468

**Comment by mekya** [comment] 2023-08-01 09:57
Yes, it's same issue.

**Comment by tmbailey0304** [comment] 2023-11-08 17:16
@mekya Any fix for this available yet? If not, do you know where the problem is so I can try and look into it?

**Comment by mekya** [comment] 2023-11-13 10:48
Hi @tmbailey0304,

Thank you for follow-up.

No update yet. My colleague is working about it. Currently, there is no permanent fix. I hope we have somethings in a couple of weeks. 

FYI

Regards
Oguz

**Comment by tunixgutes** [comment] 2023-12-09 07:22
Hi @mekya, 
got the same issue. The Twitch-stream fully restarts evertime a clip is finished.

**Comment by arlindogarcia** [comment] 2023-12-17 14:59
Oi @mekya, tenho também o mesmo problema, a transmissão simplesmente é reiniciada.

Para que não fique parado juntei todos os vídeos da playlist em um só usando o Vegas 15, assim a live reinicia com maior tempo.

**Comment by ivancduran** [comment] 2024-01-09 21:00
I hope this problem can be solved, the same thing happens with YouTube, when a video on the playlist ends the transmission is cut off.

**Comment by guiiicd** [comment] 2024-02-16 14:57
No solution has been found for this problem?

**Comment by guiiicd** [comment] 2024-02-20 13:51
I'm looking forward to seeing this workaround solution. When there's any update, please let us know.

**Comment by mekya** [comment] 2024-02-22 17:27
Hi @guiiicd,

I've sent a PR that make the workaround solution work for this problem. In my tests, the twitch stream does not turn offline/restart anymore. It's always live. 

Let it pass the CI for community and enterprise. Then I'll check the final one to confirm it and will provide you the workaround.

FYI

**Comment by mekya** [comment] 2024-02-24 08:32
Hi @guiiicd,

Let me give you an update. The solution I've provided as a workaround is working with an unacceptable exception. I mean the stream is not stopping/starting on twitch. On the other hand, there is an audio/video sync issue :( 

Let me check the audio/video sync issue to fix it. I hope I can find sometime at the weekend to take a look and update you. 

FYI 

Have a great weekend. 

Oguz

**Comment by mekya** [comment] 2024-02-27 13:50
Hi @guiiicd,

I could not find a workaround solution for this case. I have somethings to deliver and I can take a look at this issue again later.

FYI

**Comment by guiiicd** [comment] 2024-02-27 14:53
Thanks for the info @mekya 
I hope you can find a solution

**Comment by mekya** [comment] 2024-03-04 10:21
Hi @guiiicd,
I found a solution and I've sent the PR. I'll give the workaround solution instructions after I merge the PR. 

Thank you

Cheers

**Comment by mekya** [comment] 2024-03-07 06:44
Hi @guiiicd,

That's great to hear that. Thank you for testing. ('done is better than perfect' :D)

Btw, why don't you join us in our journey? Just dream that you're part of a project that is like the wordpress of streaming.   Your feedbacks/forwards, testing and telling your experience is ok to get started. 

If you're interested, let me know. We can schedule a meeting to discuss together.

Cheers
Oguz

**Comment by guiiicd** [comment] 2024-03-07 14:20
Hi @mekya 

I found a bug in this new version. After a few hours (more than 12 hours), live is on a black screen and loads endlessly.
If you want, I can send you the log files by email

**Comment by burak-58** [comment] 2024-03-18 10:40
Thank you @guiiicd for the report. Could you please create a separate issue from:
https://github.com/ant-media/Ant-Media-Server/issues/new/choose

Let me close this one.

**Closed by burak-58** 2024-03-18 10:40 UTC
