### ISSUE TITLE
I tried to install Antmedia Server on ArmBased Processor but...

### ISSUE THREAD

**Issue by TeckboyAj** [ant-media/Ant-Media-Server#4241] opened 2022-06-12 13:05 UTC
### Short description
I tried to install Antmedia community version in arm based processor. it is installed but whenever i tried to open in web it is always showing this issue.
This site can’t be reached
<My Ippadress>  took too long to respond.
Try:
Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
[Running Windows Network Diagnostics](javascript:diagnoseErrors())
ERR_CONNECTION_TIMED_OUT

i check in the but in server it is showning that the ant media is active and running.
Loaded: loaded (/etc/systemd/system/antmedia.service; enabled; vendor pres>
     Active: active (running) since Sun 2022-06-12 12:46:03 UTC; 55s ago
   Main PID: 17171 (java)
      Tasks: 70 (limit: 36000)
     Memory: 420.4M
     CGroup: /system.slice/antmedia.service
             └─17171 /bin/java -Dlogback.ContextSelector=org.red5.logging.Loggi>

for installation i have used ubuntu 20.04 in arm based processor.

Any idea what to do now?

![image](https://user-images.githubusercontent.com/31789400/173234628-c355debc-a2cc-4f7b-b260-ef94903a253b.png)

![image](https://user-images.githubusercontent.com/31789400/173234642-c6c88890-3a0e-4ad4-9bd1-b38431b597f4.png)

**Comment by yashtandon113** [comment] 2022-06-13 16:32
Hi @TeckboyAj 
Thanks for creating the issue.
Could you please tell us which Ant media server version you're using? I tried installing the current latest v2.4.3 community edition on an ARM processor, but I couldn't reproduce the problem, and the server was up and running.
Also make sure that [required ports](https://resources.antmedia.io/docs/installation#server-ports) should be enabled on your firewall/security groups.

**Comment by yashtandon113** [comment] 2022-06-25 07:21
@TeckboyAj 
Please let us know if your issue is resolved or not.

**Comment by yashtandon113** [comment] 2022-11-24 06:51
Closing this issue. Please feel free to open if you have any questions.

**Closed by yashtandon113** 2022-11-24 06:51 UTC
