### ISSUE TITLE
Support Publish/Play in Unity SDK

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#4616] opened 2022-11-28 10:42 UTC

**Comment by popisdead** [comment] 2022-12-20 14:19
Hey, this is important - nobody can switch to the new SDK without this feature! Is there any ETA for this?

**Comment by mekya** [comment] 2022-12-26 09:12
Thank you @popisdead . There are some blocker things on our end to proceed. My ETA is about a couple of weeks.

**Comment by mustafaboleken** [comment] 2023-01-02 11:37
Hi @popisdead 

We tested on Android, iOS, Windows and MacOS -> peer-to-peer connection and publish works right now. For the player side there is a sound issue that we are working on it. Because of that I don't have much experience in unity can you also test and give feedback to me.

**Comment by popisdead** [comment] 2023-01-02 12:44
Thanks @mustafaboleken - we are starting the test today and keep you posted

**Comment by popisdead** [comment] 2023-01-05 16:22
Hi, we tested, and as you mentioned there is a sound issue.
 To fix this, the audio source cannot be initialized with: PlayOnAwake
![image](https://user-images.githubusercontent.com/1311622/210829431-558f849f-ba01-476e-8c85-2ebdb3049404.png)

**Comment by mekya** [comment] 2023-01-30 07:47
Thank you @popisdead . I've moved the issue to the "In Progress" to fix it.

**Comment by mekya** [comment] 2023-01-30 07:48
I think this one is also related -> https://github.com/ant-media/Ant-Media-Server/issues/4717

**Comment by burak-58** [comment] 2023-02-13 10:33
When I used Unity IDE to run the sample application and play the stream, I also can't get audio. But if I create an executable file and run it I can get the audio.

**Comment by mustafaboleken** [comment] 2023-02-13 11:08
It could be related to ide.

**Comment by burak-58** [comment] 2023-03-06 13:19
I have searched and foun that there is a Mute Audio toogle button on the Unity Editor. Please disable it to get audio while running application in Unity Editor.



![Image](https://user-images.githubusercontent.com/39169933/223121155-25acacc2-f3e4-4c6a-94ae-94dba292c57a.png)

**Comment by popisdead** [comment] 2023-03-08 16:13
Hi @mustafaboleken @mekya and @burak-58 

P2P works well, publish/play works in the upload direction to the server (we can see our video in the admin backend of antmedia), but we cannot make the receiver of publish/play work.

The event OnVideoReceived is never triggered, **so we don't have the texture.**

webRTClient.setDelegateOnTrack(e =>
            {

                if (e.Track is VideoStreamTrack video)
                {
                    video.OnVideoReceived += tex =>
                    {
                        receiveImage.texture = tex;
                    };
                }

                if (e.Track is AudioStreamTrack audioTrack)
                {
                    receiveAudio.SetTrack(audioTrack);
                    receiveAudio.loop = true;
                    receiveAudio.Play();
                }
            });
        }

Of course, this is tested the https://github.com/ant-media/WebRTC-Unity-SDK  without modification except publishing to our cluster websocket URL. Can you please try to see if you can reproduce this problem?

**Comment by burak-58** [comment] 2023-03-13 11:24
I have created this issue https://github.com/ant-media/Ant-Media-Server/issues/4897. We can continue there. Closing this.

**Closed** 2023-03-20 08:43 UTC
Labels: Priority: Important
