### ISSUE TITLE
Recording should be start/stop on demand from javascript api

### ISSUE THREAD

**Issue by krishnapsarthi** [ant-media/Ant-Media-Server#851] opened 2019-01-25 11:09 UTC
Hi @mekya and @SelimEmre ,

We are trying to implement enable and disable video recording on demand with ant media server.
For that we are using enableMp4Muxing API but its not working for me.
When hit any API including enableMp4Muxing/getToken etc. Its redirecting us to https://antmedia.io/.
ex. curl -X GET "https://antmedia.io/broadcast/enableMp4Muxing?id=video0108315&enableMp4=1" -H "accept: application/json"

we have enterprise edition account for antmedia server with latest version 1.6.1.

**Comment by SelimEmre** [comment] 2019-02-03 21:54
Hi @krishnapsarthi,

Thank you for your interest. Sorry for the delay. EnableMp4Muxing rest service should in below.
http://serverIp:5080/WebRTCAppEE/rest/broadcast/enableMp4Muxing?id=streamId&enableMp4=1
Also you can check our rest service documentation https://antmedia.io/swagger/swagger.html

Please let me know if you encounter any problems.

Best Regards,
Selim

**Comment by krishnapsarthi** [comment] 2019-02-04 11:23
Hello @SelimEmre ,

I have tried the same URL(https://serverIp:5443/WebRTCAppEE/rest/broadcast/enableMp4Muxing?id=streamId&enableMp4=1) to start the recording on demand, but recording not done.

Do we have any specific API of stop on demand recording?

Also can start recording after video streaming already started?

Thanks,
Krishna

**Comment by mekya** [comment] 2019-04-09 06:46
Duplicate of #901

This feature is scheduled for this sprint

**Closed** 2019-11-04 12:35 UTC
Labels: duplicate, investigating

**Comment by navilllous** [comment] 2021-01-18 16:47
was this feature finished?

**Comment by mekya** [comment] 2021-02-16 08:50
Hi @navilllous,

Yeah this feature is available for a long time.
