### ISSUE TITLE
Issue if using OBS with NVENC H.264 encoder

### ISSUE THREAD

**Issue by Philosyang** [ant-media/Ant-Media-Server#4643] opened 2022-12-08 01:17 UTC
# Issue

### Short description
Needs to "refresh" encoder settings after the viewer has joined the WebRTC stream if streaming using OBS with NVENC H.264 encoder in order for the viewer to be able to view the WebRTC stream.

### Environment

* Operating system and version: Ubuntu 20.04.5 LTS
* Java version: openjdk 11.0.17 2022-10-18
* Ant Media Server version: Enterprise Edition 2.5.1 20221030_1635
* Browser name and version: N/A

### Steps to reproduce
1. Use OBS with "NVIDIA NVENC H.264" encoder for streaming settings.
1. "Tune for ultra-low latency streaming" with the parameters mentioned in https://resources.antmedia.io/docs/open-broadcaster-software-publishing. For NVENC, rate control is set to CBR, keyframe interval is set to 1 second, tuning is set to Ultra Low Latency, max B-frames is set to 0.
1. Assuming we have set up a stream named `abcdef` with stream id `abcdef` on Ant Media Server, and input correct server and key in OBS.
1. Streamer starts their stream.
1. Viewer opens the browser and navigate to the `abcdef` stream.
1. Viewer fails to see the stream. The stream is loading forever.
1. Streamer navigates to OBS > Settings > Output > Encoder Settings and change a random item such as +50 Kbps to Bitrate.
1. Viewer fails to see the stream. The stream is loading forever.
1. Streamer clicks the "Apply" button to apply the encoder settings.
1. Viewer is now immediately able to see the stream.

### Expected behavior
1. Streamer starts their stream.
1. Viewer opens the browser and navigate to the `abcdef` stream.
1. Viewer is now immediately able to see the stream.

### Actual behavior
1. Streamer starts their stream.
1. Viewer opens the browser and navigate to the `abcdef` stream.
1. Viewer fails to see the stream. The stream is loading forever.
1. Streamer navigates to OBS > Settings > Output > Encoder Settings and change a random item such as +50 Kbps to Bitrate.
1. Viewer fails to see the stream. The stream is loading forever.
1. Streamer clicks the "Apply" button to apply the encoder settings.
1. Viewer is now immediately able to see the stream.

Note that this issue _only_ happens with NVENC for me. I have tested CPU encoding and Intel's QuickSync encoding, both worked as expected.

Reproduction GIF:
Maybe click on the GIF file for a better view.
![Animation](https://user-images.githubusercontent.com/24841393/206331911-2ed6ef11-08bb-459e-a0a6-a7ec54fb92e5.gif)

 

### Logs
https://gist.github.com/Philosyang/7315e31f565cb0afe30bd18d7700aca9

**Comment by racile** [comment] 2022-12-08 12:03
I have had the same issue for a week now every time I change the encoder to NVENC it keeps loading,
using the same setting without NVENC it works,
I even tried the same settings with NVENC but streamed it to Facebook live or Youtube live and it worked. 
it seems like NVENC doesn't work with any media server, or am I missing something, please advise, thank you.

**Comment by yashtandon113** [comment] 2022-12-09 18:52
Hi @Philosyang @racile 
Thank you for raising the issue and providing such a detailed explanation.

We were also able to reproduce the problem on our end. According to the release logs for OBS v28.1, they made some changes to the NVENC H264 encoder. It is available at https://github.com/obsproject/obs-studio/releases.
We will investigate this matter and provide an update here.

Meanwhile, as a workaround, you can downgrade your OBS version to v28.0.3, which works fine.

**Comment by shhhhhh16** [comment] 2023-02-14 10:37
Hello, this problem still persist - any update on it?

**Comment by mekya** [comment] 2023-02-27 10:17
Unfortunately, there is no update. We could not schedule it due to commitments on our end.

**Comment by TheLion092** [comment] 2023-04-21 23:44
Hello, i also encountered this behavior. Are there new informations about it?

**Comment by shhhhhh16** [comment] 2023-07-25 10:44
Hello, is there any possibility to increase priority on this? We are still forced to use OBS 27.x.x in order to not have this problem.
Any OBS above 27.x has this problem :(

**Comment by shhhhhh16** [comment] 2023-11-09 14:22
In my opinion the issue itself is with the player itself. Recorded videos works properly. Maybe something in between getting the rtmp stream <> web player? 
OBS 30.x beta has the same issue

**Comment by TheLion092** [comment] 2023-11-10 08:26
I just notice that the problem only occurs in the enterprise edition.

Enterprise Edition 2.7.0 20231031_0626  -> Problem exists
Community Edition 2.7.0 20231031_0625  -> Everything is working as intended

@mekya maybe that can help you fix the problem?

**Comment by mekya** [comment] 2023-11-13 10:34
I have not had a chance to test it.  I'm just moving it to the next sprint to check if anyone is available to fix the problem

**Comment by TheLion092** [comment] 2023-11-13 15:21
Thank you @mekya. Can we assist you with informations or something else @lastpeony ?

**Comment by lastpeony** [comment] 2023-11-16 10:34
I reproduced this issue on my end using AMS 2.7.x. 
Additionally, I found another workaround: selecting the h264 encoder and adding one ABR resolves the problem, allowing the stream to function correctly. However, when the ABR is removed, the issue reappears, and the stream fails to work.

**Comment by shhhhhh16** [comment] 2023-12-05 14:55
Sadly ABR is increasing CPU usage by a lot so its not very reliable on a bigger scale. Is there any chance increase priority on this issue?

**Comment by TheLion092** [comment] 2023-12-05 15:05
Yes, i have the same opinion and thoughts too. As a workaround, for multiple streams, adding ABR is not feasible due to the high CPU load.

**Comment by TheLion092** [comment] 2024-01-10 09:30
It has now been a year since this issue was first reported, and there is still no fix for it. This is particularly frustrating given the importance of this function. Using OBS with AntMediaServer has become nearly impossible, or at least requires workarounds that come with their own set of drawbacks.

What makes this situation even more sad is that the issue doesn't pertain to the free "Community Edition" but rather to the paid and far from inexpensive "Enterprise Edition."

I have given up on waiting for a fix from the developers. Perhaps the issue is not important enough; who knows?

In the meantime i have discovered another product that allows me to initiate a WebRTC stream with OBS without any problems, and it happens to be open source and free!

I recommend everyone who uses OBS to give the [MediaMTX](https://github.com/bluenviron/mediamtx) Project a try.

**Comment by shhhhhh16** [comment] 2024-01-25 12:20
@mekya are there any news about this issue?

**Comment by mekya** [comment] 2024-02-12 07:13
Hi @shhhhhh16,
You're right.  Unfortunately, it seems that I need to fix this issue because it cannot be delegated and I could not have availability to prioritise and fix it.

Btw, We try to find a balance in giving priority of the issues according to enterprise users, community users, support packages, our commitments etc.  If you are an enterprise user and want us to give increase priority, please reach out to contact@antmedia.io and let us know.

Thank you for your patience. 

Regards
Oguz

**Comment by muratugureminoglu** [comment] 2024-10-28 13:20
<div>Agent Mohit Dubey linked Freshdesk ticket <a href="https://antmedia.freshdesk.com/a/tickets/134482">134482</a> for this issue.</div><br/>

**Closed** 2024-11-18 10:34 UTC
Labels: Confirmed
