### ISSUE TITLE
this.dbType is null after some time running

### ISSUE THREAD

**Issue by SebastienGautier** [ant-media/Ant-Media-Server#6569] opened 2024-08-09 08:19 UTC
### Short description
After some time working properly something happens and streaming and login become impossible. We're using kubernetes, restart the deployement is enough to get it working again but after it happening twice I decided to rollback to our previous 2.7.0 version

### Environment

* Operating system and version: Docker ubuntu:22.04
* Java version: default provided
* Ant Media Server version: 2.10.0 Enterprise
* Browser name and version: Chrome 127.0

### Steps to reproduce
1. Use AMS 2.10
2. Wait some time
3. Unable to login with a 500 error saying `this.dbType is null`

### Expected behavior
Should be able to stream and login

### Actual behavior
Unable to stream and login

### Logs
https://pastebin.com/i4LDdnnS

**Comment by mekya** [comment] 2024-08-12 10:42
Hi @SebastienGautier ,
Thank you for creating the issue.

I've tagged it as investigating because we've not encountered such a problem. 
One of us will try to reproduce the problem.  
Please let us know if you have some more information that may help us understand/reproduce the problem.  

Cheers

**Comment by SebastienGautier** [comment] 2024-08-14 13:18
I'm afraid I can't say much more, everything works fine on 2.7, after updating to 2.10.0 it was running fine for some time (about 12 hours) and after that I was unable to login through the UI with the log I sent and unable to stream using RTMP.
I restarted the deployment (kubernetes) and it was fine again for about the same period (between 10 and 15 hours) and I got the same error. After that I decided to rollback to the previous version

**Comment by muratugureminoglu** [comment] 2024-08-14 13:27
Hi @SebastienGautier 

If you send an e-mail to support[@]antmedia[.]io by mentioning me, I will be happy to help you.

**Comment by muratugureminoglu** [comment] 2024-10-06 16:54
This problem occurs in a cluster (MongoDB) structure when HLS threads become busy over time and then become responseless. The issue [here](https://github.com/ant-media/Ant-Media-Server/issues/6660) is also resolved and verified.

**Comment by SebastienGautier** [comment] 2024-10-07 06:43
We're encountering this issue a lot and are running AMS 2.11.3, will the fix be released soon ?

**Comment by muratugureminoglu** [comment] 2024-10-07 06:58
Hi @SebastienGautier 

I guess you didn't receive my message 6 days ago via email. In version 2.11.3 we have not encountered such an error. Can you please share how we can reproduce it?  If you share the credentials of the cluster you are having trouble with via the ticket system, we will check again.

**Comment by ocatta** [comment] 2024-10-07 08:02
Hi Murat, start of our migrating the customers last week, so we did not have much time.
Is [6660](https://github.com/ant-media/Ant-Media-Server/issues/6660) a fix for this issue too ?
I see it "done", is it available on latest version ?

**Comment by muratugureminoglu** [comment] 2024-11-11 06:07
Hi @ocatta 

If you confirm that the error "this.dbType is null" has been fixed, I close this issue.

**Comment by SebastienGautier** [comment] 2024-11-12 06:20
The issue has not been solved, the automated restarts when it happens are in place and keep restarting the pods on a regular basis

**Comment by burak-58** [comment] 2024-12-16 10:49
Hi @SebastienGautier,
As @ocatta mentioned in email thread, you don't encounter the issue anymore. So I am closing this issue now.

**Closed by burak-58** 2024-12-16 10:49 UTC
Labels: investigating
