### ISSUE TITLE
Firefox 118 on Windows and Ubuntu does not play streams with ABR

### ISSUE THREAD

**Issue by timantmedia** [ant-media/Ant-Media-Server#5659] opened 2023-10-06 15:31 UTC
### Short description
When playing back a live stream that has configured adaptive bitrates, the stream is playing back as expected when using the Firefox browser on Ubuntu or Windows. 

The playback is extremely lagging, meaning the video picture is slow and extremely bad quality. 

This is only affecting the latest version of Firefox, not earlier versions. 

Without ABR configured, the live stream is fine. 

### Environment

* Operating system and version: Ubuntu and Windows 11
* Java version: 
* Ant Media Server version: 2.6.3, 2.6.4
* Browser name and version: Firefox 118

### Steps to reproduce
1. Start a live stream that has ABR configured
2. Playback using Firefox 118 on Ubuntu or Windows 11
3. Observe the laggy, bad playback

### Expected behavior
Always have good quality pictures even with ABR on all major browsers

### Actual behavior
Bad quality playback using the latest version of Firefox, 

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by kputyra** [comment] 2023-10-06 22:17
First reported in #5635

**Comment by timantmedia** [comment] 2023-10-09 08:59
Reproduced this on Ubuntu and Firefox 118. When using ABR in the live stream, Firefox 118 does not play the stream well, the stream is laggy and not playing smoothly. If no ABR is used, it's fine and as expected. 

@yashtandon113 @Mohit-3196 do you have a windows 11 laptop to test Firefox 118 on Windows 11?

**Comment by lastpeony** [comment] 2023-10-10 11:11
I also reproduced this on firefox 118 windows 10.
I tried to update video.js to latest version but it didnt solve the problem.
I will continue to investigate and share my findings.

**Comment by kputyra** [comment] 2023-10-10 11:23
@lastpeony 

I've mentioned this to @timantmedia  in our private communication already - the issue is not directly related to JavaScript framework used to play the stream. We have observed this issue first with our own JavaScript player that is built using **only the standard classes** from WebRTC API.

My impression is that the decoder used by FireFox 118 is not compatible with the encoding used by AntMedia (again: the issue happens only for stream with ABR). Just a quick though: maybe it is related to using openh264 instead of libx264?

**Comment by lastpeony** [comment] 2023-10-10 11:48
@kputyra 
You are correct. I disabled H.264 via the web panel and exclusively used VP8, resulting in a smooth stream experience on Firefox 118. Could you kindly perform a similar test on your end? I will continue our investigation to understand why H.264 appears to be causing issues specifically with Firefox 118.

**Comment by timantmedia** [comment] 2023-10-10 11:50
see also the original issue here https://github.com/ant-media/Ant-Media-Server/issues/5635 for more details from the customer.

**Comment by lastpeony** [comment] 2023-10-10 13:26
openH264 plugin version is same on both firefox 117 and 118(2.3.2) but problem occurs only on firefox 118

**Comment by kputyra** [comment] 2023-10-12 09:31
@lastpeony
Yes, the stream is fine when only VP8 is used as WebRTC codec.

BTW: when I turned on both H264 and VP8, then the server crashes the moment I start streaming to it via RTMP. I've let the admin panel to sent details about it and received already an automatic confirmation of it.

**Comment by lastpeony** [comment] 2023-10-19 19:28
@kputyra, I want to express my gratitude for your diligent investigation into this matter.
 I've conducted tests myself and can verify that the bug has been resolved with the most recent Firefox update.
Feel free to open if seen again.

**Closed by lastpeony** 2023-10-19 19:28 UTC
Labels: bug, investigating
