### ISSUE TITLE
Conference Call with Screen Share Option

### ISSUE THREAD

**Issue by naveedaziz** [ant-media/Ant-Media-Server#2337] opened 2020-07-18 12:39 UTC
Hi, i want screen share option with conference call. I have tried a lot but not able to succeed. It shows me as publisher screen share with camera, but other attendees video got stuck.
 

Should have in basic documentation as its basic feature.

**Comment by muratugureminoglu** [comment] 2020-07-21 17:38
Hi, Thank you for your good point! Technically it's possible. But this is not supported directly at the moment. You need some custom development. I take note of this issue. We will consider your request.

**Comment by naveedaziz** [comment] 2020-07-23 01:58
Thanks for the reply, Its i think very basic in conference call. Anyhow can you tell me when it will be available

**Comment by muratugureminoglu** [comment] 2020-07-27 18:00
Yes, of course, we can update you when it's available!

**Comment by mekya** [comment] 2020-08-04 13:35
Let me give some basic instructions for that. 

The related JS methods are

- `switchVideoCameraCapture(streamId)` : Switches to video camera capture
- `switchDesktopCapture(streamId)`: Switches to desktop only capture
- `switchDesktopCaptureWithCamera(streamId)`: Switches to desktop capture with camera on the right top. 

The critical thing is about the parameter `streamId`. If you're not publishing, it's not important. If you're publishing, you should use the correct `streamId` value. If you don't specify explicitly, server returns you a streamId value in [`joinedTheRoom` callback.](https://github.com/ant-media/StreamApp/blob/b4b7a4a93caf84424590bb4b2fbfcc755debca64/src/main/webapp/conference.html#L388)
You should use the value of obj.streamId in using methods above to switch between camera and screen sharing    

You can even use it through developer console as shown in the image below. 
<img width="1490" alt="Screen Shot 2020-08-04 at 16 28 57" src="https://user-images.githubusercontent.com/3456251/89299682-af5c5800-d66f-11ea-932d-f15109a7725d.png">

**Comment by mekya** [comment] 2020-09-21 11:03
Duplicate of #2462. It's implemented and merged into the master branch for now.

**Closed** 2020-09-22 09:57 UTC
