### ISSUE TITLE
antmedia dont work on iphone

### ISSUE THREAD

**Issue by sonikultra1234** [ant-media/Ant-Media-Server#2924] opened 2021-02-03 11:09 UTC
i was streaming on antmedia live app but i cant see any streaming on ihpne (iOS) and i can see on android...how i can fix this?

**Comment by mhuisken** [comment] 2021-02-09 08:41
I had sort of the same issue when I moved to release 2.2.1: live streaming over https on iPhone didn't work anymore. I moved back to version 2.1.0 and then it worked on iPhone again (but not on those devices that I used testing 2.2.1 release; I had to clear the cache first). The problem also occurred when I tried previewing a VoD from the web panel (didn't start a stream until I cleared the browser cache). Using a different player (VideoJS) solved all problems (as I could not ask  my customers to clear their cache and I have to use https to embed the player). So I assume the problem is related to embedded video player / play.html (and ssl stuff) that is packed with release 2.2.1. Hope this will be fixed asap.

**Comment by mekya** [comment] 2021-02-16 07:38
Hi @sonikultra1234 ,

I think it's about SSL. We already provide a solution for SSL problem in 2.2.1

Please test it with 2.3 RC and let us know if it works for you.

**Comment by EmilianoOzi** [comment] 2021-03-06 15:48
I have the some problem. Ant Media server Version 2.3. On Iphone not working when is ssl enable

**Comment by mekya** [comment] 2021-03-08 06:39
Hi @EmilianoOzi ,

I've tested both on Safari and iOS SDK.  Here is my test scenario.

Safari
1. Install 2.3.0
2. Install SSL with Let's Encrtypt
3. Publish via WebRTCAppEE/index.html through https on Safari
4. Play the stream 

Result it's working and playing.

I've also install sample app and set the endpoint with wss and try publishing. It's also working. 

Could you please let me know your scenario?

**Comment by slavakhol** [comment] 2021-06-06 10:55
> Hi @EmilianoOzi ,
> 
> I've tested both on Safari and iOS SDK. Here is my test scenario.
> 
> Safari
> 
> 1. Install 2.3.0
> 2. Install SSL with Let's Encrtypt
> 3. Publish via WebRTCAppEE/index.html through https on Safari
> 4. Play the stream
> 
> Result it's working and playing.
> 
> I've also install sample app and set the endpoint with wss and try publishing. It's also working.
> 
> Could you please let me know your scenario?

I had exactly the same scenario but it still doesn't work on IOS.

**Comment by mekya** [comment] 2021-06-07 17:04
Hi @slavakhol ,

Shall we schedule a call to check your case?

**Comment by EmilianoOzi** [comment] 2021-06-07 17:52
Hi, is working good now. I did reinstall and after that iss ok.
Regards


pon., 7 cze 2021, 19:04 użytkownik Ahmet Oğuz Mermerkaya <
***@***.***> napisał:

**Comment by slavakhol** [comment] 2021-06-08 05:45
Yes, please


Best regards,
Slava
7 июн. 2021 г., 19:04 +0200, Ahmet Oğuz Mermerkaya ***@***.***>, написал (-а):

**Comment by mekya** [comment] 2021-06-08 07:36
Shall we make it at 2:00 PM GMT+3  on June 9 or at 11:00 AM GMT+3 on June 10?  If not, could you please suggest new dates? 

Btw, may I invite any other guy in the google group to join the meeting? I mean we can let friends in the community join and we can have some discussion with these guys. 

https://groups.google.com/g/ant-media-server

**Comment by slavakhol** [comment] 2021-06-08 07:40
Hello,

Yes, 2:00 PM GMT+3 on June 9 is fine. Will you send  a  link for a call?

Yes, you can invite others.

Best regards,
Slava

От: Ahmet Oğuz Mermerkaya ***@***.***>
Дата: вторник, 8 июня 2021 г. в 09:37
Кому: ant-media/Ant-Media-Server ***@***.***>
Копия: slavakhol ***@***.***>, Mention ***@***.***>
Тема: Re: [ant-media/Ant-Media-Server] antmedia dont work on iphone (#2924)

Shall we make it at 2:00 PM GMT+3 on June 9 or at 11:00 AM GMT+3 on June 10? If not, could you please suggest new dates?

Btw, may I invite any other guy in the google group to join the meeting? I mean we can let friends in the community join and we can have some discussion with these guys.

https://groups.google.com/g/ant-media-server

**Comment by mekya** [comment] 2021-06-08 07:46
Ok. I've created the event. 

You can add it to your calendar. 
https://calendar.google.com/event?action=TEMPLATE&tmeid=MDB2MGJnZmMyN3FybzI3ZGMwbnJnOTNrdmUgbWVreWFAYW50bWVkaWEuaW8&tmsrc=mekya%40antmedia.io

This is the direct link to join
meet.google.com/mfh-ccau-xvb

**Comment by slavakhol** [comment] 2021-06-08 07:50
Ok, got it. BTW calendar link doesn’t work.

Best regards,
Slava

От: Ahmet Oğuz Mermerkaya ***@***.***>
Дата: вторник, 8 июня 2021 г. в 09:46
Кому: ant-media/Ant-Media-Server ***@***.***>
Копия: slavakhol ***@***.***>, Mention ***@***.***>
Тема: Re: [ant-media/Ant-Media-Server] antmedia dont work on iphone (#2924)

Ok. I've created the event.

You can add it to your calendar.
https://calendar.google.com/event?action=TEMPLATE&tmeid=MDB2MGJnZmMyN3FybzI3ZGMwbnJnOTNrdmUgbWVreWFAYW50bWVkaWEuaW8&tmsrc=mekya%40antmedia.io

This is the direct link to join
meet.google.com/mfh-ccau-xvb

**Comment by mekya** [comment] 2021-06-09 16:06
Hi Slava,

Let me give update. 

In the call, we figure out that stream is playing in the embedded player however there is a compatibility problem in the custom code. 

I get the custom code and I try to debug. However, my safari web inspector has a problem and I cannot connect to iOS safari. I'm working on that in order to debug the code. I'll keep you posted.

**Comment by slavakhol** [comment] 2021-06-09 17:07
Thank you! I believe that the problem is exactly as you decribed.

Best regards,
Slava

От: Ahmet Oğuz Mermerkaya ***@***.***>
Дата: среда, 9 июня 2021 г. в 18:06
Кому: ant-media/Ant-Media-Server ***@***.***>
Копия: slavakhol ***@***.***>, Mention ***@***.***>
Тема: Re: [ant-media/Ant-Media-Server] antmedia dont work on iphone (#2924)

Hi Slava,

Let me give update.

In the call, we figure out that stream is playing in the embedded player however there is a compatibility problem in the custom code.

I get the custom code and I try to debug. However, my safari web inspector has a problem and I cannot connect to iOS safari. I'm working on that in order to debug the code. I'll keep you posted.

**Comment by mekya** [comment] 2021-06-09 20:12
Hi Slava,

I've find the problem.  Your custom code cover all width and height of the screen and the play button is actually is not clickable. That's why it does not start playing. Quick solution is commenting out the `autoPlay`line  below.
Or make the play button clickable

```
	function playWebRTCVideo() {
		document.getElementById("remoteVideo").style.display = "block";
		if(mute){
			document.getElementById("remoteVideo").muted=true;
		}
		else{
			document.getElementById("remoteVideo").muted=false;
		}
	//	if(autoPlay) comment out this line
		{
			document.getElementById("remoteVideo").play().then(function(value){
				//autoplay started
				document.getElementById("play_button").style.display="none";
			}).catch(function(error) {
				document.getElementById("play_button").style.display="block";
				console.log("User interaction needed to start playing");
			});
		}
	}
```
 
It's working for me now. Could you please check it on your end?

**Comment by slavakhol** [comment] 2021-06-10 08:49
You guys doing absolutely amazing job! Thank you! Solved.

Best regards,
Slava

От: Ahmet Oğuz Mermerkaya ***@***.***>
Дата: среда, 9 июня 2021 г. в 22:12
Кому: ant-media/Ant-Media-Server ***@***.***>
Копия: slavakhol ***@***.***>, Mention ***@***.***>
Тема: Re: [ant-media/Ant-Media-Server] antmedia dont work on iphone (#2924)

Hi Slava,

I've find the problem. Your custom code cover all width and height of the screen and the play button is actually is not clickable. That's why it does not start playing. Quick solution is commenting out the autoPlayline below.
Or make the play button clickable

        function playWebRTCVideo() {

               document.getElementById("remoteVideo").style.display = "block";

               if(mute){

                       document.getElementById("remoteVideo").muted=true;

               }

               else{

                       document.getElementById("remoteVideo").muted=false;

               }

        //      if(autoPlay) comment out this line

               {

                       document.getElementById("remoteVideo").play().then(function(value){

                               //autoplay started

                               document.getElementById("play_button").style.display="none";

                       }).catch(function(error) {

                               document.getElementById("play_button").style.display="block";

                               console.log("User interaction needed to start playing");

                       });

               }

        }

It's working for me now. Could you please check it on your end?

**Comment by mekya** [comment] 2021-06-10 08:58
Hi Slava,

It's good to know it's working for you. 

May I ask a favor at this time? 
Is it possible just drop a simple good comment and 5 stars  in [AWS Marketplace](https://aws.amazon.com/marketplace/reviews/write-review/B07569Y9SJ) or [G2](https://www.g2.com/products/ant-media-server-ant-media-server/reviews) ?

**Comment by slavakhol** [comment] 2021-06-10 09:09
Done!

May I ask you one more question? We want to implement one time token approach. I have successfully generated token and use it.  I just wonder how those tokens behave?  If I have 5 viewers, should I generate 5 tokens for them, right? If they refresh the page will be the stream still available? If the same viewer want to change  a device during the stream (for example from mobilde to desktop will be the stream still available with the same token?


Best regards,
Slava

От: Ahmet Oğuz Mermerkaya ***@***.***>
Дата: четверг, 10 июня 2021 г. в 10:58
Кому: ant-media/Ant-Media-Server ***@***.***>
Копия: slavakhol ***@***.***>, Mention ***@***.***>
Тема: Re: [ant-media/Ant-Media-Server] antmedia dont work on iphone (#2924)

Hi Slava,

It's good to know it's working for you.

May I ask a favor at this time?
Is it possible just drop a simple good comment and 5 stars in AWS Marketplace<https://aws.amazon.com/marketplace/reviews/write-review/B07569Y9SJ> or G2<https://www.g2.com/products/ant-media-server-ant-media-server/reviews> ?

**Comment by mekya** [comment] 2021-06-10 11:05
Hi Slava,

Thank you so much. 

Let me answer your questions. 

> If I have 5 viewers, should I generate 5 tokens for them, right?

Yes

> If they refresh the page will be the stream still available?

In short, no

If they use the token and they refresh the page, they need to get another token to send the stream. 
If they refresh the page without using the token, they can use the same token. 
In both ways, when page is refreshed, it's disconnected from the server and re-connects again.  

>If the same viewer want to change  a device during the stream (for example from mobilde to desktop will be the stream still available with the same token?

One-time token can be used for only one-time, even if it's used by the same user.

You can alternatively use JWT token, they are valid until they're expired. 
https://github.com/ant-media/Ant-Media-Server/wiki/Stream-Security-Documentation#6-jwt-stream-security-filter

**Comment by mekya** [comment] 2021-06-14 08:46
Hi Guys,

I'm closing this issue. Please feel free to open if you have some issues with that. 

Regards,
A. Oguz

**Closed by mekya** 2021-06-14 08:46 UTC

**Comment by samotage** [comment] 2021-07-22 00:34
Hi,

Having the same issue, the iframe based player does not present the play button for ios and remains with "Stream will start playing automatically when it is live".

This is in both:
2.3.2
2.3.3.1

The player works fine on OSX in Safari and Chrome.

I have tried modifying the play.html file as indicated above, commenting this condition out may not be correct, and indeed breaks the working player in the desktop browser.
