### ISSUE TITLE
The modified m3u8 file is not correct when using the HLS modifier

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#6308] opened 2024-04-30 14:39 UTC
### Short description
The m3u8 file is not correct when using the HLS modifier. The modified m3u8 files contain all the files.

### Environment

* Ant Media Server version: v2.9.0 and above

### Steps to reproduce
1. Follow the instructions for HLS playback with defined interval [here](https://antmedia.io/docs/guides/playing-live-stream/hls-playing/#hls-play-for-a-given-time-interval)
2. Publish the stream. For example, RTMP or RTSP stream
3. Try to play the HLS with the custom time interval as defined in a document

### Expected behavior
The modified m3u8 should play fine.

### Actual behavior
The modified m3u8 plays but it contains all the files after the Endlist tag. As a result, the player buffers for further files.

Check below:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:2.05,
test000000000.ts
#EXTINF:2.234,
test000000001.ts
#EXTINF:1.734,
test000000002.ts
#EXTINF:2.1,
test000000003.ts
#EXTINF:2.117,
test000000004.ts
#EXTINF:2.517,
test000000005.ts
#EXTINF:2.084,
test000000006.ts
#EXTINF:2.217,
test000000007.ts
#EXTINF:1.2,
test000000008.ts
#EXTINF:2.801,
test000000009.ts
#EXTINF:2.851,
test000000010.ts
#EXTINF:0.35,
test000000011.ts
#EXTINF:2.2,
test000000012.ts
#EXTINF:1.984,
test000000013.ts
#EXTINF:2.034,
test000000014.ts
#EXTINF:3.484,
test000000015.ts
#EXTINF:0.333,
test000000016.ts
#EXTINF:3.117,
test000000017.ts
#EXT-X-ENDLIST
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:EVENT
#EXTINF:2.050000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:15:28.294+0000
test000000000.ts
#EXTINF:2.234000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:15:30.344+0000
test000000001.ts
#EXTINF:1.734000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:15:32.578+0000
test000000002.ts
#EXTINF:2.100000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:15:34.312+0000
test000000003.ts
#EXTINF:2.117000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:15:36.412+0000
test000000004.ts
#EXTINF:2.517000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:15:38.529+0000
test000000005.ts
#EXTINF:2.084000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:15:41.046+0000
test000000006.ts
#EXTINF:2.217000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:15:43.130+0000
test000000007.ts
#EXTINF:1.200000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:15:45.347+0000
test000000008.ts
#EXTINF:2.801000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:15:46.547+0000
test000000009.ts
#EXTINF:2.851000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:15:49.348+0000
test000000010.ts
#EXTINF:0.350000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:15:52.199+0000
test000000011.ts
#EXTINF:2.200000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:15:52.549+0000
test000000012.ts
#EXTINF:1.984000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:15:54.749+0000
test000000013.ts
#EXTINF:2.034000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:15:56.733+0000
test000000014.ts
#EXTINF:3.484000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:15:58.767+0000
test000000015.ts
#EXTINF:0.333000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:02.251+0000
test000000016.ts
#EXTINF:3.117000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:02.584+0000
test000000017.ts
#EXTINF:1.984000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:05.701+0000
test000000018.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:07.685+0000
test000000019.ts
#EXTINF:2.000000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:09.702+0000
test000000020.ts
#EXTINF:2.034000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:11.702+0000
test000000021.ts
#EXTINF:1.984000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:13.736+0000
test000000022.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:15.720+0000
test000000023.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:17.737+0000
test000000024.ts
#EXTINF:2.000000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:19.754+0000
test000000025.ts
#EXTINF:2.018000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:21.754+0000
test000000026.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:23.772+0000
test000000027.ts
#EXTINF:2.050000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:25.789+0000
test000000028.ts
#EXTINF:2.000000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:27.839+0000
test000000029.ts
#EXTINF:2.018000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:29.839+0000
test000000030.ts
#EXTINF:2.000000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:31.857+0000
test000000031.ts
#EXTINF:2.034000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:33.857+0000
test000000032.ts
#EXTINF:1.983000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:35.891+0000
test000000033.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:37.874+0000
test000000034.ts
#EXTINF:1.984000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:39.891+0000
test000000035.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:41.875+0000
test000000036.ts
#EXTINF:2.051000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:43.892+0000
test000000037.ts
#EXTINF:2.000000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:45.943+0000
test000000038.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:47.943+0000
test000000039.ts
#EXTINF:2.034000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:49.960+0000
test000000040.ts
#EXTINF:2.034000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:51.994+0000
test000000041.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:54.028+0000
test000000042.ts
#EXTINF:2.000000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:56.045+0000
test000000043.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:16:58.045+0000
test000000044.ts
#EXTINF:2.001000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:00.062+0000
test000000045.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:02.063+0000
test000000046.ts
#EXTINF:2.000000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:04.080+0000
test000000047.ts
#EXTINF:2.034000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:06.080+0000
test000000048.ts
#EXTINF:2.034000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:08.114+0000
test000000049.ts
#EXTINF:1.983000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:10.148+0000
test000000050.ts
#EXTINF:2.034000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:12.131+0000
test000000051.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:14.165+0000
test000000052.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:16.182+0000
test000000053.ts
#EXTINF:2.051000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:18.199+0000
test000000054.ts
#EXTINF:2.000000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:20.250+0000
test000000055.ts
#EXTINF:1.984000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:22.250+0000
test000000056.ts
#EXTINF:2.050000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:24.234+0000
test000000057.ts
#EXTINF:1.984000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:26.284+0000
test000000058.ts
#EXTINF:2.050000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:28.268+0000
test000000059.ts
#EXTINF:1.967000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:30.318+0000
test000000060.ts
#EXTINF:2.051000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:32.285+0000
test000000061.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:34.336+0000
test000000062.ts
#EXTINF:2.000000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:36.353+0000
test000000063.ts
#EXTINF:2.034000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:38.353+0000
test000000064.ts
#EXTINF:2.050000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:40.387+0000
test000000065.ts
#EXTINF:2.001000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:42.437+0000
test000000066.ts
#EXTINF:1.983000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:44.438+0000
test000000067.ts
#EXTINF:2.034000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:46.421+0000
test000000068.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:48.455+0000
test000000069.ts
#EXTINF:2.001000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:50.472+0000
test000000070.ts
#EXTINF:2.033000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:52.473+0000
test000000071.ts
#EXTINF:2.034000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:54.506+0000
test000000072.ts
#EXTINF:2.034000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:56.540+0000
test000000073.ts
#EXTINF:2.034000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:17:58.574+0000
test000000074.ts
#EXTINF:2.000000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:00.608+0000
test000000075.ts
#EXTINF:2.034000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:02.608+0000
test000000076.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:04.642+0000
test000000077.ts
#EXTINF:2.034000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:06.659+0000
test000000078.ts
#EXTINF:2.000000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:08.693+0000
test000000079.ts
#EXTINF:2.034000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:10.693+0000
test000000080.ts
#EXTINF:2.050000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:12.727+0000
test000000081.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:14.777+0000
test000000082.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:16.794+0000
test000000083.ts
#EXTINF:1.984000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:18.811+0000
test000000084.ts
#EXTINF:2.034000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:20.795+0000
test000000085.ts
#EXTINF:2.000000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:22.829+0000
test000000086.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:24.829+0000
test000000087.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:26.846+0000
test000000088.ts
#EXTINF:2.001000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:28.863+0000
test000000089.ts
#EXTINF:2.033000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:30.864+0000
test000000090.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:32.897+0000
test000000091.ts
#EXTINF:2.018000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:34.914+0000
test000000092.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:36.932+0000
test000000093.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:38.949+0000
test000000094.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:40.966+0000
test000000095.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:42.983+0000
test000000096.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:45.000+0000
test000000097.ts
#EXTINF:2.034000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:47.017+0000
test000000098.ts
#EXTINF:1.967000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:49.051+0000
test000000099.ts
#EXTINF:2.033000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:51.018+0000
test000000100.ts
#EXTINF:2.001000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:53.051+0000
test000000101.ts
#EXTINF:2.034000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:55.052+0000
test000000102.ts
#EXTINF:2.050000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:57.086+0000
test000000103.ts
#EXTINF:2.000000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:18:59.136+0000
test000000104.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:19:01.136+0000
test000000105.ts
#EXTINF:2.034000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:19:03.153+0000
test000000106.ts
#EXTINF:2.017000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:19:05.187+0000
test000000107.ts
#EXTINF:1.084000,
#EXT-X-PROGRAM-DATE-TIME:2024-04-29T19:19:07.204+0000
test000000108.ts
#EXT-X-ENDLIST

```

**Comment by bazookanu** [comment] 2024-07-22 10:19
is this an open bug? what release will it be fixed in?

**Comment by bazookanu** [comment] 2024-07-23 04:42
@burak-58 @yashtandon113 @mekya

**Comment by burak-58** [comment] 2024-07-23 10:21
Hi @bazookanu,
We couldn't reproduce that issue. Do you have a reproduce scenario for us to try?

**Comment by bazookanu** [comment] 2024-07-30 10:25
Hi @burak-58 - we can share access to our server. Otherwise, what information do you need to reproduce?
 - server version: 2.10.0 20240705_1151
 - input stream is RTSP (CCTV cam)

App settings:
```
{
  "remoteAllowedCIDR": "127.0.0.1,0.0.0.0/0",
  "mp4MuxingEnabled": false,
  "webMMuxingEnabled": false,
  "addDateTimeToMp4FileName": false,
  "fileNameFormat": "%r%b",
  "hlsMuxingEnabled": true,
  "encoderSettingsString": "[{\"videoBitrate\":2000000,\"forceEncode\":true,\"audioBitrate\":128000,\"height\":720}]",
  "signalingEnabled": false,
  "signalingAddress": "",
  "hlsListSize": "5",
  "hlsTime": "10",
  "uploadExtensionsToS3": 7,
  "s3StorageClass": "STANDARD",
  "endpointHealthCheckPeriodMs": 2000,
  "endpointRepublishLimit": 3,
  "dashSegDuration": "6",
  "dashFragmentDuration": "0.5",
  "targetLatency": "3.5",
  "dashWindowSize": "5",
  "dashExtraWindowSize": "5",
  "lLDashEnabled": true,
  "lLHLSEnabled": false,
  "hlsEnabledViaDash": false,
  "useTimelineDashMuxing": false,
  "webRTCEnabled": true,
  "useOriginalWebRTCEnabled": false,
  "deleteHLSFilesOnEnded": false,
  "deleteDASHFilesOnEnded": false,
  "tokenHashSecret": "",
  "hashControlPublishEnabled": false,
  "hashControlPlayEnabled": false,
  "listenerHookURL": "",
  "acceptOnlyStreamsInDataStore": false,
  "acceptOnlyRoomsInDataStore": false,
  "publishTokenControlEnabled": false,
  "playTokenControlEnabled": false,
  "timeTokenSubscriberOnly": false,
  "enableTimeTokenForPlay": false,
  "timeTokenSecretForPlay": "",
  "enableTimeTokenForPublish": false,
  "timeTokenSecretForPublish": "",
  "timeTokenPeriod": 60,
  "hlsPlayListType": "event",
  "hlsSegmentType": "mpegts",
  "vodFolder": "",
  "previewOverwrite": false,
  "stalkerDBServer": "",
  "stalkerDBUsername": "",
  "stalkerDBPassword": "",
  "objectDetectionEnabled": false,
  "createPreviewPeriod": 5000,
  "restartStreamFetcherPeriod": 0,
  "startStreamFetcherAutomatically": false,
  "streamFetcherBufferTime": 0,
  "hlsflags": "delete_segments+append_list+omit_endlist+program_date_time",
  "mySqlClientPath": "/usr/local/antmedia/mysql",
  "muxerFinishScript": "",
  "webRTCFrameRate": 25,
  "webRTCPortRangeMin": 50000,
  "webRTCPortRangeMax": 60000,
  "stunServerURI": "stun:stun1.l.google.com:19302",
  "turnServerUsername": "",
  "turnServerCredential": "",
  "webRTCTcpCandidatesEnabled": false,
  "webRTCSdpSemantics": "unifiedPlan",
  "portAllocatorFlags": 0,
  "encoderName": "",
  "encoderPreset": "",
  "encoderProfile": "",
  "encoderLevel": "",
  "encoderRc": "",
  "encoderSpecific": "",
  "encoderThreadCount": 0,
  "encoderThreadType": 0,
  "vp8EncoderSpeed": 4,
  "vp8EncoderDeadline": "realtime",
  "vp8EncoderThreadCount": 1,
  "previewHeight": 480,
  "generatePreview": false,
  "writeStatsToDatastore": true,
  "encoderSelectionPreference": "gpu_and_cpu",
  "allowedPublisherCIDR": "",
  "excessiveBandwidthValue": 300000,
  "excessiveBandwidthCallThreshold": 3,
  "excessiveBandwithTryCountBeforeSwitchback": 4,
  "excessiveBandwidthAlgorithmEnabled": false,
  "packetLossDiffThresholdForSwitchback": 10,
  "rttMeasurementDiffThresholdForSwitchback": 20,
  "replaceCandidateAddrWithServerAddr": false,
  "appName": "...",
  "encodingTimeout": 5000,
  "webRTCClientStartTimeoutMs": 10000,
  "defaultDecodersEnabled": false,
  "updateTime": 0,
  "httpForwardingExtension": "",
  "httpForwardingBaseURL": "",
  "maxAnalyzeDurationMS": 1500,
  "disableIPv6Candidates": true,
  "rtspPullTransportType": "3",
  "rtspTimeoutDurationMs": 5000,
  "maxFpsAccept": 0,
  "maxResolutionAccept": 0,
  "h264Enabled": true,
  "vp8Enabled": false,
  "h265Enabled": false,
  "dataChannelEnabled": false,
  "dataChannelPlayerDistribution": "all",
  "rtmpIngestBufferTimeMs": 0,
  "dataChannelWebHookURL": "",
  "h265EncoderPreset": null,
  "h265EncoderProfile": null,
  "h265EncoderRc": null,
  "h265EncoderSpecific": null,
  "h265EncoderLevel": null,
  "heightRtmpForwarding": 360,
  "audioBitrateSFU": 96000,
  "dashMuxingEnabled": false,
  "aacEncodingEnabled": true,
  "gopSize": 0,
  "constantRateFactor": "23",
  "webRTCViewerLimit": -1,
  "toBeDeleted": false,
  "pullWarFile": false,
  "warFileOriginServerAddress": "",
  "jwtSecretKey": "",
  "jwtControlEnabled": false,
  "ipFilterEnabled": true,
  "ingestingStreamLimit": -1,
  "webRTCKeyframeTime": 2000,
  "jwtStreamSecretKey": "",
  "publishJwtControlEnabled": false,
  "playJwtControlEnabled": false,
  "dashHttpStreaming": true,
  "s3StreamsFolderPath": "streams",
  "s3PreviewsFolderPath": "previews",
  "dashHttpEndpoint": "",
  "hlsHttpEndpoint": "",
  "forceDecoding": false,
  "addOriginalMuxerIntoHLSPlaylist": true,
  "s3RecordingEnabled": false,
  "s3AccessKey": "",
  "s3SecretKey": "",
  "s3BucketName": "",
  "s3RegionName": "",
  "s3Endpoint": "",
  "s3CacheControl": "no-store, no-cache, must-revalidate, max-age=0",
  "s3Permission": "bucket-owner-full-control",
  "hlsEncryptionKeyInfoFile": "",
  "jwksURL": "",
  "forceAspectRatioInTranscoding": false,
  "webhookAuthenticateURL": "",
  "maxAudioTrackCount": -1,
  "maxVideoTrackCount": -1,
  "vodUploadFinishScript": "",
  "contentSecurityPolicyHeaderValue": "",
  "rtmpPlaybackEnabled": false,
  "originEdgeIdleTimeout": 2,
  "addDateTimeToHlsFileName": false,
  "playWebRTCStreamOnceForEachSession": true,
  "statsBasedABREnabled": true,
  "abrDownScalePacketLostRatio": 1,
  "abrUpScalePacketLostRatio": 0.1,
  "abrUpScaleRTTMs": 150,
  "abrUpScaleJitterMs": 30,
  "clusterCommunicationKey": "...",
  "id3TagEnabled": false,
  "sendAudioLevelToViewers": false,
  "hwScalingEnabled": false,
  "firebaseAccountKeyJSON": "",
  "subscriberAuthenticationKey": "...",
  "apnsServer": "api.sandbox.push.apple.com",
  "apnTeamId": "",
  "apnPrivateKey": "",
  "apnKeyId": "",
  "webhookRetryCount": 0,
  "secureAnalyticEndpoint": false,
  "webhookRetryDelay": 1000,
  "webhookPlayAuthUrl": "",
  "recordingSubfolder": "",
  "webhookContentType": "application/json",
  "iceGatheringTimeoutMs": 2000,
  "encoderSettings": [
    {
      "height": 720,
      "videoBitrate": 2000000,
      "audioBitrate": 128000,
      "forceEncode": true
    }
  ]
}
```

**Comment by mekya** [comment] 2024-08-12 11:44
Hi Guys,
I've encountered a similar problem. 

Double check the date time in "EXT-X-PROGRAM-DATE-TIME" are correct. 

I've encountered these values are not fully correct and they may shift. 

I hope it may help you identify the problem. 

FYI

**Comment by yashtandon113** [comment] 2024-11-01 18:50
@burak-58 @mekya 

FYI, please, the issue is still reproducible using the same reproduce scenario with the latest version 2.11.3 and snapshot version.

I have updated the issue description for more clarity.

**Comment by yashtandon113** [comment] 2024-11-05 16:07
After further testing with @lastpeony, we found that the defined issue comes with the HTTPS and with HTTP, it works as expected.

**Comment by lastpeony** [comment] 2024-11-05 18:07
As @yashtandon113 mentioned this issue was occuring only in HTTPS.
I investigated and found out that ContentCachingResponseWrapper class behaves a bit different in HTTPS. If its buffer is not reseted correctly it appends hole m3u8 file to the modified m3u8 content.

Mentioned PR adresses this issue and fixes the problem. @yashtandon113 also verified the fix working correctly as expected in https server.

**Closed** 2024-11-25 10:34 UTC
