### ISSUE TITLE
Error: Could not find or load main class org.red5.server.Bootstrap

### ISSUE THREAD

**Issue by ishandutta2007** [ant-media/Ant-Media-Server#9] opened 2017-10-17 23:05 UTC
The instructions [here](https://github.com/ant-media/LiveVideoBroadcaster#step-1-get-a-media-server) tells, just download and run `./red5.sh` but I guess something more is required.

ishandutta2007@MacBook-Pro:~/Documents/Projects/red5-server/src/main/server$ `bash red5.sh `
> Running on  Darwin
> Starting Red5
> Error: Could not find or load main class org.red5.server.Bootstrap
>

**Comment by mekya** [comment] 2017-10-21 07:41
Yeah you are right. I have updated the document. Please let me know if you still have problem. 

In addition, I can give instant support via slack or whatsapp if you wish. 

Regards,
A. Oguz

**Comment by ishandutta2007** [comment] 2017-10-21 08:52
I downloded the zip from the site than cloning this repo and got the server started. By the way which documentaion you are talking about, I don't see anywhere any mention the difference between zip on your site and this repo? I guess building this repo you need to copy the latest jar to the extracted zip download from your site for any code update. Isn't it ? Can you get these steps mentioned properly somewhere. The video just shows to build and copy but doesnt give info where those zips are required and where those came from in first place.
As far as this issue is considered you can close it once you point me to those documentations.

**Comment by mekya** [comment] 2017-10-22 06:48
I mean the README document which now says start.sh by starting the server.

Ok. I am going to try to document this and let you know.

**Comment by mekya** [comment] 2017-10-27 07:19
Build From Source instructions is added to Getting_Started.md

https://github.com/ant-media/Ant-Media-Server/blob/master/doc/Getting_Started.md

**Comment by mekya** [comment] 2017-11-04 06:39
Closing this issue. Please reopen it if you have still a problem.

**Closed by mekya** 2017-11-04 06:39 UTC

**Comment by devsideal** [comment] 2018-04-07 07:01
I'm also getting same error, When starting server
```
Devs-iMac:~ dev$ sh /Users/dev/Downloads/Ant-Media-Server-ams-v1.2.6/src/main/server/start.sh 
Running on  Darwin
Starting Ant Media Server
Error: Could not find or load main class org.red5.server.Bootstrap
```
I used v1.3.1 and v1.2.6,
Which version i should use, that contain Bootstrap class ?

**Comment by aun408** [comment] 2018-04-08 11:30
I am having the same error also, can help?

Do I need to preinstall any software before I run this? Like red5

**Comment by mekya** [comment] 2018-04-09 05:08
@devsideal ,
You should download from [releases](https://github.com/ant-media/Ant-Media-Server/releases). 
If you want to build from source follow the [Building From Source](https://github.com/ant-media/Ant-Media-Server/blob/master/doc/Getting_Started.md) instructions


@aun408 ,
The simplest way to install Ant Media Server is running it as a Service. There is a one shot script you it install all required softwares and ant media server to your ubuntu box. [Here is the link for that](https://github.com/ant-media/Ant-Media-Server/blob/master/doc/Getting_Started.md#running-as-a-service)

**Comment by devsideal** [comment] 2018-04-09 06:39
@mekya ,
Still same error i just download [this version](https://github.com/ant-media/Ant-Media-Server/releases/download/ams-v1.2.6/ant-media-server-community-1.2.6-180223_0931.zip) of release, extract zip and run the start.sh.

**Comment by mekya** [comment] 2018-04-09 07:30
Could you try to install this way([running as a service](https://github.com/ant-media/Ant-Media-Server/blob/master/doc/Getting_Started.md#running-as-a-service))? It is likely some required softwares are not installed on your system.

**Comment by devsideal** [comment] 2018-04-09 11:26
Yes now its seems to working using the way running as a service (on ubuntu),
But now I'm facing [this issue](https://github.com/ant-media/LiveVideoBroadcaster/issues/26#issuecomment-379719710)

**Comment by mortezakhorshidy** [comment] 2018-06-29 23:17
hi 
please run in path
sh start-debug.sh

**Comment by Chivorns** [comment] 2018-10-11 07:45
After run : sh start-debug.sh
I got error as bellow:

Bootstrap exception: null
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.red5.server.Bootstrap.bootStrap(Bootstrap.java:122)
        at org.red5.server.Bootstrap.main(Bootstrap.java:50)
Caused by: java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1220)
        at org.bytedeco.javacpp.Loader.load(Loader.java:980)
        at org.bytedeco.javacpp.Loader.load(Loader.java:879)
        at org.bytedeco.javacpp.avutil.<clinit>(avutil.java:10)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.bytedeco.javacpp.Loader.load(Loader.java:938)
        at org.bytedeco.javacpp.Loader.load(Loader.java:879)
        at org.bytedeco.javacpp.avformat.<clinit>(avformat.java:14)
        at org.red5.server.Launcher.launch(Launcher.java:67)
        ... 6 more
Caused by: java.lang.UnsatisfiedLinkError: no avutil in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1220)
        at org.bytedeco.javacpp.Loader.load(Loader.java:965)
        ... 14 more
Bootstrap exit

**Comment by mekya** [comment] 2018-10-12 12:56
Which version do you download, which OS and java environment?

Btw, could you use bash shell?

**Comment by selina21** [comment] 2021-03-16 13:34
> The instructions [here](https://github.com/ant-media/LiveVideoBroadcaster#step-1-get-a-media-server) tells, just download and run `./red5.sh` but I guess something more is required.
> 
> ishandutta2007@MacBook-Pro:~/Documents/Projects/red5-server/src/main/server$ `bash red5.sh `
> 
> > Running on  Darwin
> > Starting Red5
> > Error: Could not find or load main class org.red5.server.Bootstrap

what if theWindows10 ？I downloaded red5，but there are some promblems:
Starting Red5
Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
错误: 找不到或无法加载主类 org.red5.server.Bootstrap
原因: java.lang.ClassNotFoundException: org.red5.server.Bootstrap
wondering how to solve it........

**Comment by mekya** [comment] 2021-03-16 14:40
Hi @selina21 ,

Thank you for your message.

We don't maintain LiveVideoBroadcaster anymore. However it's compatible with Ant Media Server. 
Please install the Ant Media Server according to the its documentation 
https://github.com/ant-media/Ant-Media-Server/wiki/Installation
