### ISSUE TITLE
Automatic Camera Activation on Flutter SDK Publish sample

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#5224] opened 2023-06-12 07:01 UTC
A user wants to have a feature in the Flutter SDK that automatically activates the camera as soon as the Publish page/function is called on the Flutter app, even before connecting to the server or starting the publishing process.

https://antmedia.freshdesk.com/a/tickets/95573

**Comment by USAMAWIZARD** [comment] 2023-06-16 15:19
@Mohit-3196 does something like this works ?

![image](https://github.com/ant-media/Ant-Media-Server/assets/47350008/23212525-c13d-4bb4-abfa-625129690747)

**Comment by OrbysSocialMediaLLC** [comment] 2023-06-16 20:46
Something along those lines exactly.

**Comment by OrbysSocialMediaLLC** [comment] 2023-06-16 20:56
> @Mohit-3196 does something like this works ?
> 
> ![image](https://user-images.githubusercontent.com/47350008/246459479-23212525-c13d-4bb4-abfa-625129690747.png)

yes

**Comment by OrbysSocialMediaLLC** [comment] 2023-06-16 21:25
> @Mohit-3196 does something like this works ?
> 
> ![image](https://user-images.githubusercontent.com/47350008/246459479-23212525-c13d-4bb4-abfa-625129690747.png)

I'm guessing this is like a MediaStream that is activated before the publish. I will already have all the publish settings in that page also Like Servers, Etc, I need to be able to control the camera, Mute etc also before ethe live stream is started . Just like Facebook you could use Facebook as an example. Live In Facebook.

**Comment by USAMAWIZARD** [comment] 2023-06-18 16:46
Sure, Currently it just displayed camera as it is and does not provide any option to turn off cam or mute Unmute mic I will try to implement it and let you know once its done

**Comment by OrbysSocialMediaLLC** [comment] 2023-06-18 17:52
> Sure, Currently it just displayed camera as it is and does not provide any option to turn off cam or mute Unmute mic I will try to implement it and let you know once its done

Turning off the camera will be hen they leave the page? Because for example let's say I finished a Live Stream and I want to start a new one, I will have a Function that will create a new Live Stream on the server side and provide it to the app in flutter. So if the user press Go Live agan they could do it from the same screen. Again Just like FaceBook live video.

To be clear this is something that all Live Streaming apps have. YouTube, Facebook etc. 

The managing of the Mic, Switch Camera etc. will be done Before and During the live Video

**Comment by USAMAWIZARD** [comment] 2023-06-22 18:29
https://github.com/ant-media/Ant-Media-Server/assets/47350008/ff44e3a3-5730-4f39-9616-0d5995653fce

https://github.com/ant-media/WebRTC-Flutter-SDK/tree/preview_cam_and_publish

**Comment by USAMAWIZARD** [comment] 2023-07-13 06:31
All issues are resolved I confirmed with the user that we can close this issue

**Comment by OrbysSocialMediaLLC** [comment] 2023-07-14 19:18
Usama Sorry but the issues are not resolved. I opened all ports on my firewall and Still have the Green Images and The turn around screens.


***@***.***

**Comment by OrbysSocialMediaLLC** [comment] 2023-07-14 19:19
***@***.***

**Comment by OrbysSocialMediaLLC** [comment] 2023-07-16 12:57
ANOTHER ISSUE - IF I ENABLE DATA CHANNEL THERE IS NO CAMERA OR AUDIO IN THE VIDEO...

From: Orbys Support
Sent: Friday, July 14, 2023 3:19 PM
To: ant-media/Ant-Media-Server ***@***.***>; ant-media/Ant-Media-Server ***@***.***>
Cc: Comment ***@***.***>
Subject: RE: [ant-media/Ant-Media-Server] Automatic Camera Activation on Flutter SDK Publish sample (Issue #5224)

***@***.***

**Comment by USAMAWIZARD** [comment] 2023-07-17 11:03
Problem remaining 
1. Artifacts on the video
2. enable data channel causing 
Problems Resolved
1.  go live button that a stop button 
3.  video getting mirrored  solved
4. HLS video getting rotated sideways
5. camera switching issues

**Comment by USAMAWIZARD** [comment] 2023-07-24 10:57
I have Created a new issue for that and fixed it we can close this issue here.

**Comment by OrbysSocialMediaLLC** [comment] 2023-07-25 15:19
undefinedg] INFO  org.red5.server.Context - Deployment type: bootstrap
2023-07-25 15:18:02,392 [Loader:/testing] WARN  o.s.w.c.s.XmlWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'web.scope' defined in ServletContext resource [/WEB-INF/red5-web.xml]: Cannot resolve reference to bean 'web.handler' while setting bean property 'handler'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'web.handler' defined in ServletContext resource [/WEB-INF/red5-web.xml]: Cannot resolve reference to bean 'dataStoreFactory' while setting bean property 'dataStoreFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataStoreFactory' defined in ServletContext resource [/WEB-INF/red5-web.xml]: Initialization of bean failed; nested exception is org.mapdb.DBException$VolumeIOError
2023-07-25 15:18:02,397 [Loader:/testing] ERROR org.red5.server.tomcat.TomcatLoader - org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'web.scope' defined in ServletContext resource [/WEB-INF/red5-web.xml]: Cannot resolve reference to bean 'web.handler' while setting bean property 'handler'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'web.handler' defined in ServletContext resource [/WEB-INF/red5-web.xml]: Cannot resolve reference to bean 'dataStoreFactory' while setting bean property 'dataStoreFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataStoreFactory' defined in ServletContext resource [/WEB-INF/red5-web.xml]: Initialization of bean failed; nested exception is org.mapdb.DBException$VolumeIOError
                at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342)
                at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1707)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1452)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
                at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
                at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
                at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
                at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
                at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
                at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)
                at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
                at org.red5.server.tomcat.TomcatLoader$1.run(TomcatLoader.java:517)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'web.handler' defined in ServletContext resource [/WEB-INF/red5-web.xml]: Cannot resolve reference to bean 'dataStoreFactory' while setting bean property 'dataStoreFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataStoreFactory' defined in ServletContext resource [/WEB-INF/red5-web.xml]: Initialization of bean failed; nested exception is org.mapdb.DBException$VolumeIOError
                at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342)
                at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1707)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1452)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
                at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
                at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
                at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
                at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
                at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330)
                ... 18 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataStoreFactory' defined in ServletContext resource [/WEB-INF/red5-web.xml]: Initialization of bean failed; nested exception is org.mapdb.DBException$VolumeIOError
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:628)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
                at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
                at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
                at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
                at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
                at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330)
                ... 28 more
Caused by: org.mapdb.DBException$VolumeIOError
                at org.mapdb.volume.MappedFileVol.<init>(MappedFileVol.java:113)
                at org.mapdb.volume.MappedFileVol$MappedFileFactory.factory(MappedFileVol.java:64)
                at org.mapdb.volume.MappedFileVol$MappedFileFactory.makeVolume(MappedFileVol.java:38)
                at org.mapdb.StoreDirect$volume$1.invoke(StoreDirect.kt:77)
                at org.mapdb.StoreDirect$volume$1.invoke(StoreDirect.kt:16)
                at org.mapdb.StoreDirect.<init>(StoreDirect.kt:76)
                at org.mapdb.StoreDirect$Companion.make(StoreDirect.kt:57)
                at org.mapdb.StoreDirect$Companion.make$default(StoreDirect.kt:56)
                at org.mapdb.DBMaker$Maker.make(DBMaker.kt:450)
                at io.antmedia.datastore.db.MapDBStore.<init>(MapDBStore.java:52)
                at io.antmedia.datastore.db.DataStoreFactory.init(DataStoreFactory.java:104)
                at io.antmedia.datastore.db.DataStoreFactory.setApplicationContext(DataStoreFactory.java:148)
                at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:128)
                at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:102)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
                ... 34 more
Caused by: java.io.FileNotFoundException: testing.db (Permission denied)
                at java.base/java.io.RandomAccessFile.open0(Native Method)
                at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
                at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
                at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
                at org.mapdb.volume.MappedFileVol.<init>(MappedFileVol.java:85)
                ... 50 more

2023-07-25 15:18:04,276 [https-jsse-nio2-0.0.0.0-5443-exec-3] INFO  io.antmedia.rest.RestServiceBase - Version Name 2.6.2 Version Type Enterprise Edition
2023-07-25 15:18:04,365 [https-jsse-nio2-0.0.0.0-5443-exec-2] WARN  io.antmedia.statistic.GPUUtils - UnsatisfiedLinkError no cuda installed no jnicudart in java.library.path: [/usr/local/antmedia/lib/native]
2023-07-25 15:18:16,037 [https-jsse-nio2-0.0.0.0-5443-exec-10] INFO  i.a.e.s.WebSocketLocalHandler - Web Socket opened session:0 user-agent:[Dart/3.0 (dart:io)]
2023-07-25 15:18:25,993 [https-jsse-nio2-0.0.0.0-5443-exec-1] INFO  i.a.console.rest.SupportRestService - New Support Request
2023-07-25 15:18:25,997 [https-jsse-nio2-0.0.0.0-5443-exec-1] INFO  io.antmedia.rest.RestServiceBase - Version Name 2.6.2 Version Type Enterprise Edition

**Closed** 2023-08-07 11:05 UTC
Labels: enterprise-user-request, flutter-sdk
