### ISSUE TITLE
How to add watermark to video content

### ISSUE THREAD

**Issue by ntnahn** [ant-media/Ant-Media-Server#735] opened 2018-12-24 11:00 UTC
# Issue

### Short description
I want to add watermark on video stored or both when streaming. Is it possible and how to do it?

Thanks

**Comment by SelimEmre** [comment] 2019-01-12 20:46
Hi @ntnahn,
Thank you for your interest. Can you try the following options?
1-You can add watermark in a stream in OBS. 
2-You can add watermark to recorded videos via 3rd party softwares.
We're thinking adding the watermark feature in the new version. Thanks for your feedback.

**Comment by ntnahn** [comment] 2019-01-17 04:08
Thanks for your answer. I'm waiting for the next version 👍

**Comment by mekya** [comment] 2019-12-02 17:44
Duplicate of #1530

**Closed by mekya** 2019-12-02 17:44 UTC
Labels: duplicate, feature-request, investigating
