### ISSUE TITLE
JS SDK and React Native SDK Reconnection Issues

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#6333] opened 2024-05-15 08:54 UTC
- When reconnection happens, play stream ids are duplicated,  remote tracks are damaged and cannot be playable, and we cannot publish again.
- When we stop playing or publishing and try to do it again, websocket connection closed randomly and  the sample app cannot work until we restarted the application.

**Comment by MaZZly** [comment] 2024-05-15 11:54
For more info on this problem see the following: https://github.com/ant-media/Ant-Media-Server/issues/4071#issuecomment-2012348181

**Comment by mustafaboleken** [comment] 2024-05-26 21:36
Hi @MaZZly 

I just finished the implementation and it works for me. Can you please test it and tell me if it works for you or not?

Btw, other than these changes, you need to make a couple of configuration changes:

Go to the management console, edit advanced settings, and set  ` "encodingTimeout": 500`,  `"webRTCClientStartTimeoutMs": 1000`

Also, you mentioned about the `newTrackAvailable` is not received after ice connection change. To be able to receive the latest tracks, you can call `requestVideoTrackAssignments(streamId)` function and you will get video_track_assignment_list and audio_track_assignment callbacks. Then, you can just update them.

**Comment by MaZZly** [comment] 2024-05-27 05:09
@mustafaboleken we will go through it and see if it works as needed for network changes :)

**Comment by MaZZly** [comment] 2024-05-27 11:35
@mustafaboleken it seems to be a bit better, but there are still cases where it stops working and seem to get into a "runaway" scenario where the console flooding with triggered events for reconnection_attempt_for_X/unathorized_access/already_playing.

By the way, we haven't needed or seen any events of the `requestVideoTrackAssignments` or `video_track_assignment_list` type yet.

# Runaway/flooding problem scenario
- Have 3 participants join a conference room and publish their own streams as `host`, `client` and `mobile_client` (from e.g. Android phone)
  - have all these streams visible on all devices also, just like e.g. a normal Teams/Zoom call or similar
- On the mobile client, Toggle back and forth between wifi and cellular couple of times, making sure to let the streams "recover"...
- You can also try fully disabling the internet access for a while and re-enabling it.

After doing this for a while (and it seems after `WebSocketNotConnected` has triggered a couple times) it will start to flood the console with more and more of the following:
- `reconnection_attempt_for_publisher` (multiple times for same streamid)
- `reconnection_attempt_for_player` (multiple times for same streamid)
- `Cannot send message:`
- `WebSocketNotConnected`
- `unauthorized_access` (hundreds of them for the same streamids)
- `already_playing` (hundreds of them for the same streamids)

So it seems there is something that starts spawning multiple calls when the websocket connection has been gone in to some state (multiple disconnects?) and from there just keeps spawning more and more events, creating a runaway scenario where no streaming works anymore and the device/tab ultimately becomes unusable.

**Comment by mustafaboleken** [comment] 2024-05-27 13:47
Hi @MaZZly 

I will try the scenario you provided. Btw, can you tell me your ant media server version?

**Comment by MaZZly** [comment] 2024-05-28 05:08
@mustafaboleken it is `Enterprise Edition 2.9.0 20240405_1755`

**Comment by MaZZly** [comment] 2024-05-28 07:44
@mustafaboleken did some more testing with 2 participants, one streaming from mobile, and one watcher from desktop. This is probably the easiest I've been able to reproduce problems so far.

# Problem with broadcast after network switch
- Connect to a room from desktop and mobile(Android on mobile network)
  - Android to publish stream, desktop to watch it.
-  Turn off the mobile network
- Wait for the error `WebSocket connection to '...' failed: ...`
- Turn the mobile network back on.
- wait for `publish_started` event to trigger
  - Broadcast is visible in AMS ui
  - The watcher is not notified about new stream in room... Doing `webRTCAdaptor.getRoomInfo(` triggers callback `no_active_streams_in_room`) 

We have logic for killing the broadcast if  `streamIdInUse` triggers, but I also tried without and the same thing happens..

I also noticed that with the 1000ms setting, we are pretty often triggering `publishTimeoutError` on the mobile client... Is that really needed/better than the 3000 default setting? 
**Note that the 1000ms timeout might be "okay" in your test setup, and not triggering the problem described above...**

Anyway, there seems to be some timing issue somewhere, and the even though the server sees the newly started broadcast, it is not passed on to the other participants in the room. Is there somewhere in AMS UI where I can see if the broadcast is tied to a room?

**Comment by mustafaboleken** [comment] 2024-05-28 08:06
Hi @MaZZly 

When I think about these two things

`By the way, we haven't needed or seen any events of the requestVideoTrackAssignments or video_track_assignment_list type yet.
`

and 

`Doing webRTCAdaptor.getRoomInfo( triggers callback no_active_streams_in_room`

I realize that you are using a stream-based conference solution. I was doing my tests with the multitrack conference samples. Probably that's why I didn't face them. 

Can you tell me which one you are using?

**Comment by MaZZly** [comment] 2024-05-28 09:09
TBH I don't know (AMS documentation is quite scattered...), but from a quick Google it seems we should've used `sdpSemantics` to enable multitrack, which we haven't. 
So I'm going to say/guess we are just using stream-based solution.

**Comment by MaZZly** [comment] 2024-05-28 09:45
Also btw, we keep seeing logs in the console for events like `no_active_streams_in_room`, is this something that can be ignored, or does it mean we are doing something wrong?

**Comment by MaZZly** [comment] 2024-05-28 11:03
also,  `webRTCAdaptor.playStreamId` still has the problem of starting to contains duplicates (multiple ones) after doing network switches...

**Comment by MaZZly** [comment] 2024-05-29 05:16
Well if the other one is deprecated I guess we should migrate... How do we proceed to get this done ASAP ?

**Comment by MaZZly** [comment] 2024-05-29 06:14
@mustafaboleken also, is the track-based conference room supported by other SDKs than JS? :thinking: If not, when are they planned?

**Comment by mustafaboleken** [comment] 2024-05-29 08:40
Yes, the multitrack approach is supported by all of our SDKs. I can prepare a migration guide and send it to you or if you wanted to make a meeting, you can just contact me through my mail address so we can make it together. Other than my planned meetings, my first priority is solving your problem. Just let me know about your decision. @MaZZly

**Comment by MaZZly** [comment] 2024-05-29 09:08
@mustafaboleken lets start with a guide, and if something is unclear we can do a meeting to go through the unclear details :)

**Comment by mustafaboleken** [comment] 2024-05-29 09:30
Sure, I will prepare and send it to you in 2 hours. :)

**Comment by mustafaboleken** [comment] 2024-05-29 11:59
### Key Updates and Changes

1. **Room Structure Removal**:
   - The room structure has been completely removed. Instead, there is now one main track broadcast that acts as the room, with participants added as sub-track broadcasts into the main broadcast.

2. **Simplified Participant Management**:
   - There is no need to store participants in lists like `roomOfStream` or `streamsList` as in the previous sample. Instead, you can check the subTracks of the main broadcasts. [More details here](https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/conference.html#L583).

3. **Storing Status in Metadata**:
   - The microphone, camera, and screen share status can now be stored inside the metadata field. [More details here](https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/conference.html#L605).

4. **Function Simplification**:
   - The `joinRoom`, `leave`, and `getRoomInfo` functions are no longer needed. All you need to do is publish to the main broadcast and play it. [More details here](https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/conference.html#L479).

5. **New Callbacks**:
   - You can check the new callbacks that have been introduced. [More details here](https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/conference.html#L655).

6. **New Websocket Message**:
   - A new websocket message called `getBroadcastObject` has been introduced to retrieve the Broadcast structure as JSON. This broadcast can be either a Maintrack or a Subtrack. Obtain a Broadcast object for a main track by calling `getBroadcastObject` with the room ID, and for a subtrack, use its ID.

7. **Event-Based Approach**:
   - The `getRoomInfo` method is no longer used. Instead, an event-based approach has been introduced. Applications will now be notified by the `TRACK_LIST_UPDATED` Data Channel message. Upon receiving this notification, applications can call `getBroadcastObject` for the Maintrack, check the subtracks, and obtain participant names by calling `getBroadcastObject` for the participant ID.

---

<img src='https://antmedia.io/wp-content/uploads/2022/12/Untitled.png'></img>

**Comment by mustafaboleken** [comment] 2024-05-29 12:00
Also I have a pr to show how to implement reconnection mechanism, you can also take a look at that https://github.com/ant-media/StreamApp/pull/468 @MaZZly

**Comment by MaZZly** [comment] 2024-05-30 06:33
@mustafaboleken I sent you a mail about setting up a chat :)

**Comment by mustafaboleken** [comment] 2024-05-30 08:48
You can check the inbox. @MaZZly

**Comment by Mohit-3196** [comment] 2024-06-05 09:37
Hi @MaZZly,

> TBH I don't know (AMS documentation is quite scattered...), but from a quick Google it seems we should've used `sdpSemantics` to enable multitrack, which we haven't. So I'm going to say/guess we are just using stream-based solution.

I'm sorry you had to face problems with the documentation and couldn't find the right instructions while you were implementing the solution.
We are continuously trying to improve the documents and make them more useful and user-friendly.
It is already mentioned in the [multitrack document](https://antmedia.io/docs/guides/publish-live-stream/multitrack-publish-and-play-with-ams/) that the `sdpSemantics` should be set to Unified Plan which is also set by default in AMS v2.4.3 and above.

It seems like we are missing some pieces in the documents and it would be great if you can guide me so that it can improved further.
May I know which specific document you looked at and what are the issues you face about the documentation so that we can improve the same?

Thank you,
Mohit

**Comment by burak-58** [comment] 2024-09-02 10:40
Fixed with https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/726

**Closed by burak-58** 2024-09-02 10:40 UTC
Labels: bug, Priority: Urgent
