### ISSUE TITLE
Getting the "already_playing" error on Firefox

### ISSUE THREAD

**Issue by louaiah** [ant-media/Ant-Media-Server#5397] opened 2023-07-24 18:04 UTC
### Short description
Stream keeps restarting with the "already_playing" error showing up, making the streams unusable.

### Environment

* Operating system and version: Microsoft Windows 10 Home - 10.0.19045 build 19045
* Java version: openjdk 11.0.19 2023-04-18
                       OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu120.04.1)
                       OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu120.04.1, mixed mode, sharing)
* Ant Media Server version: Enterprise Edition 2.6.2 20230623_0843
* Browser name and version: Mozilla Firefox 115.0.2 (64-bit)

### Steps to reproduce
1. open ant-media-server/appname/player.html on firefox on windows 10

### Expected behavior
Stream should start playing

### Actual behavior
Stream keeps trying to play and never succeeding
Working fine on Chrome and Edge
 

### Logs
```
pong notification received [player.html:508:13](https://appname/WebRTCAppEE/player.html)
play finished [player.html:329:13](https://appname/WebRTCAppEE/player.html)
It will try to play again because it is not stopped on purpose [webrtc_adaptor.js:646:22](https://appname/WebRTCAppEE/js/webrtc_adaptor.js)
pong notification received 2 [player.html:508:13](https://appname/WebRTCAppEE/player.html)
It will try to play again because it is not stopped on purpose [webrtc_adaptor.js:646:22](https://appname/WebRTCAppEE/js/webrtc_adaptor.js)
error callback: "already_playing" [utility.js:81:12](https://appname/WebRTCAppEE/js/utility.js)
already_playing [utility.js:121:12](https://appname/WebRTCAppEE/js/utility.js)

    errorHandler https://appname/WebRTCAppEE/js/utility.js:121
    callbackError https://appname/WebRTCAppEE/player.html:514
    notifyErrorEventListeners https://appname/WebRTCAppEE/js/webrtc_adaptor.js:410
    callbackError https://appname/WebRTCAppEE/js/webrtc_adaptor.js:1550
    onmessage https://appname/WebRTCAppEE/js/websocket_adaptor.js:89

Object { streamId: "foo", definition: "already_playing", command: "error" }
[utility.js:123:16](https://appname/WebRTCAppEE/js/utility.js)
pong notification received [player.html:508:13](https://appname/WebRTCAppEE/player.html)
play finished [player.html:329:13](https://appname/WebRTCAppEE/player.html)
It will try to play again because it is not stopped on purpose [webrtc_adaptor.js:646:22](https://appname/WebRTCAppEE/js/webrtc_adaptor.js)
pong notification received [player.html:508:13](https://appname/WebRTCAppEE/player.html)
It will try to play again because it is not stopped on purpose

```
this will continue on looping
Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by mekya** [comment] 2023-08-01 08:04
Hi @louaiah,

Thank you for the issue. I've quickly tested it on my end(mac, firefox) and could not reproduce the issue. 

Do you encounter the same problem again when you use this player?
https://test.antmedia.io/WebRTCAppEE/player.html

**Comment by louaiah** [comment] 2023-08-01 14:51
Hi @mekya,

Thanks for following up, just tested this player and I'm still having the same issue, the stream never plays.

To be clear, I'm only having this issue on **Firefox** on **Windows 10**. Edge and Chrome on Windows are working fine, as are Safari, Chrome, and Firefox on Mac.

**Comment by mekya** [comment] 2023-08-07 09:01
Hi @louaiah,

Thank you for making it clear. 

I'm putting to the backlog to resolve it. 

Regards

**Comment by Mohit-3196** [comment] 2023-08-14 07:32
Hi @louaiah ,
How are you doing?

I tested by playing a stream using player.html sample page on Firefox 116.0.2 which is the latest version it seems and I could play it without any issues.
I even tried playing in multiple tabs and it seems fine.

Here's a sample screen recording for the same 

https://github.com/ant-media/Ant-Media-Server/assets/86982446/af53c2ae-1fda-4d1f-bd16-424178e5eb20

Please let me know if I'm missing something here.

Thank you

**Comment by louaiah** [comment] 2023-08-14 18:02
Hi @mekya,
Turns out the issue was due to the openh264 plugin not being installed properly on my end. Really sorry for the confusion, the issue just got resolved and streams are now running properly. Thanks.

**Comment by Mohit-3196** [comment] 2023-08-14 18:07
Hi @louaiah ,
It is good to know that everything is fine now :)
And no worries, we are here to help you whenever needed.

I'm closing this issue now. Let me know if it is fine.

Thank you

**Comment by louaiah** [comment] 2023-08-14 18:11
Sounds good. Thank you for your time :)

**Closed** 2023-08-21 11:09 UTC
Labels: support, awaiting-confirmation
