### ISSUE TITLE
Is this CMAF ULL DASH supported by Ant Media?

### ISSUE THREAD

**Issue by jplogos** [ant-media/Ant-Media-Server#3753] opened 2021-11-19 06:47 UTC
Hi, Can you please tell , Is that CMAF ULL DASH (chunked transfer) supported by Ant media? 

if so, 

- Which OS version supported?
- What it the max benchmarked  throughput by Ant Media server for CMAF ULL requests?

Thx.
JP.

**Comment by mekya** [comment] 2021-11-22 16:50
Hi @jplogos ,

Yes, it's supported.  

> Which OS version supported?
Ubuntu 18.04 is officially supported. 
> What it the max benchmarked throughput by Ant Media server for CMAF ULL requests?
We've not heavily tested the CMAF throughput.  One support engineer can help you make the benchmark test.


This issue is not a bug or a feature request. I'll close it if it's ok for you 

Support related questions can be asked in the community. Support engineers will answer the questions there. 
https://groups.google.com/g/ant-media-server

**Comment by mekya** [comment] 2021-11-29 17:48
I'm closing this issue for the inactivity and no-response

**Closed by mekya** 2021-11-29 17:48 UTC
