### ISSUE TITLE
Live stream recording has video/audio sync issue in AlmaLinux

### ISSUE THREAD

**Issue by timantmedia** [ant-media/Ant-Media-Server#5134] opened 2023-05-22 08:50 UTC
### Short description
Stream is broadcasting live without any problems. No audio issues. After the live broadcasting stream is saved into an mp4 and moved to the storage server, playback experiences an audio sync issue with a 2 to 3 seconds latency.

This is not happening all the time and it's not reproducible. 

### Environment

* Operating system and version:
openjdk version "11.0.18" 2023-01-17 LTS
OpenJDK Runtime Environment (Red_Hat-11.0.18.0.10-2.el8_7) (build 11.0.18+10-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-11.0.18.0.10-2.el8_7) (build 11.0.18+10-LTS, mixed mode, sharing)
 
4.18.0-425.13.1.el8_7.x86_64
 
NAME="AlmaLinux"
VERSION="8.7 (Stone Smilodon)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.7 (Stone Smilodon)"
 
* Java version:
 
* Ant Media Server version:
Enterprise Edition 2.5.3 20230107-0851

### Steps to reproduce
start live stream
watch it in ANT
No latency
Recording is stopped
Stream is moved to VOD
Watch VOD and there is audio latency of 2 – 3 seconds

**Comment by mekya** [comment] 2023-05-22 12:06
Make sure h264 encoder is not generating B-frames and set tune to zerolatency.

**Comment by timantmedia** [comment] 2023-06-23 11:12
@mekya customer is not using b-frames and has tuned to zerolatency. 

I captured the raw stream and managed to reproduce the issue locally with an MP4 recording having the audio out of sync.

**Comment by timantmedia** [comment] 2023-07-11 09:59
@mustafaboleken have you managed to uncover anything from your investigation?

**Comment by timantmedia** [comment] 2023-07-24 08:56
@mustafaboleken Wondering if there is any movement on this issue. It's been a while, do we need more information from the customer?

**Comment by mekya** [comment] 2023-07-24 10:33
I'm moving this task to backlog. Please raise this if an user is waiting for this development.

**Comment by timantmedia** [comment] 2023-07-27 09:46
@mekya we have a ticket FD 93386 the customer has been waiting for feedback on this issue for almost 1 month. We have the raw stream and MP4 recorded stream and need to find out why the audio is not syncing in the MP4 recording but is fine on the live stream.

**Comment by mekya** [comment] 2023-08-01 07:33
Hi @timantmedia,

I understand that it is about 1 month. On the other hand, we don't have availability for this issue yet. I hope you let the customer know that sometimes fixing issue takes time due to team availability, number of pending issues, priority and workarounds. 

As quick workaround, please use the Ubuntu. If the problem happens in Ubuntu, we'll increase the priority of this issue to understand what the problem is. 

Regards
Oz

**Comment by timantmedia** [comment] 2023-09-12 08:01
@mekya When we stream the raw FLV to a test server running Ubuntu, then the issue persists.

**Comment by timantmedia** [comment] 2023-09-13 06:58
@mekya @mustafaboleken can we make sure to schedule this again next week. Using Ubuntu does not have any positive results.

**Comment by mustafaboleken** [comment] 2023-09-13 07:51
It's okay for me. I can take a look again next sprint

**Comment by timantmedia** [comment] 2023-09-13 13:41
@mustafaboleken I just tried reproducing in version 2.6.4 and it seems its resolved in that version. Are you able to confirm that? If it has, it would be great to understand what the problem was if you are able to identify the changes.

**Comment by mustafaboleken** [comment] 2023-09-14 07:54
@timantmedia I confirm that it's resolved. There are 4 releases between 2.5.3 and 2.6.4 But when I check the changelogs it's probably fixed by the FFmpeg update. 

Their changelog is bad but you can check https://github.com/FFmpeg/FFmpeg/blob/master/Changelog

We updated from 4.3 to 5.1

**Comment by mustafaboleken** [comment] 2023-09-25 11:39
Because we didn't get any response from the customer, I'm closing for now. If it's not working or have some questions, we can always reopen it.

**Comment by mekya** [comment] 2023-09-29 06:24
This is the file that we're talking about 

https://drive.google.com/file/d/1Avv19pO2o2NaY2oV2-Irx7YT6L5Vc_2H/view?usp=sharing

**Comment by timantmedia** [comment] 2023-10-05 11:41
> This is the file that is being used in testing. TBH, I don't understand how it's being used and how to confirm the issue. I'm just putting the link below.
> 
> https://drive.google.com/file/d/1Avv19pO2o2NaY2oV2-Irx7YT6L5Vc_2H/view?usp=sharing

@mekya That file is the raw RTMP stream saved as FLV. So by using an FFMPEG command, we can live stream this file to Ant Media Server simulating the customer's incoming live stream. 

From there, we are able to view the live stream and record it as MP4 to reproduce the audio sync issue. In version 2.6.4 the issue seemed resolved, however, the customer just responded and was not able to confirm that the upgrade resolved the problem. 

However, they are having some issues with their cluster setup after the upgrade which might be causing an indirect issue. I think I'll need to re-open this issue based on customer feedback.

**Comment by timantmedia** [comment] 2023-10-09 13:47
Waiting for the customer to confirm the exact status after reinstallation which is supposed to happen today. FD 93386

**Comment by timantmedia** [comment] 2023-10-23 11:58
The customer has still not responded to confirm if reinstallation resolved the issue.

**Comment by farawaysouthwest** [comment] 2023-11-16 05:32
I would like to add that we have also experienced this exact issue on a fresh install of 2.6.4 (community) intermittently. 

VM ram and CPU usage never getting higher than 30%.

**Comment by timantmedia** [comment] 2023-11-29 16:52
@mekya @mustafaboleken Customer's problem still persists, but the cluster issue that was introduced is now resolved. I understand that the original issue described was not clear enough, please advise what additional details you need to investigate this. 

We provided a raw stream recording from the customer that reproduced the issue by restreaming it using FFMPEG.

**Comment by mustafaboleken** [comment] 2023-11-29 17:44
Hi @timantmedia,

Oguz Abi and I had a meeting recently and after that meeting, I prepared a mail to this customer. I shared it with you on Slack. We can discuss it if you want.

**Comment by mekya** [comment] 2024-03-04 10:10
Thanks to the user, in the latest report I just see that the audio/video synch issue in the packets and I figure out that we start audio and video from zero for all cases by assuming that both of them are started at the same time on the other hand, video or audio packets may start a few milliseconds later.

Anyway, I've resolved this issue on this PR 
https://github.com/ant-media/Ant-Media-Server/pull/6150

After it's merged, please try and let me know if it works for you

**Comment by burak-58** [comment] 2024-03-18 10:36
It is fixed with [Support seeking in pulling stream sources & fix first packet audio/video sync #6150](https://github.com/ant-media/Ant-Media-Server/pull/6150)

If you encounter the same issue, please feel free to reopen it.

**Comment by lastpeony** [comment] 2024-05-03 12:51
Seen again. reported by usportfor.com

**Comment by mekya** [comment] 2024-05-06 08:01
Let us have the file to confirm that there is latency problem as we discussed and confirm the scenario again. 
Because, the months have been passed because there was no clear understanding of the problem.

**Comment by lastpeony** [comment] 2024-05-13 06:32
The user verified that the 2.8.3 snapshot, containing the necessary fix, successfully resolved the issue. However, they later noted its recurrence upon transitioning to the 2.9.0 release.

**Closed** 2024-05-27 10:52 UTC
Labels: bug
