### ISSUE TITLE
Be able to select the audio input/outputs for a session

### ISSUE THREAD

**Issue by rberger** [ant-media/Ant-Media-Server#2188] opened 2020-05-23 19:08 UTC
***Attention:*** *For your support questions, ask at [stackoverflow](https://stackoverflow.com/questions/tagged/ant-media-server) or [our community forum](https://groups.google.com/forum/#!forum/ant-media-server).*

**Is your feature request related to a problem? Please describe.**

I can not currently use the WebRTCAdapter to set the audio and video inputs. 

**Describe the solution you'd like**

Javascript APIs to set the audio inputs/outputs before and during the stream is active

**Describe alternatives you've considered**

Read thru the WebRTCAdapter code and could not figure out how to modify it myself to do this.

**Additional context**

This seems pretty fundamental

**Comment by mekya** [comment] 2020-06-03 10:21
This is a duplicate of #2164 ?

**Closed** 2020-07-27 18:23 UTC
