### ISSUE TITLE
Only video is being played in some circumstances using the IOS SDK(or reference application)

### ISSUE THREAD

**Issue by eneskuluk** [ant-media/Ant-Media-Server#2468] opened 2020-09-05 15:32 UTC
### Short description
Happening in an application that is based on IOS SDK. Same thing happens on reference application too according to client's report.
Audio playback stops and only video can be perceivable after some conditions are met.

### Environment

* Operating system and version: IOS

### Steps to reproduce
 While playing the streaming video:
(1) User switch the app into Background mode (Press Home hardware button)
(2) Turn on Flight Mode (Disable all networks connection)
(3) Turn off Flight Mode (Enable all networks connection)
(4) Switch app to Foreground Mode
(5) Reconnect to live stream video. User can play the video but cannot hear any sound.

### Expected behavior
After reconnection, audio should play without an issue like the video.

### Actual behavior
After reconnection, no audio can be hearable.

**Comment by mekya** [comment] 2020-09-21 07:13
I've tried to reproduce this problem on my end with the same scenario. However I couldn't reproduce it.

Btw, we've upgraded the WebRTC SDK to M85 recently. Maybe this problem has been fixed with the new update. 
We've not released M85 update for iOS. It's in beta. You can ask to get the beta from support team. 

Regards,
A. Oguz

**Comment by lehuy2012** [comment] 2020-09-29 03:37
Hi  @mekya 

> We've not released M85 update for iOS. It's in beta. You can ask to get the beta from support team.

-> Can you send me a URL link to download iOS SDK (beta)  like you were said that in this comment?
    We also need a URL link to download your Sample APP for testing.
   
Thanks,

**Comment by lehuy2012** [comment] 2020-10-01 12:54
Hi @mekya @SelimEmre and Support team,

If you see my comment above, please support me.

We're using Ant Media Enterprise.
Version: Edition 2.1.0 20200720_1328

Thank you,

**Comment by mekya** [comment] 2020-10-12 14:50
Hi @lehuy2012 ,

Sorry for late reply. I mean you can ask it from support@antmedia.io

**Closed** 2021-03-03 07:24 UTC
