### ISSUE TITLE
Iframe player not playing on iPhone or Android

### ISSUE THREAD

**Issue by samotage** [ant-media/Ant-Media-Server#3465] opened 2021-07-22 00:37 UTC
Hi,

Having the same issue, the iframe based player does not present the play button for ios and remains with "Stream will start playing automatically when it is live".

This is in both:
2.3.2
2.3.3.1

This was documented in issue 2924:
https://github.com/ant-media/Ant-Media-Server/issues/2924

The player works fine on OSX in Safari and Chrome.

I have tried modifying the play.html file as indicated above, commenting this condition out may not be correct, and indeed breaks the working player in the desktop browser.

Sam.

**Comment by cemklc** [comment] 2021-07-28 15:47
Hello, I am the developer assigned to this issue

Can you add "&autoplay=true" to the URL and try it again?

Like here
"<iframe width="560" height="315" src="https://your_domain_name:5443/LiveApp/play.html?name=123&autoplay=true" frameborder="0" allowfullscreen></iframe>"

**Comment by cemklc** [comment] 2021-07-29 11:02
Hi I am the developer that is assigned to this issue.

I tried to reproduce this issue but I was able to play the video with Iframe on both Android and Iphone device with the default play.html with Ant Media Server v2.3.3.1, I had to push the play button since it wasn't automatically starting.

The probable cause for this issue might be that the stream id on the iframe URL might be different that the broadcasting stream id.

Can you tell us a little more detail, a code piece that you use for iframe or add a screenshot perhaps?

**Comment by samotage** [comment] 2021-08-04 01:07
Perhaps this was some kind of iOs issue, as the problem went away after restarting Sarfai.  Still strange...

**Closed** 2021-08-04 01:39 UTC
