### ISSUE TITLE
Can’t create a Filter

### ISSUE THREAD

**Issue by Alex-Denysiuk** [ant-media/Ant-Media-Server#4793] opened 2023-02-02 15:19 UTC
### Short description

When I merge the video of a stream with the audio of another stream then I get a 500 code.

### Environment

* Operating system and version: ubuntu 20.04 LTS
* Java version: ?
* Ant Media Server version: 2.5.3
* Browser name and version: Firefox 109

### Steps to reproduce
1. ffmpeg -re -i 'BigBuckBunny.mp4'  -c:v libx264 -b:v 1600k -preset ultrafast -b 900k -c:a aac -b:a 128k -s 1920x1080 -x264opts keyint=50 -g 25 -pix_fmt yuv420p -f flv rtmp://localhost:5443/WebRTCAppEE/videoStream1
2. ffmpeg -re -i 'sample-15s.mp3' -acodec aac -strict experimental -ab 128k -ar 44100 -vn -f flv flv rtmp://localhost:5443/WebRTCAppEE/audioStream2
3. curl -i -X POST -H "Accept: Application/json" -H "Content-Type: application/json" "https://localhost:5443/WebRTCAppEE/rest/v2/filters/create" -d '{"filterId":"addAudio","inputStreams":["videoStream1","audioStream2"],"outputStreams":["test"],"videoFilter":"[in0]copy[out0]","audioFilter":"[in1]acopy[out0]","videoEnabled":"true","audioEnabled":"true"}'

This is the video I used http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4.
This is the audio I used https://download.samplelib.com/mp3/sample-15s.mp3. 

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

### Logs
2023-02-02 15:13:37,204 [https-jsse-nio2-0.0.0.0-5443-exec-9] ERROR o.a.c.c.C.[.[.0.0.0.[.[jersey-serlvet] - Servlet.service() for servlet [jersey-serlvet] in context with path [/WebRTCAppEE] threw exception [java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null
	at io.antmedia.filter.VideoDecoder.<init>(VideoDecoder.java:80)
	at io.antmedia.filter.FilterAdaptor.setVideoStreamInfo(FilterAdaptor.java:185)
	at io.antmedia.enterprise.webrtc.WebRTCApplication.addFrameListener(WebRTCApplication.java:429)
	at io.antmedia.filter.FilterAdaptor.createOrUpdateFilter(FilterAdaptor.java:404)
	at io.antmedia.plugin.FiltersManager.createFilter(FiltersManager.java:63)
	at io.antmedia.rest.FilterRestService.create(FilterRestService.java:44)
	at jdk.internal.reflect.GeneratedMethodAccessor184.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.ExpiresFilter.doFilter(ExpiresFilter.java:1230)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at io.antmedia.filter.IPFilter.doFilter(IPFilter.java:24)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at io.antmedia.filter.ContentSecurityPolicyHeaderFilter.doFilter(ContentSecurityPolicyHeaderFilter.java:32)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at io.antmedia.filter.JWTFilter.doFilter(JWTFilter.java:44)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:368)
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:698)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:367)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:639)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:882)
	at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1710)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1184)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:637)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:615)
	at org.apache.tomcat.util.net.SecureNio2Channel$1.completed(SecureNio2Channel.java:1008)
	at org.apache.tomcat.util.net.SecureNio2Channel$1.completed(SecureNio2Channel.java:936)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-02-02 15:13:47,923 [vert.x-worker-thread-27] INFO  i.a.e.adaptive.StreamAdaptor - Stream adaptor queue size: 2 for stream: videoStream1
2023-02-02 15:13:48,193 [RTMPConnectionExecutor-3] WARN  o.red5.server.net.rtmp.RTMPHandler - Not connected, closing connection
2023-02-02 15:13:48,193 [NioProcessor-13] INFO  o.r.s.stream.ClientBroadcastStream - Checking mux adaptor to stop audioStream1
2023-02-02 15:13:48,193 [NioProcessor-13] INFO  io.antmedia.muxer.MuxAdaptor - Calling stop for audioStream1 input queue size:6
2023-02-02 15:13:48,193 [NioProcessor-13] INFO  o.r.s.stream.ClientBroadcastStream - Mux Adaptor stop called audioStream1
2023-02-02 15:13:48,193 [NioProcessor-13] INFO  i.a.e.webrtc.WebRTCApplication - W3C x-category:stream x-event:unpublish c-ip:217.196.161.145 cs-bytes:317704 sc-bytes:3587 x-sname:f91adc27-dd10-4089-9699-696fd246a094 x-file-length:19 x-name:audioStream1
2023-02-02 15:13:48,194 [NioProcessor-13] INFO  i.a.e.webrtc.WebRTCApplication - W3C x-category:session x-event:disconnect c-ip:217.196.161.145 c-client-id:59
2023-02-02 15:13:48,195 [vert.x-worker-thread-49] WARN  io.antmedia.muxer.MuxAdaptor - closing adaptor for audioStream1 
2023-02-02 15:13:48,195 [vert.x-worker-thread-49] INFO  io.antmedia.muxer.MuxAdaptor - close resources for streamId -> audioStream1
2023-02-02 15:13:48,195 [vert.x-worker-thread-49] INFO  io.antmedia.muxer.MuxAdaptor - Cancelling packet poller task(id:2495) for streamId: audioStream1
2023-02-02 15:13:48,196 [vert.x-worker-thread-49] INFO  io.antmedia.muxer.Mp4Muxer - writing trailer for stream: audioStream1
2023-02-02 15:13:48,196 [vert.x-worker-thread-49] INFO  io.antmedia.muxer.HLSMuxer - writing trailer for stream: audioStream1
2023-02-02 15:13:48,197 [vert.x-worker-thread-17] INFO  io.antmedia.muxer.Mp4Muxer - audioStream1-2023-02-02_15-13-28.833.mp4 is ready
2023-02-02 15:13:48,197 [vert.x-worker-thread-49] INFO  io.antmedia.muxer.HLSMuxer - Delete File onexit:true upload to S3:true stream:audioStream1 hls time:2 hlslist size:5
2023-02-02 15:13:48,197 [vert.x-worker-thread-49] INFO  i.a.e.adaptive.EncoderAdaptor - closing input and number of dropped packets 0
2023-02-02 15:13:48,197 [vert.x-worker-thread-49] INFO  i.a.e.adaptive.EncoderAdaptor - Total video encode time 0ms, average video encode time 0ms total audio encode time 42ms total video decode time 0ms , average video decode time 0 ms 
2023-02-02 15:13:48,197 [vert.x-worker-thread-49] WARN  io.antmedia.muxer.MuxAdaptor - closed adaptor for audioStream1
2023-02-02 15:13:48,199 [vert.x-worker-thread-17] WARN  i.a.datastore.db.MapBasedDataStore - VoD is saved to DB audioStream1-2023-02-02_15-13-28.833.mp4 with voID oa5KWaKKCLAZXNBPFiKNgiBT
2023-02-02 15:13:48,199 [vert.x-worker-thread-17] INFO  io.antmedia.muxer.Mp4Muxer - File: /usr/local/antmedia/webapps/WebRTCAppEE/streams/audioStream1-2023-02-02_15-13-28.833.mp4.tmp_extension exist: false
2023-02-02 15:13:48,199 [vert.x-worker-thread-17] INFO  i.a.AntMediaApplicationAdapter - Closing broadcast stream id: audioStream1
2023-02-02 15:13:48,207 [vert.x-worker-thread-59] INFO  i.a.e.adaptive.StreamAdaptor - Recording set to false in streamadaptor: 1722172535 for stream: audioStream1 stopping scheduler job id: 2499
2023-02-02 15:13:48,208 [vert.x-worker-thread-59] INFO  i.a.e.adaptive.StreamAdaptor - Flushing audio encoder:aac for stream adaptor:1722172535 stream id:audioStream1
2023-02-02 15:13:48,209 [vert.x-worker-thread-59] ERROR i.a.e.adaptive.audio.OpusEncoder - Cannot send audio frame to encoder for stream index 0 error is End of file for stream:audioStream1
2023-02-02 15:13:48,209 [vert.x-worker-thread-59] INFO  i.a.e.adaptive.StreamAdaptor - Flushing audio encoder:libopus for stream adaptor:1722172535 stream id:audioStream1
2023-02-02 15:13:48,209 [vert.x-worker-thread-59] INFO  io.antmedia.muxer.Mp4Muxer - writing trailer for stream: audioStream1
2023-02-02 15:13:48,210 [vert.x-worker-thread-59] INFO  io.antmedia.muxer.HLSMuxer - writing trailer for stream: audioStream1
2023-02-02 15:13:48,210 [vert.x-worker-thread-48] INFO  io.antmedia.muxer.Mp4Muxer - audioStream1-2023-02-02_15-13-31.848.mp4 is ready
2023-02-02 15:13:48,210 [vert.x-worker-thread-59] INFO  io.antmedia.muxer.HLSMuxer - Delete File onexit:true upload to S3:true stream:audioStream1 hls time:2 hlslist size:5
2023-02-02 15:13:48,210 [vert.x-worker-thread-59] INFO  i.a.e.adaptive.audio.AACEncoder - writing trailer codec name: aac bitrate:96000 for stream:audioStream1
2023-02-02 15:13:48,210 [vert.x-worker-thread-59] INFO  i.a.e.adaptive.audio.AACEncoder - Total processing time 601, Average processing time 0 ms per frame on average for stream:audioStream1
2023-02-02 15:13:48,210 [vert.x-worker-thread-59] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - unregistering audioStream1 muxer with 0p and codec: NoCodec from webrtc adaptor
2023-02-02 15:13:48,211 [vert.x-worker-thread-59] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Decreasing number of live streams: 10 and stream id:audioStream1
2023-02-02 15:13:48,211 [vert.x-worker-thread-59] INFO  i.a.enterprise.webrtc.WebRTCMuxer - Average write packet call interval: 17ms average audio processing time: 0ms  audio packet count: 961 for stream:audioStream1
2023-02-02 15:13:48,211 [vert.x-worker-thread-59] INFO  i.a.e.adaptive.audio.OpusEncoder - writing trailer codec name: libopus bitrate:96000 for stream:audioStream1
2023-02-02 15:13:48,211 [vert.x-worker-thread-59] INFO  i.a.e.adaptive.audio.OpusEncoder - Total processing time 2069, Average processing time 1 ms per frame on average for stream:audioStream1
2023-02-02 15:13:48,211 [vert.x-worker-thread-59] INFO  i.a.e.adaptive.StreamAdaptor - Average thread entrance interval 9ms for stream: audioStream1
2023-02-02 15:13:48,211 [vert.x-worker-thread-59] INFO  i.a.e.adaptive.StreamAdaptor - Leaving streamadaptor: 1722172535 for stream: audioStream1
2023-02-02 15:13:48,211 [vert.x-worker-thread-48] WARN  i.a.datastore.db.MapBasedDataStore - VoD is saved to DB audioStream1-2023-02-02_15-13-31.848.mp4 with voID pOSyUmuuYDK3aZgRxGVEVsII
2023-02-02 15:13:48,211 [vert.x-worker-thread-48] INFO  io.antmedia.muxer.Mp4Muxer - File: /usr/local/antmedia/webapps/WebRTCAppEE/streams/audioStream1-2023-02-02_15-13-31.848.mp4.tmp_extension exist: false
2023-02-02 15:14:02,341 [vert.x-worker-thread-28] INFO  i.a.e.adaptive.StreamAdaptor - Stream adaptor queue size: 2 for stream: videoStream1
2023-02-02 15:14:17,150 [vert.x-worker-thread-11] INFO  i.a.e.adaptive.StreamAdaptor - Stream adaptor queue size: 2 for stream: videoStream1
2023-02-02 15:14:31,981 [vert.x-worker-thread-28] INFO  i.a.e.adaptive.StreamAdaptor - Stream adaptor queue size: 2 for stream: videoStream1

Join [community.antmedia.io](https://community.antmedia.io) and be a part of Ant Media Server Community.

**Comment by mekya** [comment] 2023-02-06 10:50
Thank you for raising this issue @Alex-Denysiuk,

Let us confirm the problem.

**Comment by USAMAWIZARD** [comment] 2023-02-08 18:53
the behavior is really strange This is what I found out after after doing some testing 

1. if stream1 and stream2 both contains audio and video and I am sending the request to merge the video of first stream with the audio of second stream it will only work first time  that mean If I again publish another two streams and try to merge their video to audio it will fail with message {"success":false,"message":null,"dataId":null,"errorId":0}

**Comment by USAMAWIZARD** [comment] 2023-02-08 19:05
I was able to reproduce the problem at my end here are the logs 
[filterlogs.zip](https://github.com/ant-media/Ant-Media-Server/files/10689080/filterlogs.zip)

I also noticed some other strange behavior if I send in total 2 streams (both containing audio video ) and call the api to merge the stream it works first time. and if I again  send two more streams and again try to call the API it always fails that means this api only works first time

**Comment by mekya** [comment] 2023-02-27 08:31
thank you @USAMAWIZARD

**Comment by lastpeony** [comment] 2023-04-06 10:53
I was able to successfully merge video and audio using the latest versions of the master branches on Ubuntu 20.04. The ffmpeg commands mentioned earlier may be outdated and could cause issues.

Here are the ffmpeg commands I used:

ffmpeg  Video command:
`ffmpeg -re -i 'BigBuckBunny.mp4' -c:v libx264 -b:v 1600k -preset ultrafast -b 900k -c:a aac -b:a 128k -s 1920x1080 -x264opts keyint=50 -g 25 -pix_fmt yuv420p -f flv rtmp://localhost:1935/WebRTCAppEE/videoStream1`
ffmpeg  sound not looping command:
`ffmpeg -re -i 'sample-15s.mp3' -c:a aac -strict experimental -b:a 128k -ar 44100 -vn -f flv "rtmp://localhost:1935/WebRTCAppEE/audioStream2"`
ffmpeg  sound looping command:
`ffmpeg -re -stream_loop -1 -i "sample-15s.mp3" -c:a aac -strict experimental -b:a 128k -ar 44100 -vn -f flv "rtmp://localhost:1935/WebRTCAppEE/audioStream2"`

Curl command executed from windows OS:
`curl -i -X POST -H "Accept: application/json" -H "Content-Type: application/json" -d "{\"filterId\":\"addAudio\",\"inputStreams\":[\"videoStream1\",\"audioStream2\"],\"outputStreams\":[\"test\"],\"videoFilter\":\"[in0]copy[out0]\",\"audioFilter\":\"[in1]acopy[out0]\",\"videoEnabled\":true,\"audioEnabled\":true}" "http://localhost:5080/WebRTCAppEE/rest/v2/filters/create"`

![image](https://user-images.githubusercontent.com/24750845/230355739-32cca997-80d5-4dc1-ae87-7821ce7197eb.png)

I was able to play merged stream. Audio was merged and stream was fine.

**Comment by mekya** [comment] 2023-04-10 08:22
Hi @lastpeony,
In order to confirm that this issue has been resolved, did you reproduce the problem in version 2.5.3 because @Alex-Denysiuk mentions that this problem is happening in v2.5.3

Regards
Oguz

**Comment by lastpeony** [comment] 2023-04-17 09:33
Problem is reproduced on 2.5.3 but fixed on 2.6.0 snapshot. 
You can test with this build:
https://drive.google.com/file/d/1rUFZigV15HNnGj-1VbxtdxnPqKv0_YxP/view?usp=share_link
I am closing this issue. Feel free to re-open.

**Closed by lastpeony** 2023-04-17 09:33 UTC
Labels: support
