### ISSUE TITLE
already_playing errors when trying sync streams in a multitrack conference

### ISSUE THREAD

**Issue by kpsarthi** [ant-media/Ant-Media-Server#4603] opened 2022-11-22 19:38 UTC
We regularly get streams missing in a multitrack conference. We poll for the tracks similarly as done in the sample 

> WebRTCAppEE/multitrack-conference.html

 using getRoomInfo. We get already playing errors (already_playing) when trying to play tracks that are not playing. I tried first to stop the stream (subtrack in the multitrack stream) using 

`webrtcAdapter.stop(streamId);` 

However, this also doesn't resolve the issue, when we concurrently join 4-5 users in the conference. I was looking in the documentation, but couldn't find any reference using which we can first check the status of the stream before playing it. 

Any help or suggestion here is appreciated.

Thanks.

**Comment by mekya** [comment] 2022-11-28 10:51
Thank you @kpsarthi for the issue. Moving to the backlog to schedule.

**Comment by burak-58** [comment] 2022-12-24 10:13
The root cause for the missing participants issue is investigated and fixed. Because of the fixed issue, enabling the missing track can not solve the missing participant problem.

**Comment by mekya** [comment] 2023-05-22 16:27
So I'm closing this issue for now.

Please feel free to open if it does not work for you

**Closed by mekya** 2023-05-22 16:27 UTC
Labels: Priority: Important
