### ISSUE TITLE
Live stream status still broadcasting when no data is being sent

### ISSUE THREAD

**Issue by timantmedia** [ant-media/Ant-Media-Server#5277] opened 2023-06-21 13:19 UTC
### Short description
The issue is only being reported in Kubernetes environment. This cannot be reproduced on standalone. 

When pushing over 20 RTMP live streams using a automated shell script and then either stopped via cancelling the terminal process, sending an API stop request or when the live streams MKV source file has finished, sometimes random live streams are still in broadcasting status. 

The database confirms that the status is also still set at broadcasting even though nothing is being sent to that live stream. 

Trying to change the status manually in the database results in the following error when attempting to resume pushing a RTMP stream:

```
2023-06-16 08:08:39,824 [RTMPConnectionExecutor-1] INFO  i.a.s.AcceptOnlyStreamsWithWebhook - AcceptOnlyStreamsWithWebhook is not activated for stream stream_rtmp_7047d984-1caa-4868-8d1e-a55766fa8130
2023-06-16 08:08:39,827 [RTMPConnectionExecutor-1] ERROR o.red5.server.stream.StreamService - Bad name stream_rtmp_7047d984-1caa-4868-8d1e-a55766fa8130
```

**The issue is also not experienced when there are less than 20 live streams active.** 

### Environment

* Kubernetes on Vultr
* Ant Media Server version: 2.5.3

### Steps to reproduce
1. Install Ant Media Server in Kubernetes on Vultr hosting
2. Create 20+ lives streams using the API
3. Create a shell script that pushes a MKV file as RTMP to the created live streams
4. Cancel the terminal process and wait for the live streams to stop
5. Notice that not all live streams status are offline, some are still in broadcasting and the database also reflects this status as broadcasting.

### Expected behavior
When cancelling the terminal process or calling the API endpoint to stop the live stream, the live stream should stop and status should be offline.

### Actual behavior
The live stream is still showing as broadcasting in both the web panel and database and errors are triggered when trying to start the live stream again. 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

FD 94146

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by mekya** [comment] 2023-06-22 07:27
Thank you for the report @timantmedia 

Shall we have the same MKV file because that file may have different encoder parameters?

**Comment by timantmedia** [comment] 2023-06-22 09:15
@mekya ok yes, you're right, I didn't think of it. I'll ask.

**Comment by oleul05** [comment] 2023-06-22 10:43
@mekya and @timantmedia,
Following are the video files link
https://drive.google.com/file/d/1eea8FeOaZXivR5-FB14FblFwJLugLtkN/view?usp=sharing
and following are the sample script file to push 20 streams at the same time to AMS RTMP server
https://drive.google.com/file/d/1yN-Swz_ZRvNMpdwGdrLpPiRXvUx71qm-/view?usp=sharing

**Comment by mekya** [comment] 2023-06-26 05:34
Thank you I'll try on my end and share the result with you.

**Comment by timantmedia** [comment] 2023-07-03 10:49
@mekya did you manage to reproduce this on your side?

**Comment by mekya** [comment] 2023-07-05 07:08
Thank you for follow up @timantmedia.

I plan to reproduce it today and provide you some feedbacks. 

Cheers

**Comment by mekya** [comment] 2023-07-05 09:22
Hi @oleul05,
I've just had a quick analyse of the issue and check the files.

This script - above is also available below- sends 20 streams and it totally sends 1200 * 20 streams in the for loop. 
```
#!/bin/bash

for ((i=1; i<=1200; i++))
do
    ffmpeg -re -i demo.mkv -codec copy -f flv rtmp://domain/WebRTCAppEE/stream_rtmp_1 &
    sleep 10s
    ffmpeg -re -i demo.mkv -codec copy -f flv rtmp://domain/WebRTCAppEE/stream_rtmp_2 &
    sleep 10s
    ffmpeg -re -i demo.mkv -codec copy -f flv rtmp://domain/WebRTCAppEE/stream_rtmp_3 &
    sleep 10s
    ffmpeg -re -i demo.mkv -codec copy -f flv rtmp://domain/WebRTCAppEE/stream_rtmp_4 &
    sleep 10s
    ffmpeg -re -i demo.mkv -codec copy -f flv rtmp://domain/WebRTCAppEE/stream_rtmp_5 &
    sleep 10s
    ffmpeg -re -i demo.mkv -codec copy -f flv rtmp://domain/WebRTCAppEE/stream_rtmp_6 &
    sleep 10s
    ffmpeg -re -i demo.mkv -codec copy -f flv rtmp://domain/WebRTCAppEE/stream_rtmp_7 &
    sleep 10s
    ffmpeg -re -i demo.mkv -codec copy -f flv rtmp://domain/WebRTCAppEE/stream_rtmp_8 &
    sleep 10s
    ffmpeg -re -i demo.mkv -codec copy -f flv rtmp://domain/WebRTCAppEE/stream_rtmp_9 &
    sleep 10s
    ffmpeg -re -i demo.mkv -codec copy -f flv rtmp://domain/WebRTCAppEE/stream_rtmp_10 &
    sleep 10s
    ffmpeg -re -i demo.mkv -codec copy -f flv rtmp://domain/WebRTCAppEE/stream_rtmp_11 &
    sleep 10s
    ffmpeg -re -i demo.mkv -codec copy -f flv rtmp://domain/WebRTCAppEE/stream_rtmp_12 &
    sleep 10s
    ffmpeg -re -i demo.mkv -codec copy -f flv rtmp://domain/WebRTCAppEE/stream_rtmp_13 &
    sleep 10s
    ffmpeg -re -i demo.mkv -codec copy -f flv rtmp://domain/WebRTCAppEE/stream_rtmp_14 &
    sleep 10s
    ffmpeg -re -i demo.mkv -codec copy -f flv rtmp://domain/WebRTCAppEE/stream_rtmp_15 &
    sleep 10s
    ffmpeg -re -i demo.mkv -codec copy -f flv rtmp://domain/WebRTCAppEE/stream_rtmp_16 &
    sleep 10s
    ffmpeg -re -i demo.mkv -codec copy -f flv rtmp://domain/WebRTCAppEE/stream_rtmp_17 &
    sleep 10s
    ffmpeg -re -i demo.mkv -codec copy -f flv rtmp://domain/WebRTCAppEE/stream_rtmp_18 &
    sleep 10s
    ffmpeg -re -i demo.mkv -codec copy -f flv rtmp://domain/WebRTCAppEE/stream_rtmp_19 &
    sleep 10s
    ffmpeg -re -i demo.mkv -codec copy -f flv rtmp://domain/WebRTCAppEE/stream_rtmp_20 &
    sleep 10s
done
```

The problem is that it sends the same stream id in each loop so the server reports that bad naming. It's an expected behaviour. Because server checks that there is an active with the same stream id and does not accept another stream having the same stream id.  

>2023-06-16 08:08:39,827 [RTMPConnectionExecutor-1] ERROR o.red5.server.stream.StreamService - Bad name stream_rtmp_7047d984-1caa-4868-8d1e-a55766fa8130

**Comment by oleul05** [comment] 2023-07-11 06:10
@mekya Thank you for your time on the above issue.
In the following files we have 20 streams. The demo.mkv file duration is 12 minutes long. With the below files it will start stream_rtmp_1 first then wait for 10 seconds and after 10 seconds it will start stream_rtmp_2 and so on.
For better understanding if we have if we create 20 shell script file for 20 streams like following that will run stream_rtmp_1 for 12 minutes then wait for 10 seconds and then start stream_rtmp_1 streams again and stream_rtmp_1 stream will restart 1200 times. I have tried to start 100 streams with 100 shell scripts files like below.
For example after restarting 120 times for streamId ‘stream_rtmp_35’ we observed stream status remains broadcasting instead of finished. When we check from terminal we found that stream has stopped from terminal. For some streams it can restart about 80th time successfully and when it’s stopped on 81th time we found the streams status doesn’t change. The number 80 or 81 is the random number. It can be 35, 250 or 600.
script1.sh
!/bin/bash
for ((i=1; i<=1200; i++))
do
    ffmpeg -re -i demo.mkv -codec copy -f flv rtmp://domain/WebRTCAppEE/stream_rtmp_1 &
    sleep 10s
done
script2.sh
!/bin/bash
for ((i=1; i<=1200; i++))
do
    ffmpeg -re -i demo.mkv -codec copy -f flv rtmp://domain/WebRTCAppEE/stream_rtmp_1 &
    sleep 10s
done

**Comment by timantmedia** [comment] 2023-07-11 10:04
@oleul05 if you are running this locally in your terminal, can you check if the FFMPEG process is still running when you experience this issue? It can be that the terminal commands appear stopped, but the process is still running in the background. 

Did you try with @mekya recommendation? Are you saying that you still experience the issue with the recommended shell script format?

**Comment by oleul05** [comment] 2023-07-11 11:02
@timantmedia I have also tried with killing ffmpeg from terminal and confirmed ffmpeg was not running in background. And also status broadcasting remains for unlimited time until I change it manually from database.

**Comment by oleul05** [comment] 2023-07-12 08:22
Hello @timantmedia, 
The script should be like following:

> !/bin/bash
> for ((i=1; i<=1200; i++))
>   do
>   ffmpeg -re -i demo.mkv -codec copy -f flv rtmp://localhost:5080/WebRTCAppEE/stream_rtmp &
>   sleep 10s
> done

There shouldn't be _${i} in the name. As the our input source duration is 12 minutes so ffmpeg command will run 12 minutes in the background and when streams finished it will wait for 10 seconds and again starts the same streams with the same streamId 1200 times.
When we run 100 similar shell script with different streamId for example stream_rtmp_2, stream_rtmp_3 and so on when we observed at least 1 live stream status is not correctly reflected. 
Yes this is only happening in cluster mode, not standalone mode.

**Comment by timantmedia** [comment] 2023-07-13 16:59
@oleul05 

I do not fully understand your statement below. Could you explain in more detail?

`As the our input source duration is 12 minutes so ffmpeg command will run 12 minutes in the background and when streams finished it will wait for 10 seconds and again starts the same streams with the same streamId 1200 times.`

I do not think it will wait until the first FFMPEG process is finished, plus the 10 seconds sleep before attempting to start another live stream with the same name. It looks like it will start an FFMPEG process, sleep for 10 seconds and then start another regardless of whether the previous FFMPEG process has finished or not. 

@mekya correct me if I am wrong, but the shell script @oleul05 has provided appears to attempt to start the same live stream many times and is likely to fail.

**Comment by mekya** [comment] 2023-08-01 10:16
Hi @oleul05 

I agree on the comment by @timantmedia 

> I do not think it will wait until the first FFMPEG process is finished, plus the 10 seconds sleep before attempting to start another live stream with the same name. It looks like it will start an FFMPEG process, sleep for 10 seconds and then start another regardless of whether the previous FFMPEG process has finished or not.

Just remove the `&` at the end of ffmpeg command like below. 

```bash
!/bin/bash
for ((i=1; i<=1200; i++))
do
ffmpeg -re -i demo.mkv -codec copy -f flv rtmp://localhost:5080/WebRTCAppEE/stream_rtmp 
sleep 10s
done 
```

The script above should work the way you mention below

>As the our input source duration is 12 minutes so ffmpeg command will run 12 minutes in the background and when streams finished it will wait for 10 seconds and again starts the same streams with the same streamId 1200 times.

**Comment by mekya** [comment] 2023-09-18 11:55
It's moved to after sprint to confirm with memory leak issue

**Comment by mekya** [comment] 2023-10-23 11:55
Hi 
I'm closing this issue because we've implemented solution for this problem.

Please check it and feel free to re-open if it does not work for you

Cheers

**Closed by mekya** 2023-10-23 11:55 UTC
Labels: bug
