### ISSUE TITLE
Add conference room maximum participant capacity

### ISSUE THREAD

**Issue by lastpeony** [ant-media/Ant-Media-Server#5723] opened 2023-10-23 19:06 UTC
Add conference room maximum participant capacity so that number of participants in conference room can be limited.

**Comment by timantmedia** [comment] 2023-11-07 11:55
@mekya @lastpeony there is a significant opportunity with this feature. A customer from FD 108089 confirmed that once the feature is available, they expect scaling to between 10k-20k publishers with 100-200 viewers per publisher.

**Comment by sumit-anantwar** [comment] 2024-02-21 10:01
@mekya @lastpeony @timantmedia 
The tourist season starts in March, and we need this feature urgently.
We are holding our major release because of this.
Please let us know when this will be available.

Implementing this doesn't seem difficult.
If you want, we can also provide you with development support.

**Comment by mekya** [comment] 2024-05-06 13:53
Hi @sumit-anantwar,

We've missed this message. It's my bad. 

If this is something still on the table, let's have a quick discussion and proceed. You can connect directly with contact@antmedia.io to speed up the process. 

Cheers
Oguz

**Comment by sumit-anantwar** [comment] 2024-05-06 13:57
@mekya Yes, we are still waiting for the implementation.
Let me know when you want to schedule the call.

**Comment by sumit-anantwar** [comment] 2024-05-06 14:55
Will do, talk to you tomorrow then,
thank you!

**Comment by mekya** [comment] 2024-05-06 15:23
Thank you, talk to you tomorrow :)

My pleasure

**Comment by mekya** [comment] 2024-05-07 09:02
Hi @sumit-anantwar ,

I'm waiting for you here
https://meet.google.com/zhh-pdjm-vac

Cheers

**Comment by mekya** [comment] 2024-05-17 06:36
Hi @sumit-anantwar,

I've refactored and merged the PR for max participant limit for conference. 

I'm happy to make a PoC to you and proceed to next steps. 

Cheers
Oguz

**Comment by sumit-anantwar** [comment] 2024-05-17 08:18
Hey @mekya 
That's a great news. 
Let me know when it's ready. 
Please also provide instructions how to deploy it on AWS

**Closed** 2024-05-27 10:35 UTC

**Comment by sumit-anantwar** [comment] 2024-06-12 22:31
@mekya 
Please let us know if the image ia now available on AWS.
Also, please provide the WebSocket API reference.

Best,
Sumit

**Comment by mekya** [comment] 2024-06-24 07:10
Hi @sumit-anantwar,

Unfortunately, it's not ready. We'll make a release hopefully in this week in the following issue
https://github.com/ant-media/Ant-Media-Server/issues/6423

Btw, [reach out to me on LinkedIn](https://www.linkedin.com/in/ahmetoguzmermerkaya/) to have faster responses 

Cheers
Oz
