### ISSUE TITLE
Rotated live stream video from iPhone browser and Android app

### ISSUE THREAD

**Issue by salsaweb** [ant-media/Ant-Media-Server#3614] opened 2021-09-08 13:38 UTC
### Short description
WebRTC stream from mobile examples and from web examples from iPhone are rotated in hls

### Environment
* Latest WebRTC Android SDK
* Ant Media Server version: Enterprise Edition 2.2.1 20201029_2042
* Browser name and version: Chrome Version 93.0.4577.63 (Official Build) (x86_64)

### Steps to reproduce
1. open in iPhone browser (safari, chrome) https://mydomain.com/WebRTCAppEE/ and publish broadcast in portrait mode
2. open in laptop browser https://mydomain.com/WebRTCAppEE/play.html?name=stream1&playOrder=hls it's important to set playOrder to HLS

### Expected behavior
Watch stream in portrait mode

### Actual behavior
Stream is rotated for 90 degrees

**Comment by mekya** [comment] 2021-09-10 12:26
hi @salsaweb 

Thank you for the issue. It's a known issue. These browsers send streams with rotated value and HLS players does not support rotate value. Maybe we can customize HLS player further to rotate the video. 

Let me put it to the backlog

**Comment by mekya** [comment] 2021-09-10 12:28
Quick workaround solution for this is adding adaptive bitrate. But it's not performance efficient.

**Comment by mekya** [comment] 2024-03-27 08:26
Hi @salsaweb 
The problem is being fixed with this issue
https://github.com/ant-media/Ant-Media-Server/issues/6099

FYI

**Closed** 2024-04-01 10:43 UTC
