### ISSUE TITLE
Live video recording freezes when we play after live ends 

### ISSUE THREAD

**Issue by Vaibhav-Agarwal06** [ant-media/Ant-Media-Server#4806] opened 2023-02-07 17:26 UTC
We are having issues with the Front and Back camera on Mobile Live Playback.

When going Live on a mobile phone and switching from Front camera view to Back camera view while live streaming, After stream is ended it freezes the video but the audio still plays when you watch the Live playback. It never shows the Back camera view when playing back the recorded live.

**Comment by yashtandon113** [comment] 2023-04-24 11:11
Hi @Vaibhav-Agarwal06 
I attempted to replicate the stated problem, but I did not encounter the specified problem. Let me explain my reproduce scenario:

1. Stream was published on a mobile browser using a sample web page (https://domain:5443/LiveApp).
2. Watch the stream in desktop browser
3. Several times switched between front and rear cameras
4. Play the recorded stream.

The broadcast was successfully terminated, and the back camera view is visible in the recorded stream.

Please let me know if there was anything I missed while duplicating the problem.

**Comment by Vaibhav-Agarwal06** [comment] 2023-04-24 11:19
@yashtandon113 : Thanks for considering the problem.

I go live using iPhone and switch the camera back/front during live streaming. Recorded video is not playing back camera video and its freezes but audio is playing fine.

Please let me know if you need more info.

**Comment by yashtandon113** [comment] 2023-05-01 11:56
@Vaibhav-Agarwal06 
Could you please upgrade your AMS to version 2.5.3? Please see the document below to upgrade your server.
https://antmedia.io/docs/guides/upgrading-ant-media-server/

If the problem persists, we can investigate further.

**Comment by yashtandon113** [comment] 2023-05-08 11:14
@Vaibhav-Agarwal06 
I am closing this issue. If you have any questions or if the problem is reproducible on v2.5.3 as well, please feel free to reopen the issue.

**Closed by yashtandon113** 2023-05-08 11:14 UTC
Labels: support, to-validate
