### ISSUE TITLE
webrtc player does not work on puffin browser

### ISSUE THREAD

**Issue by vinceaar0n** [ant-media/Ant-Media-Server#1305] opened 2019-06-07 14:12 UTC
Webrtc player does not work on puffin browser

no video or audio on puffin browsers for desktop, android and ios

* Operating system and version: windows 10, android, ios
* Ant Media Server version: ant media server enterprise 
* Browser name and version: puffin browsers *

**Comment by mekya** [comment] 2019-06-07 15:23
Hi,

I had a quick check about puffin browser. 
I couldn't find any useful information about it support webrtc or not

https://caniuse.com/#search=webrtc
https://en.wikipedia.org/wiki/Comparison_of_web_browsers

Its  usage probably is very less than %1.

Are you sure puffin supports WebRTC? 

Regards,

**Comment by vinceaar0n** [comment] 2019-06-07 15:26
> Hi,
> 
> I had a quick check about puffin browser.
> I couldn't find any useful information about it support webrtc or not
> 
> https://caniuse.com/#search=webrtc
> https://en.wikipedia.org/wiki/Comparison_of_web_browsers
> 
> Its usage probably is very less than %1.
> 
> Are you sure puffin supports WebRTC?
> 
> Regards,

yes im using wowza ull with it.

**Comment by mekya** [comment] 2019-06-07 16:06
Maybe it does not support h264 for WebRTC. Ant Media Server supports H264 for WebRTC.  
Can you send me the console log of puffin browser while you are publishing/playing with puffin?

**Comment by vinceaar0n** [comment] 2019-06-07 16:10
> Maybe it does not support h264 for WebRTC. Ant Media Server supports H264 for WebRTC.
> Can you send me the console log of puffin browser while you are publishing/playing with puffin?

log: websocket connected

log: initialized

log: sent message:{"command":"getStreamInfo","streamId":"266135020412091690242059"}

log: stream information

log: sent message:{"command":"play","streamId":"266135020412091690242059","token":"235282494127506061406881"}

log: received remote description type for stream id: 266135020412091690242059 type: offer

log: stream id in init peer connection: 266135020412091690242059 close dstream id: 266135020412091690242059

log: onTrack

log: Received remote stream

log: onTrack

log: try to create answer for stream id: 266135020412091690242059

log: Candidate is added for stream 266135020412091690242059

log: Candidate is added for stream 266135020412091690242059

log: created answer for stream id: 266135020412091690242059

log: sent message:{"command":"takeConfiguration","streamId":"266135020412091690242059","type":"answer","sdp":"v=0\r\no=- 8138655162448946206 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE audio video\r\na=msid-semantic: WMS\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 110\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:EA0C\r\na=ice-pwd:e9ifcAOZX8JlKxRloVo3XROA\r\na=ice-options:trickle\r\na=fingerprint:sha-256 C2:7B:22:9E:E1:6D:D5:BF:43:EB:70:00:3A:28:DF:B6:4A:C8:DB:30:C9:6C:0C:EC:AA:38:62:E7:D7:6A:1E:76\r\na=setup:active\r\na=mid:audio\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=recvonly\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:110 telephone-event/48000\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:EA0C\r\na=ice-pwd:e9ifcAOZX8JlKxRloVo3XROA\r\na=ice-options:trickle\r\na=fingerprint:sha-256 C2:7B:22:9E:E1:6D:D5:BF:43:EB:70:00:3A:28:DF:B6:4A:C8:DB:30:C9:6C:0C:EC:AA:38:62:E7:D7:6A:1E:76\r\na=setup:active\r\na=mid:video\r\na=extmap:2 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:4 urn:3gpp:video-orientation\r\na=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=recvonly\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 H264/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:98 red/90000\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:100 ulpfec/90000\r\n"}

log: Candidate is added for stream 266135020412091690242059

log: Candidate is added for stream 266135020412091690242059

log: play started

**Comment by vinceaar0n** [comment] 2019-06-07 18:01
also seems to be a problem with enable_ssl.sh at first i was getting error directory or file does not exist for 
"/etc/letsencrypt/live/$domain/fullchain.pem"
"/etc/letsencrypt/live/$domain/privkey.pem"

i tried manuall creating the directory but still the sameso i tried creating empty files it continued but now im getting 

"IMPORTANT NOTES: - The following errors were reported by the server:
   Domain: test.vincesolutions.net   Type:   unauthorized   Detail: Invalid response from   http://test.vincesolutions.net/.well-known/acme-challenge/mCC_PUUC7bOFfvY33KHTjPxofVWIEW8vGFnDEC0CEmo   [2606:4700:30::681b:be97]: "<!doctype html><html   lang=\"en\"><head><title>HTTP Status 404 – Not Found</title><style   type=\"text/css\">h1 {font-family:Tahoma,A"
   To fix these errors, please make sure that your domain name was   entered correctly and the DNS A/AAAA record(s) for that domain   contain(s) the right IP address.There is a problem in installing SSL to Ant Media Server. Please take a look at the logs above and try to fix. If you do not have any idea, contact@antmedia.io"    On Saturday, June 8, 2019, 12:06:29 AM GMT+8, Ahmet Oğuz Mermerkaya <notifications@github.com> wrote:  
 
 
Maybe it does not support h264 for WebRTC. Ant Media Server supports H264 for WebRTC.
Can you send me the console log of puffin browser while you are publishing/playing with puffin?

**Comment by vinceaar0n** [comment] 2019-06-07 18:39
found the problem had to remove PREROUTING rules in iptables.you guys need to improve documentation alot
but still https:// 5443 still does not work This site can’t be reached 51.79.20.190 took too long to respond.

    On Saturday, June 8, 2019, 12:06:29 AM GMT+8, Ahmet Oğuz Mermerkaya <notifications@github.com> wrote:  
 
 
Maybe it does not support h264 for WebRTC. Ant Media Server supports H264 for WebRTC.
Can you send me the console log of puffin browser while you are publishing/playing with puffin?

**Comment by vinceaar0n** [comment] 2019-06-09 13:36
upon checking puffin supports H264

**Comment by mekya** [comment] 2019-06-10 05:44
It seems that configuration is ok for codec and messaging. 

It may have some problem in rendering or ports. UDP ports are open for your instance?

Regards

**Comment by vinceaar0n** [comment] 2019-06-10 07:24
yes they are open

**Comment by mekya** [comment] 2019-06-10 09:11
Then which android device do you use?

I'm going to try this https://play.google.com/store/apps/details?id=com.cloudmosa.puffinFree

is it ok?

**Comment by vinceaar0n** [comment] 2019-06-10 15:00
yeps thats it. im using both pro and free

**Comment by vinceaar0n** [comment] 2019-06-20 08:44
has there been any updates regarding this?

**Comment by mekya** [comment] 2019-06-21 07:53
Yeah I acknowledged that there is a problem with that.

My first investigations does not help understand the problem. It's my quick
todo list. I hope I can provide something in a couple of days.

**Comment by mekya** [comment] 2019-06-29 13:58
Hi @vinceaar0n ,

I've just checks some more things about puffin. 

Actually it does not work for publishing in youtube as well. The main problem for your side is on playing. To be honest, I could not even make a peer to peer connection in puffin.
I've testes several things other than our solution such as https://webrtc.github.io/samples/

Because puffin is a remote browser and website on our desktop are actually rendered in remote servers. I think this is the reason. 

I think if puffin is working with WebRTC, then the issue may be about codec compatibility. Because Ant Media Server supports h264 and puffin cloud servers should support H.264 for WebRTC to be compatible with Ant Media Server streams. 

Anyway, could you give a link that I can see puffin is working with WebRTC?

Lastly, do you think it is feasible for you to play stream with HLS or something in puffin browser?

**Comment by vinceaar0n** [comment] 2019-06-29 14:06
The delay for hls is to long. The sample with hls fallback does not also work.

Sent from Yahoo Mail on Android 
 
  On Sat, 29 Jun 2019 at 9:58 PM, Ahmet Oğuz Mermerkaya<notifications@github.com> wrote:   
Hi @vinceaar0n ,

I've just checks some more things about puffin.

Actually it does not work for publishing in youtube as well. The main problem for your side is on playing. To be honest, I could not even make a peer to peer connection in puffin.
I've testes several things other than our solution such as https://webrtc.github.io/samples/

Because puffin is a remote browser and website on our desktop are actually rendered in remote servers. I think this is the reason.

I think if puffin is working with WebRTC, then the issue may be about codec compatibility. Because Ant Media Server supports h264 and puffin cloud servers should support H.264 for WebRTC to be compatible with Ant Media Server streams.

Anyway, could you give a link that I can see puffin is working with WebRTC?

Lastly, do you think it is feasible for you to play stream with HLS or something in puffin browser?

**Comment by mekya** [comment] 2019-06-29 14:11
I've tested it for HLS. It works for me. I think I can make it work for you as well. 

I understand HLS long delay. We can minimize the latency to 6 seconds. 

Just let me have a link that puffin is working for WebRTC. 
Btw, there is no development tools in puffin. So it's hard to see where the problem is. Do you have an idea about that?

**Comment by vinceaar0n** [comment] 2019-06-29 16:13
I use javascript to apend console logs in a divWill send link later for webrtc player on puffin 

Sent from Yahoo Mail on Android 
 
  On Sat, 29 Jun 2019 at 10:11 PM, Ahmet Oğuz Mermerkaya<notifications@github.com> wrote:   
I've tested it for HLS. It works for me. I think I can make it work for you as well.

I understand HLS long delay. We can minimize the latency to 6 seconds.

Just let me have a link that puffin is working for WebRTC.
Btw, there is no development tools in puffin. So it's hard to see where the problem is. Do you have an idea about that?

**Comment by mekya** [comment] 2019-12-02 17:18
We probably handle this issue when we support VP8.

Closing this issue for now.

**Closed by mekya** 2019-12-02 17:18 UTC
