### ISSUE TITLE
Error with two different streams and same model web cameras.

### ISSUE THREAD

**Issue by muratugureminoglu** [ant-media/Ant-Media-Server#2580] opened 2020-10-07 21:38 UTC
### Short description
Error with two different streams and same model web cameras.

### Environment

* Operating system and version: Ubuntu 18.04
* Ant Media Server version: Enterprise Edition 2.2.0-SNAPSHOT 20200829_0830

### Steps to reproduce
1. Plug in 2 camera (same model)
2. Try to select the second one under the Options on the WebRTC Publish Page
3. See the error: The camera is already in use

### Expected behavior
It should work.
### Actual behavior
It couldn't work.

**Comment by Glfarley** [comment] 2020-10-13 11:11
Any progress with this issue? It's causing problems for us.

**Comment by golgetahir** [comment] 2020-10-19 22:13
Hi @Glfarley ,

The issue assigned to me in this sprint, I will take of it in 2-3 days at most.

**Comment by Glfarley** [comment] 2020-10-20 15:27
Great to hear! (and I see you are using Scrum - I am an old scrummaster :-))

Sometimes I get the error message that the camera is in use, and sometimes
I do not. But even when it works, it is impossible to know which webcam I
am using since they have exactly the same name and hex number.

Thanks,
Glen Farley

**Comment by golgetahir** [comment] 2020-10-21 14:39
Hi @Glfarley

Yes, we use scrum, it is pleasure to meet with an old scrummaster :) 

The problem is that we are using device.label and device.deviceId for buttons and they are the same in same devices. So, I added an indexing if there is duplicate devices for a quick fix for the issue. I guess this will resolve the issue, but I don't really have same model devices available to try right now.

Please apply the change in index.html ; https://github.com/ant-media/StreamApp/compare/same-model-device

If it doesn't solve your problem please reach back to me.

**Comment by Glfarley** [comment] 2020-10-21 15:41
That is great.  I have the hosted plan and lack the skills to apply your
fix to my server. Could you please apply it? Thanks a lot!

Glen Farley

**Closed** 2021-03-03 07:25 UTC
