### ISSUE TITLE
Ant Media Server IPv6 support

### ISSUE THREAD

**Issue by muratugureminoglu** [ant-media/Ant-Media-Server#4371] opened 2022-08-25 20:25 UTC
The dashboard cannot be accessed if the client's IP address is IPv6. 

Tomcat Error: "Not Allowed IP"

![185744434-6f5f1ed1-4847-496b-aaee-eed7f65b97a8](https://user-images.githubusercontent.com/6337605/186761906-b167be7c-d047-4a08-b37f-2038b6cdf904.png)

**Comment by arnowelzel** [comment] 2022-08-25 21:30
The problem is not IPv6 - it is when using IPv6 via a reverse proxy. Direct access via port 5080 is no problem with IPv6.

**Comment by muratugureminoglu** [comment] 2022-08-26 11:18
Can you share the access logs (/var/log/antmedia/) you accessed from 5080 ?

**Comment by mekya** [comment] 2022-08-29 08:18
Thank you for following up the issue @arnowelzel.

> The problem is not IPv6 - it is when using IPv6 via a reverse proxy. Direct access via port 5080 is no problem with IPv6.

I think it will help the developer to provide the correct solution.

**Comment by arnowelzel** [comment] 2022-08-29 12:49
I stand corrected - indeed IPv6 is missing in AntMedia completely. I was just mistaken because the client I used to test that, has a dual stack connection with IPv6 and IPv4 alike. However when trying to access on port 5080 with IPv6 only, there is no connection at all. When using dual stack with IPv4 and IPv6 I can connect - but only because the client then uses IPv4 since IPv6 is not possible:

```
84.173.xxx.xxx - - [29/Aug/2022:14:41:31 +0200] "GET /rest/v2/request?_path=LiveApp/rest/v2/vods/list/0/10&sort_by=&order_by= HTTP/1.1" 200 2
84.173.xxx.xxx - - [29/Aug/2022:14:41:31 +0200] "GET /rest/v2/request?_path=LiveApp/rest/v2/vods/count HTTP/1.1" 200 12
84.173.xxx.xxx - - [29/Aug/2022:14:41:33 +0200] "GET /rest/v2/authentication-status HTTP/1.1" 200 57
```

For IPv6 there are no log entries since Ant Media does not listen to the IPv6 address.

Sorry for the confusion.

**Comment by SelimEmre** [comment] 2022-08-29 17:18
Hi @arnowelzel,

Thank you for these details. This issue assigned to me. I will check it.

**Comment by SelimEmre** [comment] 2022-09-04 21:17
Hi @arnowelzel,

Have a good day. I tried to reproduce this issue OVH instance. They have both IPv4 and IPv6 in OVH instances. I tried to disable IPv4 but they didn't allow that. Reproducing this issue on my end is hard for now. If you're available I want to check this issue together. I have some ideas regarding Tomcat Connector details. 

Best Regards,
Selim

**Comment by arnowelzel** [comment] 2022-09-06 07:10
Hi @SelimEmre 

I can provide a FQDN name with only a AAAA record set for any IPv6 address you need, so you can access the machine with only IPv6 even if it has IPv4 enabled too. This way I could reproduce the problem on my side. I also can provide a test server with Ant Media installed and a IPv6 only FQDN.

Get in touch with me via e-mail, see my website https://arnowelzel.de/en/about-me for contact address, then we can discuss the details.

**Comment by SelimEmre** [comment] 2022-09-10 17:38
Hi @arnowelzel,

Have a good day. You need to change something on Ant Media Server for working IPV6. But it's experimental. Please let us know if you encounter other issues.
1- Add IP V6 AAAA record to the domain
2- Remove `-Djava.net.preferIPv4Stack=true` on `antmedia.service` in Ant Media directory. If Ant Media Server is already working as a service, change on `/etc/systemd/system/antmedia.service` file. Please don't forget to daemon reload as below:
`sudo systemctl daemon-reload`
`sudo service antmedia restart`
3- You need to add IPv6 permissions on `conf/red5.properties`. Just please change `server.allowed_dashboard_CIDR=0.0.0.0/0` to `server.allowed_dashboard_CIDR=::/0,0.0.0.0/0`

Best Regards,
Selim

**Comment by arnowelzel** [comment] 2022-09-10 17:51
Hi @SelimEmre, thanks for your help - I changed the settings accordingly and now everything works fine with IPv4 and IPv6 likewise. I checked this using direct access from the client as using IPv4 and IPv6 as well as using the Apache proxy without `ProxyAddHeaders off`. Both work fine now.

**Comment by arnowelzel** [comment] 2022-09-11 08:51
Update: it turns out, that just adding `server.allowed_dashboard_CIDR=::/0,0.0.0.0/0` to the configuration is sufficient. No need to change the systemd unit parameters.

**Closed as completed** 2022-11-15 08:40 UTC
