### ISSUE TITLE
MapDB nullpointer exception

### ISSUE THREAD

**Issue by eneskuluk** [ant-media/Ant-Media-Server#2425] opened 2020-08-20 17:10 UTC
### Short description
java.lang.nullpointer exception at mapdb are in the following logs that needs to be investigated.
[ant-media-server.log.zip](https://github.com/ant-media/Ant-Media-Server/files/5104442/ant-media-server.log.zip)

### Environment

* Ant Media Server version: Community 2.1.0 20200720_1340

**Comment by muratugureminoglu** [comment] 2020-08-21 08:10
`2020-08-16 00:16:14,060 [http-nio2-0.0.0.0-5080-exec-3] ERROR o.a.c.c.C.[.[.0.0.0.[.[jersey-serlvet] - Servlet.service() for servlet [jersey-serlvet] in context with path [/WebRTCAppEE] threw exception [java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null
        at org.mapdb.volume.ByteBufferVol.getSlice(ByteBufferVol.java:43)
        at org.mapdb.volume.ByteBufferVol.getLong(ByteBufferVol.java:122)
        at org.mapdb.volume.ReadOnlyVolume.getLong(ReadOnlyVolume.java:62)
        at org.mapdb.StoreWAL.getIndexVal(StoreWAL.kt:167)
        at org.mapdb.StoreWAL.get(StoreWAL.kt:499)
        at org.mapdb.BTreeMap.getNode(BTreeMap.kt:800)
        at org.mapdb.BTreeMap.access$getNode(BTreeMap.kt:72)
        at org.mapdb.BTreeMap$BTreeIterator.advanceFrom(BTreeMap.kt:1031)
        at org.mapdb.BTreeMap$BTreeIterator.<init>(BTreeMap.kt:1016)
        at org.mapdb.BTreeMap$valueIterator$1.<init>(BTreeMap.kt:1223)
        at org.mapdb.BTreeMap.valueIterator(BTreeMap.kt:1223)
        at org.mapdb.BTreeMap$values$1.iterator(BTreeMap.kt:999)
        at io.antmedia.datastore.db.MapDBStore.getActiveBroadcastCount(MapDBStore.java:328)
        at io.antmedia.rest.BroadcastRestService.getAppLiveStatistics(BroadcastRestService.java:514)
        at sun.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:243)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.filters.ExpiresFilter.doFilter(ExpiresFilter.java:1232)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at io.antmedia.filter.IPFilter.doFilter(IPFilter.java:24)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.red5.logging.LoggerContextFilter.doFilter(LoggerContextFilter.java:84)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
        at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1682)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
2020-08-16 00:16:14,388 [https-jsse-nio-0.0.0.0-5443-exec-16] INFO  i.a.e.s.WebSocketLocalHandler - Web Socket opened
2020-08-16 00:16:14,427 [https-jsse-nio-0.0.0.0-5443-exec-11] ERROR i.a.e.s.WebSocketLocalHandler - WebSocket handler cannot be created
2020-08-16 00:16:14,427 [https-jsse-nio-0.0.0.0-5443-exec-11] ERROR i.a.e.s.WebSocketLocalHandler - InvocationTargetException: 
2020-08-16 00:16:14,791 [pool-5-thread-1] INFO  o.r.server.service.ShutdownServer - One or more contexts didn't close in the allotted time`

**Comment by eneskuluk** [comment] 2020-08-24 09:37
[antmedia-error.log](https://github.com/ant-media/Ant-Media-Server/files/5117000/antmedia-error.log)
Another log with the nullpointerexception caused by MapDb.

**Comment by minakitty** [comment] 2020-10-06 04:25
I was told the issue I was having is linked to this issue, so here's the logs from my case in case they're useful
[zagato-maint (1).zip](https://github.com/ant-media/Ant-Media-Server/files/5331383/zagato-maint.1.zip)

**Comment by mekya** [comment] 2020-10-12 14:56
We've resolved these null pointer issues in 2.2.0-SNAPSHOT

**Comment by rhengles** [comment] 2020-10-19 16:34
@mekya Is there already a release planned with this fix?

**Comment by mekya** [comment] 2020-10-19 17:25
Hi @rhengles , Yeah sure. We're about to release a new version in this week.

**Comment by rhengles** [comment] 2020-10-26 13:19
@mekya Sorry to bug you again, but we're quite anxious about this fix. Can we expect a release this week? We'd appreciate any info you could give us.

Thank you.

**Comment by mekya** [comment] 2020-11-20 09:30
Hi,
We've released the version. 

Closing this issue for now. Please feel free to re-open if you're having the same problem.

**Closed by mekya** 2020-11-20 09:30 UTC
Labels: investigating
