### ISSUE TITLE
Bug in Peer.html

### ISSUE THREAD

**Issue by maydin** [ant-media/Ant-Media-Server#2109] opened 2020-04-28 20:07 UTC
iPhone 7 (Firefox), I got the UnSecureContext message.

- Connection is secure(https) and it shouldn't give unsecure context message

**Comment by maydin** [comment] 2020-04-28 22:01
![scr.jpg](https://images.zenhubusercontent.com/5b09234676f98d26207425f5/1802e2b0-4f28-406b-88c7-352bcab0a8d2)

**Comment by Glfarley** [comment] 2020-05-18 08:22
Same problem with us. Disconcerting to get this type of warning message.

**Comment by eneskuluk** [comment] 2020-07-12 09:15
Actually this issue is caused by ios itself. IOS does not permit video camera access to the 3.rd party browsers such as firefox. Only safari can have video camera access.

**Comment by Glfarley** [comment] 2020-07-12 09:28
Yes, it would save your customers a lot of time if you posted clearly in your documentation that Ant Media on mobile devices works ONLY with Safari, no other browsers.

**Comment by mekya** [comment] 2020-07-17 07:02
Yes you're right. My colleague is preparing a browser compatibility support matrix for that. 

So I'm closing this ticket now.

**Closed by mekya** 2020-07-17 07:02 UTC
Labels: bug

**Comment by Glfarley** [comment] 2020-07-17 07:03
OK, thank you.

Glen Farley

**Comment by mekya** [comment] 2020-07-17 07:13
THANK YOU
