### ISSUE TITLE
consider business emails in Control panel create users email validation

### ISSUE THREAD

**Issue by ashrafbendary** [ant-media/Ant-Media-Server#4184] opened 2022-05-11 16:42 UTC
### Short description
when i try to create user with business email (domain not yahoo or gmail etc..) it give error message "E-mail is required in correct form." so you need to consider business emails in Control panel create users-> email validation

### Environment
Enterprise Edition 2.4.3 20220418_2241

### Steps to reproduce
1. got to contolpanel
2. setting
3. click new user
4. enter data and at email add any business email like (test@test.com) 

### Expected behavior
to add email like previous version 

### Actual behavior
give error message
 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by mekya** [comment] 2022-05-16 17:56
Let me move to the backlog to schedule

**Comment by SelimEmre** [comment] 2022-05-22 14:49
Hi @ashrafbendary,

I have checked in Enterprise Edition v2.4.3. I couldn't get this error. I'm expecting that it can be related to caching. Could you please try with incognito page or cleared cache?

**Comment by yashtandon113** [comment] 2022-06-20 11:44
Similar issue reported by user. Below is the reproduce scenario.

Description: I cannot create user with email in domain "live" or "stream". Validator pattern attribute on the field is: "[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$"
it's obviously, incorrect as it allows only 2- and 3-symbol long email domains

Steps to reproduce:
1. Go to "Settings"
2. Switch to users tab
3. Click "Add new user"
4. Fill in fields. In "username (email)" field type something like "test@company.live" or "test@company.digital"
5. See validation warning under the field

**Comment by SelimEmre** [comment] 2022-06-20 12:15
@yashtandon113 Thank you for your comment. I will check it :+1::+1:

**Comment by SelimEmre** [comment] 2022-06-27 14:40
Hi guys,

It seems that it was related to email TLD extension. It gives an error if email TLD extension exceeds 3. So I changed to 16. Please correct me if I'm wrong.

**Comment by yashtandon113** [comment] 2022-09-24 18:09
@SelimEmre 
While creating a user via the dashboard settings, the problem is fixed, but when creating a new account for the first time, the problem still exists.

**Comment by mekya** [comment] 2022-09-25 10:07
Hi @yashtandon113 ,
Thank you. I'm closing this issue because there is a new issue(#4418)

**Closed by mekya** 2022-09-25 10:07 UTC
