### ISSUE TITLE
HlsViewerCount counting x8 (Live)

### ISSUE THREAD

**Issue by triangle-stream** [ant-media/Ant-Media-Server#2812] opened 2020-12-22 18:13 UTC
Hello, 

Thank you for this project. 

With the recent version of AntMedia Server (community-2.2.1-20201029) the HlsViewerCount is counting 6 times every request at the manifest. 
This only happens when using player in other websites via embedding; viewing the video from the play button in dashboard works as expected.

**OS**: Ubuntu 18.04
**Java version**: openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

Here is some LOGs while watching videos using hls playlist in VideoJS:
```
2020-12-22 19:05:14,147 [vert.x-eventloop-thread-6] INFO  i.antmedia.statistic.HlsViewerStats - Update HLS viewer in stream ID:test increment count:2 decrement count:0 diff:2
2020-12-22 19:05:24,147 [vert.x-eventloop-thread-6] INFO  i.antmedia.statistic.HlsViewerStats - Update HLS viewer in stream ID:test increment count:5 decrement count:0 diff:5
2020-12-22 19:05:30,774 [vert.x-eventloop-thread-0] INFO  i.antmedia.statistic.StatsCollector - System cpu load:0 process cpu load:1 available memory: 58933180 KB used memory(RSS): 1666364 KB
2020-12-22 19:05:30,775 [vert.x-eventloop-thread-0] INFO  i.antmedia.statistic.StatsCollector - Vertx worker queue size:0 WebRTCVertx worker queue size:0
2020-12-22 19:05:34,146 [vert.x-eventloop-thread-6] INFO  i.antmedia.statistic.HlsViewerStats - Update HLS viewer in stream ID:test increment count:6 decrement count:-2 diff:4
2020-12-22 19:05:44,147 [vert.x-eventloop-thread-6] INFO  i.antmedia.statistic.HlsViewerStats - Update HLS viewer in stream ID:test increment count:5 decrement count:-5 diff:0
2020-12-22 19:05:54,146 [vert.x-eventloop-thread-6] INFO  i.antmedia.statistic.HlsViewerStats - Update HLS viewer in stream ID:test increment count:6 decrement count:-6 diff:0
2020-12-22 19:06:04,147 [vert.x-eventloop-thread-6] INFO  i.antmedia.statistic.HlsViewerStats - Update HLS viewer in stream ID:test increment count:4 decrement count:-5 diff:-1
2020-12-22 19:06:14,146 [vert.x-eventloop-thread-6] INFO  i.antmedia.statistic.HlsViewerStats - Update HLS viewer in stream ID:test increment count:4 decrement count:-6 diff:-2

```

No entries in Error LOGs.

**Comment by mekya** [comment] 2020-12-28 17:14
Hi @triangle-stream ,

Thank you for your report. 

Make sure that you use videojs player(that's available in the play.html) and you've installed SSL to your server. 
Then play the video via HTTPS. Otherwise, player does not store the session id cookie and server thinks that it's coming from different users. It results x8 viewer counting.

**Comment by triangle-stream** [comment] 2020-12-28 18:41
Thank you @mekya 

I'm using Antmedia only via HTTPS and unfortunately I'm having the same issue also while using the play.html player (and embedding it from the "Copy embed code"). 
I've also tried tho show debug logs but I haven't found any errors. 
Is there a specific logfile in which I can look? I mean, specific file in specific folder.

To be honest this is not a big issue but I was just curious about the possible cause. 

Thank you!

**Comment by mekya** [comment] 2020-12-29 06:03
My pleasure @triangle-stream ,

I can try to reproduce the issue on my end with 2.2.1.

So here are the steps

1. Install community 2.2.1
2. Install SSL
3. Publish stream with RTMP
4. Play stream with HLS(videojs) via HTTPS

Then I'll see the problem about x8 viewers. 

Is that correct?

**Comment by triangle-stream** [comment] 2020-12-29 09:11
Correct! 

My version is Community Edition 2.2.1 20201029_0748. If you need it, I can give you access to my antmedia installation.


Thank you!

**Comment by MrXermon** [comment] 2020-12-31 21:40
Hi!

Any chance to have correct statistics even if a external player is used? We're currently trying to generate the statistics for our live-streams on the client-side but this is not fully working due to the fact that some devices do not support the Java Script functions we're using. Therefore it would be great to be able to gather some "more valid" statistics on the server-side.

Thanks for your inputs!

**Comment by mekya** [comment] 2021-01-05 07:49
Hi,

We have not confirmed this case yet. Sorry for that. I'll ask one of my colleague to confirm the case in this week. 
 
@MrXermon , as long as external player uses the same cookie(session id) for accessing the HLS chunks, it'll be calculated correctly. If external player does not send session id cookie, it's hard to calculate the correct statistics on the server side.   

Regards,
A. Oguz

**Comment by MrXermon** [comment] 2021-01-06 08:05
Hi @mekya,

thanks for the information regarding the cookie. I've managed to sent the correct cookie (JSESSIONID) to the server whilst embedding the stream directly form the AntMedia server. Just to make sure I understand the method correctly: Does the statistic tool extracts the session ID from every request or are only the requests to the playlist file "counted"? I'm normally using AWS CloudFront in front of our streaming-servers and using this combination (AntMedia Server + AWS CloudFront) breaks the statistics again. In the case of only the hits to the playlist files are being counted I could accommodate a working configuration in CloudFlare to forward the cookie trough CloudFlare to AntMedia Server to load the playlist-file directly from there and count the viewers correctly.

Regards
Jan

**Comment by mekya** [comment] 2021-01-07 06:49
Hi @MrXermon ,

Thank you for your investigation. 

> Does the statistic tool extracts the session ID from every request or are only the requests to the playlist file "counted"?

Yes it extracts the session ID for every request to m3u8 files. It counts each different session id as new viewer. So If same player sending different session id in each request, server thinks that it's a new viewer.  

> I'm normally using AWS CloudFront in front of our streaming-servers and using this combination (AntMedia Server + AWS CloudFront) breaks the statistics again.

I think Ant Media Server may not show the correct usage when using AWS CloudFront. Because Cloudfront caches the files in pop points. If it hits the origin(Ant Media Server) for every m3u8 requests by sending cookie coming from client, then Ant Media Server shows the correct statistics.

> In the case of only the hits to the playlist files are being counted I could accommodate a working configuration in CloudFlare to forward the cookie trough CloudFlare to AntMedia Server to load the playlist-file directly from there and count the viewers correctly.

Yes I think so.

**Comment by triangle-stream** [comment] 2021-01-07 08:50
I tried with a fresh new install of the same (latest) version of AM and I'm having the same behaviour. 

This also happens by using the embed code provided by AM LiveApp Dashboard.

**Comment by MrXermon** [comment] 2021-01-07 08:50
Hi @mekya,

thanks for the feedback!
Got it working today as described above and it looks like I've had a wrong "URL pattern" set in CloudFront to disable caching for the playlist files. If it is of interest, I could add a wiki entry to the AntMedia wiki which describes the configuration?

@triangle-stream Your issue should be fixed by adding the video source to the player by using the following code/parameter. The "withCredentials: true" is the important part as this enables the player to sent back the correct cookies to the server.
`<script>
videojs('videoplayer').src([
{
  src: "URL to playlist-file",
  type: "application/x-mpegURL",
  withCredentials: true
}
]);
</script>`

Regards
Jan

**Comment by triangle-stream** [comment] 2021-01-07 20:23
Thank you @MrXermon, I'll try to put nginx in front of AntMedia but the thing is that this is happening also using the default embed code (and so play.html) provided by AntMedia.

Thank you for your work.

**Comment by mekya** [comment] 2021-01-08 06:45
hi @MrXermon ,

> Got it working today as described above and it looks like I've had a wrong "URL pattern" set in CloudFront to disable caching for the playlist files. If it is of interest, I could add a wiki entry to the AntMedia wiki which describes the configuration?

Absolutely, it's helpful. 

Thank you.

**Comment by muratugureminoglu** [comment] 2021-01-08 06:51
@triangle-stream I tested this in the latest version and I did not encounter any problems and it showed the correct numbers. Can you share your reproduce scenario with us?

@MrXermon Thank you for your feedback. It also works on Nginx but you can change it from the server side in /usr/local/antmedia/webapps/{your_app}/WEB-INF/web.xml

```
<filter>
                <filter-name>CorsFilter</filter-name>
                <filter-class>io.antmedia.filter.CorsHeaderFilter</filter-class>
                <init-param>
                    <param-name>cors.allowed.origins</param-name>
                    <param-value>*</param-value>
                 </init-param>
                 <init-param>
                        <param-name>cors.allowed.methods</param-name>
                        <param-value>GET,POST,HEAD,OPTIONS,PUT,DELETE</param-value>
                 </init-param>
        </filter>
```

**Comment by triangle-stream** [comment] 2021-01-08 07:45
@muratugureminoglu Thank you for your reply. What do I need to share with you? Are there any specific infos you want?

Thank you.

**Comment by muratugureminoglu** [comment] 2021-01-11 07:56
@triangle-stream How do you broadcast? Can you show us the steps?
- Is there any load balancer?
- Are you using embedded?

**Comment by triangle-stream** [comment] 2021-01-11 08:39
@muratugureminoglu 
We use different softwares/encoders to broadcast: OBS, vMix, Wirecast, FFMPEG via custom scripts, etc. 

We use RTMP and h264 video with AAC audio. 
Encoding parameters may be different but generally libx264 main/high profile with different bitrates (up to 1080p60).

We have not any load balancer between AntMedia and clients.

We use both embedded provided by AntMedia -
 `<iframe width="560" height="315" src="https://our.host.name:5443/LiveApp/play.html?name=test" frameborder="0" allowfullscreen></iframe>`) 
- and playlist link (with or without token as we don't have this feature and the value for token is undefined) used in VideoJS latest (but also tested with previous versions).

In AntMedia log we can see only one error:

```
org.apache.coyote.http11.Http11Processor service
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x00{0x010x000x00w0x030x033A0xec0xd90xb8I0x040x0bA0xcfU0xec0x1b&0x8a0xd00xbb}n0xdak0xe8l0xb5kwr0x940x900x1d6$0x000x000x1a0xc0/0xc0+0xc00x110xc00x070xc00x130xc00x090xc00x140xc00x0a0x000x050x00/0x0050xc00x120x000x0a0x010x000x0040x000x050x000x050x010x000x000x000x000x000x0a0x000x080x000x060x000x170x000x180x000x190x000x0b0x000x020x010x000x000x0d0x000x100x000x0e0x040x010x040x030x020x010x020x030x040x010x050x010x060x010xff0x010x000x01...]. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:427)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:503)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
	at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2045)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

This error, that seems to be related to the request headers, is also present in at least another AntMedia installation on another server with the same specs as this one. 

Thank you.

**Comment by muratugureminoglu** [comment] 2021-01-11 14:39
@triangle-stream Can you send a mail to support@antmedia.io by mentioning me ? Let's check on your end.

Regards.

**Comment by andry1234-cpu** [comment] 2021-01-13 10:11
Hello everyone,
I'm having the same problem using JWPlayer for the HLS streaming.
Number of viewers is not real, I'm using https for the Ant Media server and the hosted webpage where JW Player is embedded.
Any news on this?

Thank you

**Comment by mekya** [comment] 2021-01-15 07:14
hi @andry1234-cpu ,

I think it'll be great if we provide a working sample for JWPlayer.

By that time, do you try to take a look at how to send the same cookies in JWPlayer? 


Regards,
A. Oguz

**Comment by andry1234-cpu** [comment] 2021-01-15 09:19
> hi @andry1234-cpu ,
> 
> I think it'll be great if we provide a working sample for JWPlayer.
> 
> By that time, do you try to take a look at how to send the same cookies in JWPlayer?
> 
> Regards,
> A. Oguz

Hi,
thanks for the reply and for the support. 
What do you mean by "a working sample for JWPlayer"? 

Until now, using other CDN services, I have never had this cookie issue. 
Any advise on the difference that could lead ANT MEDIA putting out this problem? 

I'm on a .com domain with SSL certificates.

Have a nice day

**Comment by MrXermon** [comment] 2021-01-15 09:22
I think your problem is probably the "cors.allowed.origins" setting as some browsers do not allow the "*" wildcard method anymore. In addition to that please make sure to set the "withCredentials" option while adding the source to your player. Is there a chance you can share an example code/page used to embed the player into the website?

Kind Regards
Jan

**Comment by andry1234-cpu** [comment] 2021-01-15 09:32
> I think your problem is probably the "cors.allowed.origins" setting as some browsers do not allow the "*" wildcard method anymore. In addition to that please make sure to set the "withCredentials" option while adding the source to your player. Is there a chance you can share an example code/page used to embed the player into the website?
> 
> Kind Regards
> Jan

Sure,
Here's a quick sample code I'm using for testing purposes

```<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>Feel Me - Virtual Event</title>
  <link rel="shortcut icon" href="img/ded_favicon.ico" />

</head>

	
<body style="background-color:black;">
	

<div class="firstDiv" > 

<div style="position:relative; overflow:hidden; padding-bottom:56.25%"> 
	
<iframe src="https://cdn.jwplayer.com/players/LejRKPp9-aKRcUt7x.html" width="100%" height="100%" frameborder="0" scrolling="auto" title="LEOStreams - Canale 3" style="position:absolute;" allowfullscreen>
</iframe>
	
</div>	

	</body>

</html>

**Comment by MrXermon** [comment] 2021-01-15 16:17
The problem may be the third-party cookies used as the site hosting the player is not the same site as the one which embeds the iFrame. I ran into a similar issue in which at least Chrome blocks the requests with the cookies.

My setup is sth. similar like this:
- Event-Website runs under the myevent.io domain.
- VideoJS player is hosted on the streaming.mycompany.de domain.
- Stream is embedded from hls.streaming.mycompany.de or cdn.hls.streaming.mycompany.de (AWS CloudFront).

The setup works in Firefox but does not work in Chrome and Safari. I think I have to find a way to host everything on the same domain, although this is currently not possible for me. Another idea would be to do the user-tracking differently on the server-side by matching on other values sent by the client.

Regards
Jan

**Comment by andry1234-cpu** [comment] 2021-01-26 08:28
Hello everyone,
after days of testing setups and investigation on CORS, I'm still in a non working situation.
I will report my complete environment, so maybe we can investigate this once for all.
I'm using an AWS AMI Ant Media enterprise instance, running on a G4DN machine.
Everything is pretty untouched, just one or two div's removed (the ones about the network bad connection warning).

I'm ingesting a streaming in Ant Media for testing purposes, ABR is active, I do use a link as the following one:
https://live.leostreams.com:5443/LiveApp/streams/canale05_adaptive.m3u8

This M3U8 file is loaded in a JWPlayer hosted instance, the HTML web page is server by an S3 AWS bucket, with HTTPS enabled.
The viewers number in Ant Media is showing the following, with a single connection running:
![Schermata 2021-01-26 alle 09 25 46](https://user-images.githubusercontent.com/63965845/105819448-7f579700-5fb8-11eb-9643-8ddc5908f8d0.png)


All other services such as Wowza, Akamai, Bitmovin, Dacast, etc.. are running perfectly fine with this same setup (I mean, with the right number of HLS viewers showing), the problem is just with Ant Media M3U8 files.

If I remove the adaptive keyword from the link, so "https://live.leostreams.com:5443/LiveApp/streams/canale05.m3u8", the number is fine and I get the number for the single user connection. 
Using the integrated HLS player, the number is right too:
![Schermata 2021-01-26 alle 09 27 26](https://user-images.githubusercontent.com/63965845/105819648-baf26100-5fb8-11eb-91e8-9c1a028e014f.png)

Checking the CORS filter settings, everything is open to the world with the * value.

Do you have any other suggestion?

Thank you, have a nice day

**Comment by rubengg86** [comment] 2021-01-29 11:32
I think i fix this issue in my setup. We are using a external player (videogular2) and a NGINX proxy pass in front of Antmedia and after several days trying things, the solution was:

- Add crossorigin="use-credentials" in <video> tag
- Add this configuration to nginx conf:
`proxy_cookie_path ~*^/.* "/; secure; HttpOnly; SameSite=None";
proxy_cookie_domain * ANTMEDIA_DOMAIN;
if ($http_cookie ~* "JSESSIONID=([^;]+)(?:;|$)") {
		set $co "JSESSIONID=$1";
}
proxy_set_header Cookie "$co";
add_header 'withcredentials' 'true' always;
proxy_hide_header 'Access-Control-Allow-Origin';
add_header 'Access-Control-Allow-Origin' "$http_origin" always;
add_header 'Access-Control-Allow-Credentials' 'true' always;
add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With' always;`

I hope this can help someone :)

**Comment by andry1234-cpu** [comment] 2021-01-29 11:40
> I think i fix this issue in my setup. We are using a external player (videogular2) and a NGINX proxy pass in front of Antmedia and after several days trying things, the solution was:
> 
> * Add crossorigin="use-credentials" in
> * Add this configuration to nginx conf:
>   _proxy_cookie_path ~_^/._ "/; secure; HttpOnly; SameSite=None";
>   proxy_cookie_domain * ANTMEDIA_DOMAIN;
>   if ($http_cookie ~* "JSESSIONID=([^;]+)(?:;|$)") {
>   set $co "JSESSIONID=$1";
>   }
>   proxy_set_header Cookie "$co";
>   add_header 'withcredentials' 'true' always;
>   proxy_hide_header 'Access-Control-Allow-Origin';
>   add_header 'Access-Control-Allow-Origin' "$http_origin" always;
>   add_header 'Access-Control-Allow-Credentials' 'true' always;
>   add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
>   add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With' always;_
> 
> I hope this can help someone :)

Hi Ruben and thanks for the tip.
I have a standard AMI Enterprise Ant Media instance. Do you think NGINX is used by default?

Thank you

**Comment by rubengg86** [comment] 2021-01-29 11:47
> > I think i fix this issue in my setup. We are using a external player (videogular2) and a NGINX proxy pass in front of Antmedia and after several days trying things, the solution was:
> > 
> > * Add crossorigin="use-credentials" in
> > * Add this configuration to nginx conf:
> >   _proxy_cookie_path ~_^/._ "/; secure; HttpOnly; SameSite=None";
> >   proxy_cookie_domain * ANTMEDIA_DOMAIN;
> >   if ($http_cookie ~* "JSESSIONID=([^;]+)(?:;|$)") {
> >   set $co "JSESSIONID=$1";
> >   }
> >   proxy_set_header Cookie "$co";
> >   add_header 'withcredentials' 'true' always;
> >   proxy_hide_header 'Access-Control-Allow-Origin';
> >   add_header 'Access-Control-Allow-Origin' "$http_origin" always;
> >   add_header 'Access-Control-Allow-Credentials' 'true' always;
> >   add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
> >   add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With' always;_
> > 
> > I hope this can help someone :)
> 
> Hi Ruben and thanks for the tip.
> I have a standard AMI Enterprise Ant Media instance. Do you think NGINX is used by default?
> 
> Thank you

Hi,
I am using the community edition, and I install a NGINX as proxy to hide, antmedia ports and use 443 and other stuff of my infrastructure.

**Comment by lionxvibe** [comment] 2021-01-30 11:00
I have the same problem with HLS. I have AMS EE cluster behind a Haproxy, I tried to disable balancing but the counter stills multiply users... 
I've a front app using a hls player : front.domain.com
My API using the AMS API and webhook: api.domain.com

Cors is hard to manage for multiple domains. 

As a workaround I'll use my own count system with websocket...

**Comment by sahiljain2497** [comment] 2021-06-18 18:58
Any updates on this please?

**Comment by mekya** [comment] 2021-06-21 17:23
Hi @sahiljain2497 ,

Actually this issue is waiting for me to review. Sorry for that. 

Btw, we've encountered similar issues and the problem is generally about the cookie management in the player or in the LB.

**Comment by sahiljain2497** [comment] 2021-07-02 08:33
Hi @mekya , 

Can you mention anything we need to make sure on the player side?
We are using Application Load Balancer, if you can mention few steps or settings which are required to fix this issue that would be a great help.

Thanks very much

**Comment by mekya** [comment] 2021-07-03 14:08
hi @sahiljain2497 ,

Sure. 

Firsty,  application load balancer should use sticky session. 

Secondly, player should use the same session cookie received from the server side in all http requests. If it makes a new fresh request(no cookie) for each ts segments or m3u8 requests, server thinks that it's a new user. 

Let me know if you have further questions.

**Comment by mekya** [comment] 2021-08-02 10:54
It seems that nobody else complain about this issue. Please let me know if the instructions does not help you 

> hi @sahiljain2497 ,
> 
> Sure.
> 
> Firsty, application load balancer should use sticky session.
> 
> Secondly, player should use the same session cookie received from the server side in all http requests. If it makes a new fresh request(no cookie) for each ts segments or m3u8 requests, server thinks that it's a new user.
> 
> Let me know if you have further questions.

**Closed** 2021-09-13 17:41 UTC

**Comment by MrXermon** [comment] 2021-11-12 08:23
Could be improved by #3738 as well.

**Comment by petsoukos** [comment] 2022-04-05 14:26
Having this issue with HLS behind CDN using custom videojs implementation

**Comment by mekya** [comment] 2022-04-06 06:45
Let's continue in this thread #3738 @petsoukos
