### ISSUE TITLE
Noise Supression Echo Cancellation   

### ISSUE THREAD

**Issue by nocpbxchap** [ant-media/Ant-Media-Server#4955] opened 2023-04-02 15:39 UTC
### Short description
Hello, 

Seems AMS has issues with play audio if enable these Noise Supression
Echo Cancellation
 
to check please visit

1.-Publish page
2.-Start streaming
3.-Go to Player.html
4.-Play streamid
5.-Then apply on publisher page noise or echo and will see there is no audio y found that there is an issue with.

soundmeter.js:23 [Deprecation] The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead

these is affecting all related to sound.

AMS 2.5.3

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version:
* Browser name and version:

### Steps to reproduce
1. 
2. 
3.

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [community.antmedia.io](https://community.antmedia.io) and be a part of Ant Media Server Community.

**Comment by mustafaboleken** [comment] 2023-04-03 02:58
Hi @nocpbxchap ,
Thank you very much for raising this error. We already start working on migrating to AudioWorkletNode. You can check the pull request link below. Even though I test it with AudioWorkletNode, there is still an audio issue. We will investigate it and let you know about the process.

https://github.com/ant-media/StreamApp/pull/346

**Comment by mekya** [comment] 2023-04-03 08:16
hi @mustafaboleken @nocpbxchap 

I think the scenario provided @nocpbxchap should work without sound meter.
This is another issue and I think it's likely easy to fix.

**Comment by nocpbxchap** [comment] 2023-04-03 15:20
If you remove soundmeter there is no issue sounds play, but noise
supression and echo cancellation will not work.

**Comment by mustafaboleken** [comment] 2023-04-10 10:58
When we call applyConstraints, we forget to refresh soundmeter, this is the problem. I add fix into https://github.com/ant-media/StreamApp/pull/346

**Comment by nocpbxchap** [comment] 2023-04-22 03:53
is fixed?

**Comment by mekya** [comment] 2023-04-24 12:32
hi @nocpbxchap ,
It's not confirmed yet. Our goal to confirm and merge in this week. 

Thank you for follow up

**Comment by mekya** [comment] 2023-04-28 09:14
Hi @mustafaboleken,

When I take look at your PR, I see that this problem is something else. 

Please review this PR and merge it to fix this issue. 
https://github.com/ant-media/StreamApp/pull/356

Thank you for follow up @nocpbxchap 

Regards
Oguz

**Comment by mekya** [comment] 2023-05-01 07:05
Closing the issue. Please feel free to open if it does not work.

**Comment by nocpbxchap** [comment] 2023-06-13 18:26
hello, i has being testing on version 2.6.1 but error still remains, it was tested?
0.008388888888888888 audio jitter: 0.010979166666666667
2publish_webrtc.html?debug=false:478 Uncaught TypeError: Cannot read properties of undefined (reading 'then')
    at HTMLInputElement.changeAudioConstraints (publish_webrtc.html?debug=false:478:45)

no audio if enable noise or echo.

**Comment by mustafaboleken** [comment] 2023-06-14 09:14
Hi @nocpbxchap 

Can you please test it with our server? I cannot reproduced following error but if you can on ovh36, please let me know. I will reopen the task. https://ovh36.antmedia.io:5443/LiveApp/

**Comment by nocpbxchap** [comment] 2023-06-15 05:10
Maybe soundmetter issue now i see is volumetet but seems still issies there.

When enable noise and echo audio level seems not work and boise and
background do nothing, should test yourself maybe wrong but not see any
change.

**Comment by mekya** [comment] 2023-06-30 19:12
I've re-opened this issue and let's reproduce it @mustafaboleken @nocpbxchap

**Comment by USAMAWIZARD** [comment] 2023-09-06 13:10
This issue is not reproducible and has been fixed on latest snapshot

**Comment by USAMAWIZARD** [comment] 2023-09-25 10:21
@nocpbxchap I am closing this issue for inactivity , Please re-open the issue if you are still facing the same problem with the latest version.

**Closed by USAMAWIZARD** 2023-09-25 10:21 UTC
Labels: bug, js-sdk
