### ISSUE TITLE
Streams doesn't play in Opera.

### ISSUE THREAD

**Issue by golgetahir** [ant-media/Ant-Media-Server#3553] opened 2021-08-21 10:09 UTC
### Short description
we get play_finished in Opera, a user says this also happens sometimes in chrome, the issue on chrome could not reproduced on my end.

![Untitled](https://user-images.githubusercontent.com/32591015/130318468-351cf1eb-9c0f-4f65-9d06-a7bbcc27c1c6.png)

### Environment

* Operating system and version: Windows 10
* Java version: 11
* Ant Media Server version: 2.4.0
* Browser name and version: Opera

### Steps to reproduce
1. Publish stream
2. Try to play in opera
3.

### Expected behavior
Stream should play as in other browsers

### Actual behavior
Stream does not play

**Comment by picpixel** [comment] 2021-08-21 16:12
I have the same behavior with FireFox. 
It’s not systematic but the stream won’t play.

**Comment by eneskuluk** [comment] 2021-08-31 11:02
Duplicate of #1650
My response was:
```
Opera does not come with a native support of h.264. It's dependent on the environment that it is installed. 
Opera supports VP8,VP9, AV1 natively but not h.264. 
This is because proprietary licence issues of h.264 .
To use h.264 in opera in a Windows 10 environment, Windows Media Pack needs to be installed.
On the other hand, VP8 can be used to stream which works flawless with Opera.
Disabling h.264 and enabling vp8 in Ant Media Settings would solve this issue.
``` 

Opera only support x264 encoding but has no decoding capabilities, so that's why if installed environment does not support it, user won't be able to play videos with it. 
My testing results were:
On ubuntu 21.04, I was able to stream with h264 but couldn't played due to the problems mentioned above. In Windows 10, I have media pack installed. I could stream and play with no issues whatsoever.

**Closed** 2021-09-13 17:40 UTC
