### ISSUE TITLE
JWT settings disappear

### ISSUE THREAD

**Issue by muratugureminoglu** [ant-media/Ant-Media-Server#3214] opened 2021-04-27 18:18 UTC
### Short description
JWT settings disappear when Ant Media Server is restarted.

### Environment

* Operating system and version: Ubuntu 18.04
* Java version: Java 11
* Ant Media Server version: 2.3.2
* Browser name and version: Chrome 90

### Steps to reproduce
1. Go to the Dashboard > App > Settings > JWT settings
2. Enable "Publish with JWT Filter for Stream" or " Play with JWT Filter for Stream"
3. Save the settings
4. Restart the Ant Media Server

### Expected behavior
It should save the JWT settings.

### Actual behavior
It's not saving the JWT settings.

**Comment by tkdave** [comment] 2021-04-29 21:50
Related question. How would one set these settings in the config file? I was also just looking for them to add to my startup scripts, but as original poster mentions, settings are not saved as others are.

**Comment by golgetahir** [comment] 2021-05-10 11:23
Hi @tkdave 

First I would like to say that the problem is resolved with the above mentioned PR.

For your question, please add the settings like;

settings.publishJwtControlEnabled=true
settings.jwtStreamSecretKey=JTI902tjUlmQiezul3kSTHo11SDYQCLl
settings.jwtControlEnabled=false

settings.playJwtControlEnabled=false
settings.jwtSecretKey=


to /usr/local/antmedia/webapps/<App_Name>/WEB-INF/red5-web.properties

These are the related settings.

Cheers

**Closed** 2021-05-13 19:54 UTC
Labels: bug
