### ISSUE TITLE
remotePeerConnection dataChannel after reconnect is undefined

### ISSUE THREAD

**Issue by allevi18** [ant-media/Ant-Media-Server#5151] opened 2023-05-25 14:42 UTC
### Short description
After internet connection interruption the dataChannel is undefined and can't send/receive data through it.

### Environment

* WebRTC adaptro version: [2.6.1-SNAPSHOT-2023-May-25-09-03](https://www.npmjs.com/package/@antmedia/webrtc_adaptor/v/2.6.1-SNAPSHOT-2023-May-25-09-03)
* Ant Media Server version: 2.6.0
* Browser name and version: Chrome

![image](https://github.com/ant-media/Ant-Media-Server/assets/48120819/7e1cb35e-ab74-4114-bdde-1961e2836292)

![image](https://github.com/ant-media/Ant-Media-Server/assets/48120819/e9ecbff9-295d-4503-be8e-963d0b35e7d1)

**Comment by allevi18** [comment] 2023-05-26 09:31
UPDATE:
It is happening because iceConnectionState is stuck on "new" and not being updated

**Comment by mekya** [comment] 2023-05-29 10:56
Hi @allevi18,
Could you provide me with a full reproduce scenario? Because it helps us focus on solution directly without losing time.

**Comment by allevi18** [comment] 2023-05-30 09:14
After I disable an internet on mobile device, after successful reconnect I can't send anything to data channel, but can receive messages from others. iceConnectionState is stuck at "new" and checkWebSocketConnection not helping. Tested on iOS and Android - same result. There is no such problem for PC.

**Comment by mekya** [comment] 2023-05-30 15:35
hi @allevi18,
Thank you for this issue. I've just tried on my end for publish and play scenario in iOS device. Unfortunately, I could not reproduce it. Let me tell my scenarios

Scenario 1 
1. Open https://SERVER_ADDRESS:5443/WebRTCAppEE/index.html in iOS Safari
2. Start publishing
3. Connect to iOS Safari through Desktop Safari with developer tools to see the logs
4. Disconnect from network
5. I see that publishing has stopped
6. Connect to network
7. I see that publishing has started
8. I try to send data channel messages and it could send as expected 

Scenario 2
1. Open https://SERVER_ADDRESS:5443/WebRTCAppEE/index.html in Desktop 
2. Start publishing
3. Open https://SERVER_ADDRESS:5443/WebRTCAppEE/player.html in iOS safari
4. Start Playing in iOS 
5. Disconnect from network
6. I see that playing has stopped
7. Connect to network
8. I see that playing has started
9. I try to send data channel messages and it could send as expected and receive from the publisher


Please let me know the scenarios above are correct. Additionally, it will be great if you provide step by step scenario because we can focus on solving the issue directly in this way without spending time to understand/guess the scenario.

**Comment by allevi18** [comment] 2023-06-06 08:58
@mekya You can try to debug it with your conference-call-application. As a user who lost internet connection, I receive messages in datachannel, but can't send. iceConnectionState is stuck at "new" and dataChannel is not ready, however I can see all other participants

**Comment by allevi18** [comment] 2023-06-30 12:49
@mekya Did you manage to reproduce this bug?

**Comment by mekya** [comment] 2023-08-13 16:32
Hi @allevi18,
I just had a chance to check this issue again. 

Yes, I've reproduced the problem. This problem is related to the conference call application reconnect scenario. It's not directly JS SDK issue. 

I've created an issue to fix this problem on the related repo. We try to schedule it soon.  
https://github.com/ant-media/conference-call-application/issues/143

I'm closing this issue and let's follow up there.

**Closed** 2023-08-14 11:30 UTC
