### ISSUE TITLE
Not able to RTMP pull when ingesting using WebRTC

### ISSUE THREAD

**Issue by samidalati** [ant-media/Ant-Media-Server#4170] opened 2022-05-04 15:26 UTC
### Short description
When source stream is WebRTC, the RTMP pull does not work. 

### Environment

* Operating system and version: Ubuntu 20.04
* Java version: openjdk version "11.0.15" 2022-04-19
* Ant Media Server version: Enterprise Edition 2.4.2.1 20220201_1956
* Browser name and version: NA

### Steps to reproduce
1. Ingest stream via WebRTC
2. use ffmpeg/vlc to play the RTMP stream `rtmp://{server url}/WebRTCAppEE/{stream key}`

### Expected behaviour
Since the stream forwarding to youtube/twitch happens over RTMP, the expectation is that RTMP pull works regardless of the source  protocol (RTMP or WebRTC)

### Actual behaviour
RTMP pull fails (HLS pull works tho as intended)
Please note that RTMP pull when source is RTMP works fine

**Comment by yashtandon113** [comment] 2022-05-05 14:10
Hi @samidalati 
Yes, it is expected behavior as we do not support WebRTC to RTMP. Although we do not recommend RTMP playback because we do not maintain it anymore on the server side and most probably it will be removed in future releases after the internal discussion. We provide several other options to playback like WebRTC (0.5 secs), CMAF (3-5 secs), HLS (8-12 secs).

**Comment by samidalati** [comment] 2022-05-06 19:51
Could you kindly provide a way to pull stream using ffmpeg using WebRTC or CMAF

**Comment by yashtandon113** [comment] 2022-05-16 11:39
@samidalati
You can pull the CMAF (Dash) stream with below URL format 
https://your-domain:5443/LiveApp/streams/streamId/streamId.mpd

For WebRTC, you can use Gstreamer to play webrtc stream. One guy in the community has developed this Gstreamer WebRTC connection for Ant Media Server.
https://github.com/SelimEmre/webrtc-ant-media/blob/master/webrtc.py

**Comment by yashtandon113** [comment] 2022-11-24 06:53
Closing this issue. Please feel free to open if you have any questions.

**Closed by yashtandon113** 2022-11-24 06:53 UTC
