### ISSUE TITLE
video getting stuck multiple times while playing

### ISSUE THREAD

**Issue by akashvinfinite** [ant-media/Ant-Media-Server#5470] opened 2023-08-17 12:10 UTC
https://dtmtb9b8de7xr.cloudfront.net/vod/demo-3/MIS-405/AV6/g2_510/next_vision_510-2023-08-14_17-25-31.012.mp4

please look into above video, which is getting stuck multiples times while playing
logs attached

[ant-media-server.3-part.log](https://github.com/ant-media/Ant-Media-Server/files/12369157/ant-media-server.3-part.log)

**Comment by akashvinfinite** [comment] 2023-08-23 11:14
any update on this?

**Comment by akashvinfinite** [comment] 2023-09-05 11:16
@Mohit-3196 @yashtandon113 any update on this?

**Comment by Mohit-3196** [comment] 2023-09-11 09:02
Hi @akashvinfinite ,
Yes, I checked the recorded video and can see the issue that you mentioned.

The logs seem normal to me.
Like all the other cases that you have mentioned and created an issue for, does this one have some kind of reproduce scenarios that we can try and test on our end?

Thank you

**Comment by akashvinfinite** [comment] 2023-09-11 11:39
no @Mohit-3196 , there is no reproduce scenario for this issue

**Comment by Mohit-3196** [comment] 2023-09-11 14:08
Thank you @akashvinfinite 
It seems there are a number of issues and there's no reproduce case for any of these.
Maybe we need to find a way how to proceed and what should be the next steps to consolidate the issues and proceed.

**Comment by mekya** [comment] 2023-09-11 14:29
Thank you @Mohit-3196 @akashvinfinite 

I've just check the video quickly. It seems that it's the connectivity of the encoder. For this case it's drone. 

Please make sure that drone is always having a connection to send the video packets with a good health. If there is a network connection issue on the drone side, we can see these kind of stucks. In other words, Ant Media Server cannot restore the connection issues of the drone or restore packet drops of the drone encoder. 

Please let us know if we can help you further. 

Cheers
Oguz

**Comment by akashvinfinite** [comment] 2023-09-12 07:44
Hi Oguz,

Can you please share which part of the log says that there was network issue on the drone side ?

Thanks
Akash

**Comment by mekya** [comment] 2023-09-14 11:40
I just the see the video and it seems like packet drop issue. 

Let's look at the timestamps of the video packets. Check the image below. It seems that it's jumping from sec 16 to 30 where you see stuck. 

You're using WebRTC(RTP) to publish from the drone. It's very normal to see these kind of things because it's the nature of Real-Time Communicaiton in fluctuating network conditions. 

If you don't want to have any packet drop or very less packet drop, either you make sure you have a good network in the drone with WebRTC or you can use a streaming protocol that uses TCP under the hood like RTMP. The disadvantage of RTMP is that it's slower than WebRTC and the E2E latency increases further if the network is bad.  

Please let me know if we can help you further

<img width="1487" alt="Screenshot 2023-09-14 at 13 17 09" src="https://github.com/ant-media/Ant-Media-Server/assets/3456251/eddc7750-e7f1-421e-ac3a-b8abb1e4586a">

**Comment by akashvinfinite** [comment] 2023-09-15 07:57
Hi Oguz,,

From where did you get this pts_time log, please let me know, so that i can also triage issues before sending it to you.

Thanks
Akash

**Comment by akashvinfinite** [comment] 2023-09-18 10:06
@mekya  @Mohit-3196 @yashtandon113 , can anyone pls answer my question above?

i need to know the log file from where did u get this pts_time.

**Comment by mekya** [comment] 2023-09-18 11:04
Hi @akashvinfinite,
I see you need faster responds. In this channel, we cannot give fast responses.
We give fast responses and schedule issues according to the priority. As you may guess, some customers have paid support packages and we give high priority to respond these users. 
Fortunately, we do our best to give answers to the questions here. I hope you respect us about the way we work.

For your question, this is the command I use 
```
ffprobe -show_packets -i next_vision_510-2023-08-14_17-25-31.012.mp4 | grep "pts_time" 
```

You can get more information on [ffmpeg.org](https://ffmpeg.org) for more options about ffprobe

**Comment by Mohit-3196** [comment] 2023-09-21 08:05
Hi @akashvinfinite ,
I hope this answers your queries.

Let me know if you have any other additional questions or comments.
If not, I'm going to close this issue now.

Thank you

**Comment by mekya** [comment] 2023-09-25 11:52
Closing this issue. Please feel free to re-open if it does not work for you

**Closed by mekya** 2023-09-25 11:52 UTC
