### ISSUE TITLE
Huawei Android Chrome WebRTC setRemoteDescription InvalidAccessError

### ISSUE THREAD

**Issue by StelArian** [ant-media/Ant-Media-Server#1575] opened 2019-10-11 12:04 UTC
Looks like Chrome on Huawei Android devices don't like Antmedia's WebRTC service! Using the out of the box demo (something like https://demo.server.com:5443/WebRTCAppEE/play.html?name=12345678901234567890) we get the following error on every Huawei device we have...

`set remote description is failed with error: InvalidAccessError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Failed to set remote video description send parameters.`

The certificate we use is valid. 

Every other device we test works as expected using valid or invalid development certificate. Can you please try replicate this issue and suggest us a solution?

Server: ant-media-server-enterprise-1.8.1-20190828_1051

**Comment by burak-58** [comment] 2019-10-21 12:11
Sorry for the late response. Please contact me on contact@antmedia.io

**Comment by mekya** [comment] 2019-12-02 16:16
Closing this issue

**Closed by mekya** 2019-12-02 16:16 UTC

**Comment by cdanzig** [comment] 2020-08-03 16:37
Was this every resolved? We're having the same issue.

**Comment by mekya** [comment] 2020-08-04 08:14
Yeah. The problem is Huawei devices don't have h264 for WebRTC. They're supporting VP8. 

Ant Media Server v2.0+ has VP8 support. You can enable VP8 on the server side

Check this out 
https://github.com/ant-media/Ant-Media-Server/wiki/WebRTC-Codecs.
