### ISSUE TITLE
Live Stream/End Stream with WebRTC took almost 100% machine resources on Safari browser on MacOS of Apple chip

### ISSUE THREAD

**Issue by trunghm** [ant-media/Ant-Media-Server#5656] opened 2023-10-06 08:15 UTC
### Short description
__Live Stream/End Stream with WebRTC took almost 100% machine resources and hung the browser for 5-15 seconds on Safari browser on MacOS of Apple chip.__

### Environment

* Operating system and version: Mac OS Sonoma M1/M2 16G RAM. I could also reproduce the issue on Mac OS Ventura
* Ant Media Server version: Enterprise Edition 2.5.0 20221012_1646
* Browser name and version: Safari Version 17.0 (19616.1.27.211.1)

### Steps to reproduce
1. Open the Ant media live demo server (https://antmedia.io/live-demo/) or our development server (https://tstantmds.redhotpie.com.au:5443/LiveApp/index.html)
2. Observe the browser's responsiveness between the time the page loads and the video from the camera appears.

### Expected behavior
__The video appears after 1-2 seconds, same as what the standard webRTC takes - see example at https://webrtc.github.io/samples/src/content/getusermedia/gum/__

### Actual behavior
__The browser hung from when I clicked on the Allow button to allow the camera until the cam appeared. The app appeared to take almost 100% CPU and network resources for about 5-15 seconds. The hung time period is to 15 seconds on Apple M1 Mac Pro, down to 5 seconds on Apple M2 Mac Pro. This issue is only observed on the Safari browser on Mac OS with an Apple chip. It's not happening on other browsers on the same machine, nor the Safari browser of Intel Mac__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by mekya** [comment] 2023-10-09 09:11
Hi @trunghm,

Thank you very much for creating the issue. We plan to handle this issue as a support perspective. I'm putting this to the backlog. 

Regards
Oguz

**Comment by timantmedia** [comment] 2023-10-13 15:35
@trunghm I tested Safari 16.6 on a Mac M1 using the latest version of Ant Media Server and didn't experience any issues. I also tried https://antmedia.io/live-demo with no issues. 

Can you try using https://antmedia.io/live-demo and tell me if you still experience any problems with Safari and Mac?

**Comment by nexlesoft** [comment] 2023-10-16 05:03
Hello @timantmedia ,

Thank you for looking into the issue.

I've checked the site https://antmedia.io/live-demo, and noticed the issue has been improved compared to what I saw earlier, but it's still there. 

There are two things that I think may be helpful for you to check

- check if you do anything on your demo website (e.g., selecting texts) after you click on the Allow button on the camera permission popup until the app gets the video and shows it on the screen. The Safari browser is freezing, and the entire machine is freezing until the app shows the video from the camera.
- compare the taken time between your demo site and standard WebRTC (e.g. https://webrtc.github.io/samples/src/content/getusermedia/gum/), you would see the taken time to get the camera on the standard WebRTC is much shorter.

Please let me know if you need further info.

**Comment by e-vural** [comment] 2023-10-20 13:17
Same problem. I add comparison. 

Device:  Macbook Pro 16 , Apple M1 Max, 32 GB Ram, 1 TB

Safari:

https://github.com/ant-media/Ant-Media-Server/assets/11753784/b757ba3c-d849-4b53-ab69-31442d6faa64

Chrome:

https://github.com/ant-media/Ant-Media-Server/assets/11753784/cd779097-9332-4b4d-ada9-38586eacea77

**Comment by burak-58** [comment] 2024-10-21 10:36
We couldn't reproduce the problem and merge the implementation. So I am closing the issue now. Anyone can re-open the issue if encounter the same problem.

**Closed by burak-58** 2024-10-21 10:36 UTC
Labels: support
