### ISSUE TITLE
Playlist Streaming freezes when changing video

### ISSUE THREAD

**Issue by sbr-dev** [ant-media/Ant-Media-Server#4439] opened 2022-09-29 14:43 UTC
### Short description
Currently streaming a playlist of mp4 files, we have a 6-8 seconds freeze at every file transition.
These freezes are not present using the embeded player. They are when we connect to the stream using HLS or RTMP.

### Environment

* Operating system and version: Ubuntu 20.04
* Java version: openjdk 11.0.16 2022-07-19, OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu120.04), OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)

* Ant Media Server version: Community Edition 2.4.3 20220418_2215

* Browser name and version:  Chrome, but issue is noticed with all HLS or RTMP client

### Steps to reproduce
1. Create a playlist 
2. Stream
3. Connect to the stream

### Expected behavior
I expect the playlist to be played smoothly and the video transition to be quick (something like 0.5 to 1s)

### Actual behavior
 we have a 6-8 seconds freeze at every file transition. From the logs we can see the stream is closed then reopened every time we change file.
Kind of similar to #4226, but applying the solutions mentionned had no effect

### Logs
stream:059697667402114552636329
2022-09-29 14:39:35,407 [Thread-440] INFO  io.antmedia.muxer.HLSMuxer - Adding timebase to the input time base map index:0 value: 1/48000 for stream:059697667402114552636329
2022-09-29 14:39:35,407 [Thread-440] INFO  io.antmedia.muxer.MuxAdaptor - Video format codec Id: 27 width:1920 height:1080 for stream: 059697667402114552636329 source index:1 target index:1
2022-09-29 14:39:35,407 [Thread-440] INFO  io.antmedia.muxer.RtmpMuxer - Adding timebase to the input time base map index:1 value: 1/25000 for stream:059697667402114552636329
2022-09-29 14:39:35,407 [Thread-440] INFO  io.antmedia.muxer.HLSMuxer - Adding timebase to the input time base map index:1 value: 1/25000 for stream:059697667402114552636329
2022-09-29 14:39:35,408 [Thread-440] INFO  io.antmedia.muxer.HLSMuxer - Header is written for stream:059697667402114552636329 and url:/usr/local/antmedia/webapps/TV/streams/059697667402114552636329.m3u8
2022-09-29 14:39:35,408 [Thread-440] INFO  i.a.AntMediaApplicationAdapter - start publish leaved for stream:059697667402114552636329
2022-09-29 14:39:35,408 [Thread-440] INFO  i.a.streamsource.StreamFetcher - last dts-1000 is bigger than incoming dts -1
2022-09-29 14:39:35,408 [Thread-440] WARN  io.antmedia.muxer.RtmpMuxer - Not writing packet1 for 059697667402114552636329 - Is running:false or stream index(1) is registered: true
2022-09-29 14:39:35,408 [Thread-440] INFO  i.a.streamsource.StreamFetcher - last dts0 is bigger than incoming dts 0
2022-09-29 14:39:35,412 [vert.x-worker-thread-24] INFO  io.antmedia.muxer.RtmpMuxer - Header is written for stream:059697667402114552636329 and url:rtmp://172.16.0.1:1935/input/XX 
2022-09-29 14:39:35,412 [vert.x-worker-thread-24] INFO  io.antmedia.muxer.RtmpMuxer - write header takes 1 for rtmp:rtmp://172.16.0.1:1935/input/XX 
2022-09-29 14:39:35,412 [vert.x-worker-thread-24] INFO  io.antmedia.muxer.MuxAdaptor - Endpoint status updated to broadcasting  for streamId: 059697667402114552636329 for url: rtmp://172.16.0.1:1935/input/XX 
2022-09-29 14:39:35,413 [vert.x-worker-thread-24] INFO  i.a.AntMediaApplicationAdapter -  Status of stream 059697667402114552636329 is set to Broadcasting with result: true
2022-09-29 14:39:35,730 [Thread-440] INFO  io.antmedia.muxer.MuxAdaptor - Endpoint status updated to error  for streamId: 059697667402114552636329 for url: rtmp://172.16.0.1:1935/input/XX 
2022-09-29 14:39:35,731 [Thread-440] INFO  io.antmedia.muxer.MuxAdaptor - Endpoint status updated to broadcasting  for streamId: 059697667402114552636329 for url: rtmp://172.16.0.1:1935/input/XX 
2022-09-29 14:39:37,732 [vert.x-eventloop-thread-29] INFO  io.antmedia.muxer.MuxAdaptor - Checking the endpoint health for: rtmp://172.16.0.1:1935/input/XX and status: broadcasting 
2022-09-29 14:39:37,732 [vert.x-eventloop-thread-29] INFO  io.antmedia.muxer.MuxAdaptor - Health check process finished since endpoint rtmp://172.16.0.1:1935/input/XX is broadcasting
2022-09-29 14:40:12,317 [Thread-440] INFO  i.a.streamsource.StreamFetcher - Leaving the stream fetcher loop for stream: 059697667402114552636329
2022-09-29 14:40:12,318 [Thread-440] INFO  i.a.streamsource.StreamFetcher - write all buffered packets for stream: 059697667402114552636329
2022-09-29 14:40:12,318 [Thread-440] INFO  i.a.streamsource.StreamFetcher - Writing trailer in Muxadaptor 059697667402114552636329
2022-09-29 14:40:12,318 [Thread-440] INFO  io.antmedia.muxer.RtmpMuxer - writing trailer for stream: 059697667402114552636329
2022-09-29 14:40:12,318 [Thread-440] INFO  io.antmedia.muxer.MuxAdaptor - Endpoint status updated to finished  for streamId: 059697667402114552636329 for url: rtmp://172.16.0.1:1935/input/XX 
2022-09-29 14:40:12,318 [Thread-440] INFO  io.antmedia.muxer.HLSMuxer - writing trailer for stream: 059697667402114552636329
2022-09-29 14:40:12,323 [Thread-440] INFO  io.antmedia.muxer.HLSMuxer - Delete File onexit:true upload to S3:true stream:059697667402114552636329 hls time:5 hlslist size:10 
2022-09-29 14:40:12,323 [Thread-440] INFO  i.a.AntMediaApplicationAdapter - Closing broadcast stream id: 059697667402114552636329
2022-09-29 14:40:12,324 [Thread-440] INFO  i.antmedia.statistic.HlsViewerStats - Reset HLS Stream ID: 059697667402114552636329 remove failed or null
2022-09-29 14:40:12,324 [Thread-440] WARN  i.a.s.StreamFetcherManager - inside of stopStreaming for 059697667402114552636329
2022-09-29 14:40:12,324 [Thread-440] WARN  i.a.streamsource.StreamFetcher - stop stream called for http://172.16.0.5:5080/TV/streams/CTV_PUBS/CTV_PUBS_00014.mp4
2022-09-29 14:40:12,324 [Thread-440] INFO  i.a.s.StreamFetcherManager - Next index to play in play list is 13 for stream: 059697667402114552636329
2022-09-29 14:40:14,340 [Thread-441] INFO  i.a.streamsource.StreamFetcher - StartStream called, new thread is started for 059697667402114552636329
2022-09-29 14:40:14,345 [Thread-442] INFO  i.a.streamsource.StreamFetcher - Preparing the StreamFetcher for http://172.16.0.5:5080/TV/streams/CTV_PUBS/CTV_PUBS_00015.mp4 for streamId:059697667402114552636329
2022-09-29 14:40:14,425 [Thread-442] ERROR io.antmedia.muxer.MuxAdaptor - io.antmedia.enterprise.adaptive.EncoderAdaptor
2022-09-29 14:40:14,425 [Thread-442] INFO  i.a.AntMediaApplicationAdapter -  Status of stream 059697667402114552636329 is set to Broadcasting with result: true
2022-09-29 14:40:14,425 [Thread-442] INFO  io.antmedia.muxer.MuxAdaptor - serverSettings exist io.antmedia.settings.ServerSettings@4fc1af2c
2022-09-29 14:40:14,425 [Thread-442] INFO  io.antmedia.muxer.MuxAdaptor - vertx exist io.vertx.core.impl.VertxImpl@381314ed
2022-09-29 14:40:14,426 [Thread-442] INFO  io.antmedia.muxer.MuxAdaptor - serverSettings exist io.antmedia.settings.ServerSettings@4fc1af2c
2022-09-29 14:40:14,426 [Thread-442] INFO  io.antmedia.muxer.MuxAdaptor - adding HLS Muxer for 059697667402114552636329
2022-09-29 14:40:14,427 [Thread-442] INFO  io.antmedia.muxer.HLSMuxer - hls time: 5, hls list size: 10 for stream:059697667402114552636329
2022-09-29 14:40:14,427 [Thread-442] INFO  i.a.streamsource.StreamFetcher - 059697667402114552636329 stream count in stream http://172.16.0.5:5080/TV/streams/CTV_PUBS/CTV_PUBS_00015.mp4 is 2
2022-09-29 14:40:14,427 [Thread-442] INFO  io.antmedia.muxer.MuxAdaptor - Audio format sample rate:48000 bitrate:317190 for stream: 059697667402114552636329 source index:0 target index:0
2022-09-29 14:40:14,427 [Thread-442] INFO  io.antmedia.muxer.RtmpMuxer - Creating outputFormatContext
2022-09-29 14:40:14,427 [Thread-442] INFO  io.antmedia.muxer.RtmpMuxer - Adding timebase to the input time base map index:0 value: 1/48000 for stream:059697667402114552636329
2022-09-29 14:40:14,427 [Thread-442] INFO  io.antmedia.muxer.HLSMuxer - Adding timebase to the input time base map index:0 value: 1/48000 for stream:059697667402114552636329
2022-09-29 14:40:14,427 [Thread-442] INFO  io.antmedia.muxer.MuxAdaptor - Video format codec Id: 27 width:1920 height:1080 for stream: 059697667402114552636329 source index:1 target index:1
2022-09-29 14:40:14,427 [Thread-442] INFO  io.antmedia.muxer.RtmpMuxer - Adding timebase to the input time base map index:1 value: 1/25000 for stream:059697667402114552636329
2022-09-29 14:40:14,428 [Thread-442] INFO  io.antmedia.muxer.HLSMuxer - Adding timebase to the input time base map index:1 value: 1/25000 for stream:059697667402114552636329
2022-09-29 14:40:14,428 [Thread-442] INFO  io.antmedia.muxer.HLSMuxer - Header is written for stream:059697667402114552636329 and url:/usr/local/antmedia/webapps/TV/streams/059697667402114552636329.m3u8
2022-09-29 14:40:14,428 [Thread-442] INFO  i.a.AntMediaApplicationAdapter - start publish leaved for stream:059697667402114552636329
2022-09-29 14:40:14,428 [Thread-442] INFO  i.a.streamsource.StreamFetcher - last dts-1000 is bigger than incoming dts -1
2022-09-29 14:40:14,429 [Thread-442] WARN  io.antmedia.muxer.RtmpMuxer - Not writing packet1 for 059697667402114552636329 - Is running:false or stream index(1) is registered: true
2022-09-29 14:40:14,429 [Thread-442] INFO  i.a.streamsource.StreamFetcher - last dts0 is bigger than incoming dts 0
2022-09-29 14:40:14,432 [vert.x-worker-thread-33] INFO  io.antmedia.muxer.RtmpMuxer - Header is written for stream:059697667402114552636329 and url:rtmp://172.16.0.1:1935/input/XX 
2022-09-29 14:40:14,432 [vert.x-worker-thread-33] INFO  io.antmedia.muxer.RtmpMuxer - write header takes 0 for rtmp:rtmp://172.16.0.1:1935/input/XX 
2022-09-29 14:40:14,432 [vert.x-worker-thread-33] INFO  io.antmedia.muxer.MuxAdaptor - Endpoint status updated to broadcasting  for streamId: 059697667402114552636329 for url: rtmp://172.16.0.1:1935/input/XX 
2022-09-29 14:40:14,433 [vert.x-worker-thread-33] INFO  i.a.AntMediaApplicationAdapter -  Status of stream 059697667402114552636329 is set to Broadcasting with result: true
2022-09-29 14:40:14,753 [Thread-442] INFO  io.antmedia.muxer.MuxAdaptor - Endpoint status updated to error  for streamId: 059697667402114552636329 for url: rtmp://172.16.0.1:1935/input/XX 
2022-09-29 14:40:14,753 [Thread-442] INFO  io.antmedia.muxer.MuxAdaptor - Endpoint status updated to broadcasting  for streamId: 059697667402114552636329 for url: rtmp://172.16.0.1:1935/input/XX 
2022-09-29 14:40:16,754 [vert.x-eventloop-thread-30] INFO  io.antmedia.muxer.MuxAdaptor - Checking the endpoint health for: rtmp://172.16.0.1:1935/input/XX and status: broadcasting 
2022-09-29 14:40:16,754 [vert.x-eventloop-thread-30] INFO  io.antmedia.muxer.MuxAdaptor - Health check process finished since endpoint rtmp://172.16.0.1:1935/input/XX is broadcasting

**Comment by sbr-dev** [comment] 2022-10-01 10:30
Following our investigation, 

- we found out the stream is closed then reopened every time we change file. 
- WebRTC is not affected by the issue. 
- We suspect the buffer on the client side to not be shared between the "videos" (first we empty the buffer of video 1, once the video 2 started to play we refill the buffer before playing)

Do you think this as an expected behaviour or is there an existing solution?

Cheers

**Comment by mekya** [comment] 2022-10-03 10:29
Hi @sbr-dev ,

There is an existing solution for this case. Could you please check this out?

https://github.com/ant-media/Ant-Media-Server/issues/4226#issuecomment-1144769856

**Comment by mekya** [comment] 2022-10-03 10:31
> Hi @sbr-dev ,
> 
> There is an existing solution for this case. Could you please check this out?
> 
> [#4226 (comment)](https://github.com/ant-media/Ant-Media-Server/issues/4226#issuecomment-1144769856)

Sorry you already mention about the issue #4226, it's likely that there is something different in your scenario. Maybe we can schedule a quick call to help you.

**Comment by sbr-dev** [comment] 2022-10-03 14:54
@mekya Thank you for your feedback.
A call would be great, just let me know when @yashtandon113 

B/R

**Comment by yashtandon113** [comment] 2022-10-04 06:34
@sbr-dev 
Sure, please let me know when you are available for the meeting and share your email address. You can also contact me via email at yash.tandon@antmedia.io.

**Comment by yashtandon113** [comment] 2022-10-06 07:40
@sbr-dev 
Thanks for joining the meeting yesterday.
It seems the issue is on your VLC media player as stream works fine on the browser. We are not able to reproduce the issue at our end on VLC player.
Please let us know if you have any questions.

**Comment by mekya** [comment] 2022-11-01 13:44
Hi @sbr-dev ,

Could you please let us have some update?

I'm closing the issue and feel free to re-open if you still have some problems. 

Cheers,
A. Oguz

**Closed by mekya** 2022-11-01 13:44 UTC
Labels: Priority: Low

**Comment by sbr-dev** [comment] 2022-11-01 19:53
Sure, 

as @yashtandon113 said, issue was coming from local VLC player ;)

All the best

**Comment by mekya** [comment] 2022-11-02 13:27
Hmm, I see then we need a solution that does not stop and start streams in the backend to make it compatible with VLC player. 

We receive a similar request from some users. I think we can put this to our pipeline.
