### ISSUE TITLE
initial 3 seconds of the video is skipped

### ISSUE THREAD

**Issue by akashvinfinite** [ant-media/Ant-Media-Server#5369] opened 2023-07-17 09:13 UTC
Hi,

in the below video which was recorded on 12th July, the initial 3seconds of the video is skipped automatically, looks like some issue there, can you please check

https://dtmtb9b8de7xr.cloudfront.net/vod/demo-3/INC-880-20230712T22:03:19/AV6/g2_510/next_vision_510-2023-07-12_22-06-51.005.mp4

**Comment by USAMAWIZARD** [comment] 2023-07-28 07:46
Hi @akashvinfinite We have investigate the issue with one of our scenario developers and this is the summary of our discussion 

**Issue discussed ** 
During our investigation we found out that the PTS and DTS value for the Mp4 file is starting from 3 seconds that is what  is causing the jump of 3 seconds when the video starts. 

![Screenshot from 2023-07-27 18-12-41](https://github.com/ant-media/Ant-Media-Server/assets/47350008/97988702-41c0-417a-835c-f8a64eb02102)

**Suspected Cause of the Issue** 
**Cause  1**
This may be caused due to some RMTP Encoders Delays  the video for some time this may cause this unexpected jump in the video.

**Cause  2**
This may also be possible because of Key Frame of the Video being lost or Delayed That Can also cause this issue.


**Can you please provide us a reproduce scenario @akashvinfinite **
@akashvinfinite Is this problem occurring every time or it just occurred once ? Please provide us a reproduce scenario for this issue so that we can Reproduce this issue at our end and try to resolve the issue. 

a Ant Media we truly care about what our users have to say, and we're dedicated to making our product better based on your feedback Thanks again @akashvinfinite for reporting the issue.

**Comment by USAMAWIZARD** [comment] 2023-08-03 12:51
Hi @akashvinfinite did you check our previous reply ?

**Comment by mekya** [comment] 2023-08-07 11:23
This issue is being closed for the inactivity and user reported that he has not get the same problem again.

**Comment by akashvinfinite** [comment] 2023-08-09 11:52
here we have another instance where initial 11 seconds of the video is skiiped

https://dtmtb9b8de7xr.cloudfront.net/vod/demo-3/MIS-324/AV2/DJI-SD1/AV2-DJI-SD1-2023-08-07_16-55-09.005.mp4

**Comment by USAMAWIZARD** [comment] 2023-08-09 13:21
@akashvinfinite, does this problem happen very frequently,or is it happening very rarely ? Could you give us step-by-step instructions on how to make this issue happen again? This will help us recreate the problem on our side and work towards finding a solution.

**Comment by akashvinfinite** [comment] 2023-08-09 13:53
no, it doesn't happen frequently, it is rare.

there is no step by step process to reproduce this issue, we encounter this issue while our normal testing only

**Comment by akashvinfinite** [comment] 2023-08-10 12:20
any update on this issue?

**Comment by akashvinfinite** [comment] 2023-08-11 11:48
https://github.com/SelimEmre/webrtc-ant-media

**Comment by mekya** [comment] 2023-08-14 08:28
Hi @akashvinfinite,

Thank you. We don't maintain that script officialy. Developer just took initiative and provided you a solution. 

Maybe setting key frame interval help. Could you please help resolve your issue? I mean could you check that if there is a way to set the key frame interval in the Gstreamer pipeline.

Regards

**Comment by USAMAWIZARD** [comment] 2023-08-15 05:52
@akashvinfinite  are you recording the file as Mp4 or Vp8 ?

**Comment by akashvinfinite** [comment] 2023-08-16 08:12
mp4

**Comment by USAMAWIZARD** [comment] 2023-08-16 08:19
@mekya abi @akashvinfinite is recording the files as mp4 , but the gstreamer  pipeline that he is using is sending a VP8 streams , And the will be transcoded to h264 before saving the file as mp4. Can that cause this issue ?

**Comment by akashvinfinite** [comment] 2023-08-16 08:32
![Screenshot 2023-08-16 140151](https://github.com/ant-media/Ant-Media-Server/assets/139755423/9273408a-f764-4ac2-9181-5c3d234901c8)


please open this issue

**Comment by akashvinfinite** [comment] 2023-08-18 10:18
@mekya @USAMAWIZARD    ---- any update on this request ?

**Comment by USAMAWIZARD** [comment] 2023-08-18 10:27
Can you please try with [this ](https://github.com/USAMAWIZARD/webrtc-ant-media/blob/master-1/webrtc.py)script , I have 
 set keyframe interval to 2 sec and changed the code to h264 , now mp4 file can be saved without transcoding.

https://github.com/USAMAWIZARD/webrtc-ant-media/blob/master-1/webrtc.py

**Comment by akashvinfinite** [comment] 2023-08-24 11:01
can we have a meeting for 30 min to better understand the issue & the fix you provided

**Comment by USAMAWIZARD** [comment] 2023-08-25 06:19
did you tired with the updated script ?

**Comment by akashvinfinite** [comment] 2023-08-25 07:57
no, that change is not possible in our script, my question here is how would changing the keyframe interval to 2 sec fix this problem ?

we can discuss more on this in our meeting which i want to schedule with you.

please let me know a suitable time for the meeting.

**Comment by USAMAWIZARD** [comment] 2023-08-28 11:29
@akashvinfinite  please try with the updated script and let me know

**Comment by akashvinfinite** [comment] 2023-08-28 12:33
@USAMAWIZARD  , I have few questions:-
how did you test/reproduce this issue at your end?
how did you come to the conclusion that changing the keyframe to 2sec will fix it?
how did you test the fix you made ?

**Comment by USAMAWIZARD** [comment] 2023-08-28 12:59
> **Cause 2** This may also be possible because of Key Frame of the Video being lost or Delayed That Can also cause this issue.

So by reducing the key frame interval we make sure that the frequency of the key-frame is minimum and this will be less very likely to occur  

> @USAMAWIZARD , I have few questions:- how did you test/reproduce this issue at your end? how did you come to the conclusion that changing the keyframe to 2sec will fix it? how did you test the fix you made ?

as you know the problem is very rarely occurring and there is no reproduce  scenario  it hard for me to test it on my end.

**Comment by akashvinfinite** [comment] 2023-08-29 11:03
2 action items on antmedia/Usama as per discussion:

1. Enable logging to track key frames and frame drops in antmedia server logs.

2. Try to reproduce issue with unstable network connectivity like mobile network with low signal.

**Comment by Mohit-3196** [comment] 2023-09-04 12:24
Hi @akashvinfinite,
How are you doing?

I had a discussion with @USAMAWIZARD about this issue and I understand that it is something pressing for you guys. Also, it's been a long time since we have been trying to work around this issue and have a solution.

As I understood from Usama according to the meeting that he had with you and your team, and also from the conversation above, my colleague updated some parameters in the GStreamer script with regard to the keyframe interval, etc. He made these changes as per the recommendations of our lead developer and is requesting you try the updated script to see if it resolves the issue.

It appears that your team is seeking some form of tangible evidence that trying these updates will definitively rectify the issue. However, it is important to acknowledge that the core challenge we face is the absence of a precise scenario that can consistently reproduce the problem. In instances where a reproducible scenario remains elusive, providing irrefutable proof becomes inherently complex. 
There are a lot of variables in the setup here, from drone to Gstreamer to UDP to WebRTC and hence a reproduce scenario is of foremost importance to test the issue and test the solutions. Unfortunately, as we don't have a reproduce case that can help us reproduce the issue, we can only make some informed decisions, and on the basis of those we can try out different solutions to solve the issue.

Therefore, rather than engaging in a protracted back-and-forth, I propose that we collaborate closely to surmount this challenge. I kindly urge you to conduct the tests with the updated script as advised by my colleague. Should these tests fail to yield a resolution, please rest assured that we remain committed to assisting you until the issue is conclusively resolved, working together in tandem.

Thank you for your understanding.

**Comment by Mohit-3196** [comment] 2023-09-11 08:52
Hi @akashvinfinite,
How are you doing?

Let me know if your team had a chance to try the suggestion made by Usama in the script.
In case you plan to test it then please let me know.

Thank you

**Comment by Mohit-3196** [comment] 2023-09-21 08:04
Hi @akashvinfinite ,
It seems you are not available right now.

I'm closing this issue here for inactivity. Please feel free to reopen when you have any comments for me or @USAMAWIZARD 

Thank you

**Closed** 2023-09-25 10:21 UTC
Labels: support
