### ISSUE TITLE
Inconsistent programmingDateTime and duration in HLS m3u8 file

### ISSUE THREAD

**Issue by oleul05** [ant-media/Ant-Media-Server#6506] opened 2024-07-18 02:40 UTC
Thank you for your continued support.
We are saving programDateTime and duration by parsing m3u8 playlist. For one camera we observed we got some future date and abnormal duration. For few .ts files I observed date is 30th June 2024 which is a future date. The files duration was 72,30 28 seconds which is strange to us.
I have attached a screenshot from MongoDB where we saved the information.
Note: In AMS setting, duration is set to 2 seconds, and most cameras are working fine.

* Operating system and version: Ubuntu 20.04
* Java version: 17
* Ant Media Server version: Enterprise Edition 2.8.2 20240201_1142
* Browser name and version: all browser

### Steps to reproduce
1. Start RTMP stream from LTE camera into Ant Media RTMP server
2. Check HLS m3h8 file for that stream.
3. In m3u8 file the programDateTime is future date and duration is inconsistent.

### Expected behavior
programDateTime is current date and duration is 2 seconds.

### Actual behavior
 programDateTime is future date and duration is inconsistent.
 
 
![attachment](https://github.com/user-attachments/assets/d0b119a1-2825-4164-bc92-c3a3ec293da3)

**Comment by oleul05** [comment] 2024-07-18 06:36
@mekya, @burak-58 ,
In the LTE camera settings, setting the Frame Rate (FPS) to 20 and GOP (100ms) to 20 provides the expected results. Any other Frame Rate and GOP values lead to incorrect duration and program date time in the `.m3u8` file.
![image](https://github.com/user-attachments/assets/0ac5978a-98a7-4459-bb81-3599c10bcf0a)

**Comment by burak-58** [comment] 2024-07-23 10:45
Hi @oleul05 
Could you please do a test with ffmpeg like that:
- Run this command to convert RTMP ingest to HLS:
ffmpeg -listen 1 -i rtmp://IP_ADDRESS:1935/live -c copy -hls_flags program_date_time -f hls output.m3u8

- Then stream your camera to:
rtmp://IP_ADDRESS:1935/live

Then check HLS files.

**Comment by mekya** [comment] 2024-08-12 12:08
I've encountered the same problem and it causes the server to return wrong internal when asking `m3u8` with `start` and `end` query parameters

**Comment by lastpeony** [comment] 2024-08-16 12:34
Hello @oleul05,

How long into the streaming do you encounter this issue? Is it reproducible after a few minutes?

Have you tested the problematic camera with non-integer GOP and frame rate values, such as 36/30? What were the GOP and FPS settings when you experienced the problem?

When using integer values for GOP and FPS, like GOP: 30 FPS: 30 or GOP: 60 FPS: 30, do you still encounter this issue?

We suspect that a non-integer GOP/ FPS ratio might be causing this problem. I am attempting to reproduce the issue with ffmpeg but haven't had success so far.

**Comment by oleul05** [comment] 2024-08-20 08:14
@lastpeony We get this issue immediately after starting the stream.
When using the GOP FPS ration 20/20 in this case it was working fine. On the all other ration like 30/20 we got unexpected results.

**Comment by lastpeony** [comment] 2024-09-23 08:49
We conducted a test with @oleul05 using different GOP and FPS combinations.

We were able to reproduce the issue on version 2.8, but could not replicate it on version 2.11.3.

If you're experiencing this problem, please upgrade to version 2.11.3 (the latest as of today).

**Comment by burak-58** [comment] 2024-09-30 11:17
I am closing this because didn't get response from @oleul05  and any further report with this scenario.

**Closed by burak-58** 2024-09-30 11:17 UTC
