### ISSUE TITLE
Can't stop a broadcast created using /api/v2/filters/create

### ISSUE THREAD

**Issue by tomyates** [ant-media/Ant-Media-Server#3678] opened 2021-10-17 13:09 UTC
### Short description

I'm following the guide here:
https://github.com/ant-media/Plugins/tree/master/FilterPlugin#how-to-change-mcu-layout
And created a stream with the filter plugin end-point:

`curl -i -X POST -H "Accept: Application/json" -H "Content-Type: application/json" "http://X.X.X.X:5080/WebRTCAppEE/rest/v2/filters/create" -d '{"inputStreams":["room1","room2"],"outputStreams":["testMerged"],"videoFilter":"[in0]scale=354:234:force_original_aspect_ratio=decrease,pad=360:240:3:3:color=black[s0];[in1]scale=354:234:force_original_aspect_ratio=decrease,pad=360:240:3:3:color=black[s1];[s0][s1]hstack=inputs=2,pad=120:480:(ow-iw)/2:(oh-ih)/2[out0]","audioFilter":"[in0]acopy[out0]","videoEnabled":"true","audioEnabled":"true"}'`

However, if I try and stop this broadcast, it fails.
If I try and delete the broadcast, it will delete it, but not stop it.

#### Delete (via API call or from console)

`curl -i -X DELETE -H "Accept: Application/json" -H "Content-Type: application/json" "http://X.X.X.X:5080/WebRTCAppEE/rest/v2/broadcasts/testMerged"
`
Api message returned:
`broadcast is deleted but could not stopped`

#### Stop

If I try and use the stop broadcast API end-point I get a "false" returned from the API:

`curl -i -X POST -H "Accept: Application/json" -H "Content-Type: application/json" "http://X.X.X.X:5080/WebRTCAppEE/rest/v2/broadcasts/testMerged2/stop"
`

`{"success":false,"message":null,"dataId":null,"errorId":0}`

### Environment

* Operating system and version: Ubuntu 18.04
* Ant Media Server version:  Ant Media Server Enterprise v2.4.0.2 (AWS Marketplace AMI).

Thanks, any help would be greatly appreciated.

**Comment by Mohit-3196** [comment] 2021-11-01 13:17
Hello @mekya abi,

The issue is reproducible, When we make the REST API call to stop the stream, it gives status code 200 but success is false.
The console logs show:
2021-11-01 12:41:55,022 [network_thread - 11431] INFO  i.a.enterprise.webrtc.WebRTCClient - IceConnectionState: CONNECTED instance: 139685469
2021-11-01 12:41:55,022 [network_thread - 11431] INFO  i.a.enterprise.webrtc.WebRTCClient - Timing:OnIceConnection Connected state takes 356ms hash:139685469 remoteDescriptionSet:true
2021-11-01 12:41:55,022 [network_thread - 11431] INFO  i.a.enterprise.webrtc.WebRTCClient - Starting streaming for testMerged2
2021-11-01 12:41:55,022 [vert.x-eventloop-thread-6] INFO  i.a.enterprise.webrtc.WebRTCClient - registering webrtc client 139685469 with codec H264 to webrtc adaptor for streamId testMerged2
2021-11-01 12:41:55,022 [vert.x-eventloop-thread-6] INFO  i.a.enterprise.webrtc.WebRTCMuxer - register webrtc client(139685469) to webrtc muxer(240p - codec:H264) for stream: testMerged2 current viewer count:1
2021-11-01 12:41:55,022 [network_thread - 11431] INFO  org.webrtc.Logging - Tag:WebRtcAudioRecordExternal - Message:startRecording
2021-11-01 12:41:55,023 [vert.x-eventloop-thread-6] INFO  i.a.e.w.WebRTCPlayStreamInfoListener - A new viewer started streaming of testMerged2
2021-11-01 12:42:00,023 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:139685469 for stream testMerged2 current video bitrate: 500000 audio bitrate: 32000 webrtc client target bitrate: 172000
2021-11-01 12:42:05,024 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:139685469 for stream testMerged2 current video bitrate: 500000 audio bitrate: 32000 webrtc client target bitrate: 172000
2021-11-01 12:42:06,703 [https-jsse-nio2-0.0.0.0-5443-exec-5] INFO  i.a.enterprise.webrtc.WebRTCMuxer - unregister webrtc client(139685469) to webrtc muxer(240p - codec:H264) for stream: testMerged2 current viewer count:0 decremented:true
2021-11-01 12:42:06,704 [https-jsse-nio2-0.0.0.0-5443-exec-5] INFO  i.a.enterprise.webrtc.WebRTCClient - Clearing native stats timer for stream:testMerged2 and viewer hashcode:139685469
2021-11-01 12:42:06,705 [network_thread - 11431] INFO  i.a.enterprise.webrtc.WebRTCClient - IceConnectionState: DISCONNECTED instance: 139685469
2021-11-01 12:42:06,705 [vert.x-eventloop-thread-6] INFO  i.a.enterprise.webrtc.WebRTCClient - Stop is called for testMerged2 for 139685469
2021-11-01 12:42:06,705 [vert.x-eventloop-thread-6] INFO  i.a.enterprise.webrtc.WebRTCMuxer - unregister webrtc client(139685469) to webrtc muxer(240p - codec:H264) for stream: testMerged2 current viewer count:0 decremented:false
2021-11-01 12:42:06,705 [vert.x-eventloop-thread-6] INFO  i.a.enterprise.webrtc.WebRTCClient - Disposing audio source for stream Id testMerged2 viewer hashcode:139685469
2021-11-01 12:42:06,705 [vert.x-eventloop-thread-6] INFO  i.a.enterprise.webrtc.WebRTCClient - Closing and disposing peer connection for stream Id testMerged2 for 139685469
2021-11-01 12:42:06,706 [network_thread - 11431] INFO  org.webrtc.Logging - Tag:WebRtcAudioTrackExternal - Message:GetPlayoutUnderrunCount
2021-11-01 12:42:06,706 [network_thread - 11431] INFO  i.a.enterprise.webrtc.WebRTCClient - IceConnectionState: CLOSED instance: 139685469
2021-11-01 12:42:06,706 [network_thread - 11431] INFO  i.a.enterprise.webrtc.WebRTCClient - Stop is already called for testMerged2 viewer hashcode:139685469
2021-11-01 12:42:06,706 [network_thread - 11431] INFO  i.a.enterprise.webrtc.WebRTCClient - onSignalingChange : CLOSED
2021-11-01 12:42:06,706 [network_thread - 11431] INFO  org.webrtc.Logging - Tag:WebRtcAudioRecordExternal - Message:stopRecording
2021-11-01 12:42:06,708 [vert.x-eventloop-thread-6] INFO  i.a.enterprise.webrtc.WebRTCClient - Closing peer connection factory for testMerged2 viewer hashcode:139685469
2021-11-01 12:42:06,708 [vert.x-eventloop-thread-6] INFO  i.a.enterprise.webrtc.WebRTCClient - Stopping webrtc client number of send audio packet call: 0 send video packet call: 0 client id: 139685469
2021-11-01 12:42:06,709 [vert.x-eventloop-thread-6] INFO  i.a.e.w.WebRTCPlayStreamInfoListener - A viewer stopped streaming for testMerged2
2021-11-01 12:45:09,588 [vert.x-eventloop-thread-0] INFO  i.antmedia.statistic.StatsCollector - System cpu load:0 process cpu load:0 available memory: 6496132 KB used memory(RSS): 708736 KB
2021-11-01 12:45:09,588 [vert.x-eventloop-thread-0] INFO  i.antmedia.statistic.StatsCollector - Vertx worker queue size:0 WebRTCVertx worker queue size:0

While making the DELETE call, though it deletes the stream from the dashboard and status code is 200 with "success": true,
    "message": "broadcast is deleted but could not stopped ",
The log says
2021-11-01 12:47:17,968 [https-jsse-nio2-0.0.0.0-5443-exec-7] ERROR io.antmedia.rest.RestServiceBase - No active broadcast found with id testMerged3, so could not stopped
2021-11-01 12:47:17,970 [https-jsse-nio2-0.0.0.0-5443-exec-7] INFO  io.antmedia.rest.RestServiceBase - broadcast io.antmedia.datastore.db.types.Broadcast@63f4a0d is deleted but could not stopped

**Comment by Mohit-3196** [comment] 2021-11-08 06:59
Hi @tomyates,
You can make the below written calls to first get the FilterId or you can even provide the FilterId yourself when creating the filter: 

Get Filter List:
curl -i -X GET -H "Accept: Application/json" "http://localhost:5080/WebRTCAppEE/rest/v2/filters/list/0/10"

When you call the delete filter method, the broadcast is both stopped and deleted

Delete Filter:
curl -i -X DELETE -H "Accept: Application/json" "http://localhost:5080/WebRTCAppEE/rest/v2/filters/filter1"

**Closed** 2022-01-26 14:07 UTC
